### ISSUE TITLE
[ DestinE ] Expand autosubmit 4 dependencies, a task split should be able to depend on any other task.split.

### ISSUE THREAD

**Issue by kinow** [BSC-ES/autosubmit#1023]
In GitLab by @dbeltrankyl on Apr 26, 2023, 12:30

This is an issue to expand the v4.0.0 dependencies to consider the "old select_member/chunk" but for splits. 

The idea is that a split of the current task can depend on any other task split. 

* [X] Fixed an issue with splits not being selectable ( included in v3.15.0) 
* [x] Autosubmit 4.0.0 check if the dependencies changes are working with splits ( I think the select part is not done for splits. It works for a date, member, and chunk )   
* [X] Support optional dependencies
* [X] Add tests

FYI: @mcastril

**Comment by kinow** [comment]
In GitLab by @dbeltrankyl on May 11, 2023, 08:39

Working on this issue, the split is already working partially in 4.0.0

**Comment by kinow** [comment]
In GitLab by @dbeltrankyl on Jun 6, 2023, 11:35

mentioned in issue digital-twins/de_340/project_management#118

**Comment by kinow** [comment]
In GitLab by @dbeltrankyl on Jun 13, 2023, 10:00

marked the checklist item **Autosubmit 4.0.0 check if the dependencies changes are working with splits ( I think the select part is not done for splits. It works for a date, member, and chunk )** as completed

**Comment by kinow** [comment]
In GitLab by @dbeltrankyl on Jun 13, 2023, 10:01

FYI @franra9  

AS v4.0.0b20 is now available in lumivm ( https://earth.bsc.es/gitlab/es/autosubmit/-/tags/4.0.0b20 summary) 



Select splits is integrated with the advanced dependencies,  like this example
https://autosubmit.readthedocs.io/en/master/userguide/defining_workflows/index.html#example-1-how-to-select-an-specific-chunk

Short ""select_splits"",  example:

```yaml
  DN:
    ADDITIONAL_FILES:
    - templates/dn.yml
    - lib/runscript/run_dn.py
    DEPENDENCIES: REMOTE_SETUP
    FILE: templates/dn.sh
    RUNNING: chunk
    SPLITS: 2
    WALLCLOCK: 00:05
  OPA:
    ADDITIONAL_FILES:
    - templates/opa.yml
    - lib/runscript/run_opa.py
    DEPENDENCIES:
      DN:
        SPLITS_FROM:
          "1,2":
            #DATES_TO
            #MEMBERS_TO
            #CHUNKS_TO 
            SPLITS_TO: "1"
          "3,4":
            SPLITS_TO: "2"
    FILE: templates/opa.sh
    RUNNING: chunk
    SPLITS: 4
    WALLCLOCK: 00:05
```
Which will link splits 1,2 from OPA to DN 1 and splits from 2,4 to DN 2.  


If you have any doubts, or bug please continue the discussion on this issue ( so the information can be spread easily)
