### ISSUE TITLE
Bug in refresh

### ISSUE THREAD

**Issue by kinow** [BSC-ES/autosubmit#1037]
In GitLab by @dbeltrankyl on May 16, 2023, 12:12

Seems that there is a bug with the platform checker in the 4.0.0b17 when only part of the platform info exists,

The bug is that the create/refresh check_conf is not reading the "only_experiment_data" flag correctly 

## WORKAROUND 
To workaround it in v4.0.0b17, modify the minimal.yml:

```
[dbeltran@climatedt-wf conf]$ cat minimal.yml
CONFIG:
  AUTOSUBMIT_VERSION: "4.0.0b0"
  TOTALJOBS: 20
  MAXWAITINGJOBS: 20
DEFAULT:
  EXPID: "a03c"
  HPCARCH: "lumi"
  #hint: use %PROJDIR% to point to the project folder (where the project is cloned)
  CUSTOM_CONFIG:
    PRE:
     - "%PROJDIR%/conf/jobs.yml"
     - "%PROJDIR%/conf/platforms.yml"
    #POST:
     #- "~/platforms.yml"
```

perform :

`autosubmit create a03d -v`

and then modify again the minimal.yml with the original configuration:

```
[dbeltran@climatedt-wf conf]$ cat minimal.yml
CONFIG:
  AUTOSUBMIT_VERSION: "4.0.0b0"
  TOTALJOBS: 20
  MAXWAITINGJOBS: 20
DEFAULT:
  EXPID: "a03c"
  HPCARCH: "lumi"
  #hint: use %PROJDIR% to point to the project folder (where the project is cloned)
  CUSTOM_CONFIG:
    PRE:
     - "%PROJDIR%/conf/jobs.yml"
     - "%PROJDIR%/conf/platforms.yml"
    POST:
     - "~/platforms.yml"
...
```
