### ISSUE TITLE
POST does not override values in PLATFORMS

### ISSUE THREAD

**Issue by kinow** [BSC-ES/autosubmit#1052]
I will update the template below later. I was going through my notes and emails, organizing everything, and found one from yesterday. I was debugging an issue in the mHM workflow, where the workflow project has a file `bootstrap/include.yml` similar to the climatedt workflow, with a `PRE` loading a directory `%PROJDIR%/conf` that contains a `platforms.yml` with values like `<USERNAME>` or `<REPLACEME>`. In the `POST` in the same file, it loads `~/platforms.yml` with the exact same structure as the other `%PROJDIR/conf/platforms.yml` file, but with actual values. I expected it to replace the `<REPLACEME>` values, but apparently it doesn't work.

Creating this so I don't forget to report/discuss in the next AS meeting. If confirmed I can create an experiment and use it in the template below...

( This is a template for bug reports. Please fill in the relevant information and delete the rest. )

Hello @dbeltrankyl and @kinow,

### Autosubmit Version

(Which version of Autosubmit are you using? ex: v3.14.0, v3.15.0b, v4.0.0b , tag:v4.0.0b2)

### Expid affected(If applicable)

(Which expid is affected?)

### Which task has issues? Where is the log(If applicable)

* **Full_name**: expid_taskname (ex: a000_19600101_fc0099_2_SIM)

* **Log_Path:** log path (ex: /esarchive/autosubmit/a000/Log_a000/a057_19600101_fc0099_2_SIM.20230208100046.out)

### Summary

(Summarize the bug encountered concisely)

### Steps to reproduce

(How one can reproduce the issue - this is very important)

### What is the current bug behavior?

(What actually happens)

### What is the expected correct behavior?

(What you should see instead)

### Relevant logs and/or screenshots(if applicable)

(Paste any relevant logs - use code blocks (```) to format console output, logs, and code, as
it's very hard to read otherwise.)

### Any other relevant information(if applicable)

()

**Comment by kinow** [comment]
In GitLab by @mcastril on Aug 31, 2023, 10:44

Do you know how it can be reproduced easily Bruno?

**Comment by kinow** [comment]
I think I recall more or less what I had in my experiment... I tried to quickly recreate it (cc @dbeltrankyl ), I believe what happened was that I had a `conf/platforms.yml` that is loaded after the custom config:

- `autosubmit expid -H local -d test -min`
- modify `minimal.yml`:

```yaml
CONFIG:
  # Current version of Autosubmit.
  AUTOSUBMIT_VERSION: "4.0.87"
  # Total number of jobs in the workflow.
  TOTALJOBS: 20
  # Maximum number of jobs permitted in the waiting status.
  MAXWAITINGJOBS: 20
DEFAULT:
  # Job experiment ID.
  EXPID: "a004"
  # Default HPC platform name.
  HPCARCH: "local"
  #hint: use %PROJDIR% to point to the project folder (where the project is cloned)
  # Custom configuration location.
  CUSTOM_CONFIG: "%PROJDIR%/conf/bootstrap/include.yml"
PROJECT:
  # Type of the project.
  PROJECT_TYPE: local
  # Folder to hold the project sources.
  PROJECT_DESTINATION: local_project
LOCAL:
  PROJECT_PATH: /tmp/proj
EXPERIMENT:
  NUMCHUNKS: 1
  CHUNKSIZE: 1
  CHUNKSIZEUNIT: day
  DATELIST: '19000101'
  MEMBERS: 'f0'
  CALENDAR: standard
JOBS:
  A:
    FILE: a.sh
    PLATFORM: local
    RUNNING: once
PLATFORMS:
  LOCAL:
    TYPE: ps
    HOST: localhost
    USER: kinow
    SCRATCH_DIR: /tmp/
```

- create `/tmp/proj/a.sh`

```bash
echo "%CURRENT_USER%"
```

- create `/tmp/proj/conf/bootstrap/include.yml`:

```yaml
DEFAULT:
  CUSTOM_CONFIG:
    PRE:
      - '~/platforms.yml'
```

- create `~/platforms.yml`:

```yaml
PLATFORMS:
  LOCAL:
    TYPE: ps
    HOST: localhost2
    USER: kinow2
    SCRATCH_DIR: /tmp/2/
  LOCAL2:
    TYPE: ps
    HOST: localhost2
    USER: kinow2
    SCRATCH_DIR: /tmp/2/
```

- run `autosubmit inspect <EXPID>`
- you should get the user "kinow" replacing the placeholder variable
- modify the job A to have `PLATFORM: local2` and now it should replace the placeholder by 'kinow2' 

I believe the order of configuration loading is minimal.yml, until it finds the custom config. Then loads the custom config and its pre and post recursively. Then it comes back to the minimal.yml and to other files in <EXPID>/conf, where a platform might overwrite what you had in your custom config (in your %PROJDIR%/conf/...`).

I fixed it in my repro test by moving platform.yml to my %PROJDIR%/conf as in the climatedt workflow configuration.
