### ISSUE TITLE
A local project is created, with --git_repo, --git_as_conf and --git_branch activated

### ISSUE THREAD

**Issue by kinow** [BSC-ES/autosubmit#1063]
In GitLab by @ainagaya on Jun 20, 2023, 16:48

Hello @dbeltrankyl and @kinow,

### Autosubmit Version

4.0.0b20

### Expid affected(If applicable)

a05j, but happened before in other experiments.

### Summary

I created the experiment following the Readme [here](https://earth.bsc.es/gitlab/digital-twins/de_340/workflow):

```
autosubmit expid \
  --description "A useful description" \
  --HPC <TYPE_YOUR_PLATFORM_HERE> \
  --minimal_configuration \
  --git_as_conf conf/bootstrap/ \
  --git_repo https://earth.bsc.es/gitlab/digital-twins/de_340/workflow \
  --git_branch main
```

But in the `minimal.yml` file I got this:

```
project:
  # Type of the project.
  PROJECT_TYPE: local
  # Folder to hold the project sources.
  PROJECT_DESTINATION: local_project
local:
  PROJECT_PATH: "https://earth.bsc.es/gitlab/digital-twins/de_340/workflow"
```

I think that this was not happening a couple of weeks ago... It also happened to @Lerriola . FYI @franra9 @rohanali1798 

### Steps to reproduce

Create an experiment in the VM following the Readme.

Thanks !!!

()

**Comment by kinow** [comment]
@dbeltrankyl , @ainagaya I just tested this on `master`, 

```
autosubmit expid \
  --description "A useful description" \
  --HPC local \
  --minimal_configuration \
  --git_as_conf conf/bootstrap/ \
  --git_repo https://earth.bsc.es/gitlab/digital-twins/de_340/workflow \
  --git_branch main
```

and got a `minimal.yml` with this:

```yaml
CONFIG:
  # Current version of Autosubmit.
  AUTOSUBMIT_VERSION: "4.0.0b"
  # Total number of jobs in the workflow.
  TOTALJOBS: 20
  # Maximum number of jobs permitted in the waiting status.
  MAXWAITINGJOBS: 20
DEFAULT:
  # Job experiment ID.
  EXPID: "a00d"
  # Default HPC platform name.
  HPCARCH: "local"
  #hint: use %PROJDIR% to point to the project folder (where the project is cloned)
  # Custom configuration location.
  CUSTOM_CONFIG: "%PROJDIR%/conf/bootstrap/"
PROJECT:
  # Type of the project.
  PROJECT_TYPE: git
  # Folder to hold the project sources.
  PROJECT_DESTINATION: git_project
GIT:
  PROJECT_ORIGIN: "https://earth.bsc.es/gitlab/digital-twins/de_340/workflow"
  PROJECT_BRANCH: "main"
  PROJECT_COMMIT: ''
  PROJECT_SUBMODULES: ''
  FETCH_SINGLE_BRANCH: true
```

So it might be an issue with the tag deployed in the VM.
