### ISSUE TITLE
[ DestinE ] Split syntax for large amount of splits

### ISSUE THREAD

**Issue by kinow** [BSC-ES/autosubmit#1067]
In GitLab by @dbeltrankyl on Jun 29, 2023, 08:08

Extend the https://earth.bsc.es/gitlab/es/autosubmit/-/issues/1023 usage

The idea is to make the life easier when there are a big number of splits and the dependencies are not consecutive 

* [x] Extend the 0:N notation with [start:end:step]

To do after #1025

**Comment by kinow** [comment]
In GitLab by @dbeltrankyl on Jul 6, 2023, 09:04

Added in DestinE-start-condtions, now the user can put a step 

```
    DEPENDENCIES:
     SIM-1:
        STATUS: "FAILED"
        FROM_STEP: "30"
        SPLITS_FROM:
          '[0:10:2],[10:20:2]':
            STATUS: "RUNNING"
            SPLITS_TO: "1,2"
          '2':
            STATUS: "QUEUING"
            SPLITS_TO: '[2:20:1]'
```

**Comment by kinow** [comment]
In GitLab by @dbeltrankyl on Jul 20, 2023, 09:33

marked the checklist item **Extend the 0:N notation with 0:N;2(jump)** as completed

**Comment by kinow** [comment]
In GitLab by @dbeltrankyl on Jul 20, 2023, 09:38

In merge review, 

Added 1-to-1 nomenclature

```yaml
JOBS:
  TEST:
   SPLITS: 10
    DEPENDENCIES:
     SIM:
        STATUS: "FAILED"
        FROM_STEP: "30"
        SPLITS_FROM:
          '[1:10]':
            STATUS: "QUEUING"
            SPLITS_TO: '[1:5]*,[6-10]
```

This will be translated to:

* TEST.SPLIT = 1 depends on SIM.SPLITS = 1,6,7,8,9,10 
* TEST.SPLIT = 2 depends on SIM.SPLITS = 2,6,7,8,9,10 
...
* TEST.SPLIT = 6 depends on SIM.SPLITS = 6,7,8,9,10
...
* TEST.SPLIT = 10 depends on SIM.SPLITS = 6,7,8,9,10
