### ISSUE TITLE
[CRITICAL] There are issues that occurred during the templates generation

### ISSUE THREAD

**Issue by kinow** [BSC-ES/autosubmit#1071]
In GitLab by @orioltinto on Jun 29, 2023, 17:17

Hello @dbeltrankyl and @kinow,

### Autosubmit Version

4.0.79

### Summary

Cannot use autosubmit variable for chunksize and numchunks.

### Steps to reproduce

`autosubmit expid -min -d "debug"`

we add the following to the minimal.yaml:
```
settings:
  chunks: "1"


experiment:
  DATELIST: 20201001
  MEMBERS: "m1"
  CHUNKSIZEUNIT: hour
  CHUNKSIZE: 1
  NUMCHUNKS: "%settings.chunks%"
  CHUNKINI: 0
  CALENDAR: standard

jobs:
  dummy:
    file: dummy.sh

platforms:
  dummy:
    hostname: dummy

```

we can create the experiment

`autosubmit create aXXX`

and if we do `autosubmit run aXXX` or `autosubmit inspect aXXX` the error is triggered.

### What is the current bug behavior?

```log
[ERROR] Trace: expected string or bytes-like object
 [CRITICAL] There are issues that occurred during the templates generation, please check that job parameters are well set and the template path exists. [eCode=7014]

```

### What is the expected correct behavior?

I expect to be able to use autosubmit variables in expdef as well.
It looks to work when it comes to defining the members. For example, this works:

```yaml
settings:
        members: "5"


experiment:
  MEMBERS: "m[1-%settings.members%]"

```

()CR

**Comment by kinow** [comment]
In GitLab by @dbeltrankyl on Jun 30, 2023, 10:33

Hello @orioltinto , 

Sorry for the delay, 

Could you try using v4.0.80?

**Comment by kinow** [comment]
In GitLab by @orioltinto on Jun 30, 2023, 10:41

Hi @dbeltrankyl,
same thing.

**Comment by kinow** [comment]
In GitLab by @dbeltrankyl on Jun 30, 2023, 11:00

Hello, 

```yaml

settings:
  chunks: "4"

DEFAULT: # ADDED
  EXPID: "a00p" # ADDED
  HPCARCH: "dummy" # ADDED
experiment:
  DATELIST: 20201001
  MEMBERS: "m1"
  CHUNKSIZEUNIT: hour
  CHUNKSIZE: 1
  NUMCHUNKS: "%settings.chunks%"
  CHUNKINI: 0
  CALENDAR: standard

jobs:
  dummy:
    file: dummy.sh
    RUNNING: "chunk" # added

platforms:
  dummy:
    type: "slurm" # "added" required 
    hostname: dummy

```

Unified conf:

experiment_data.yml located in metadata folder...
```yaml

CONFIG:
  AUTOSUBMIT_VERSION: 4.0.0b
DEFAULT:
  EXPID: a00p
  HPCARCH: dummy
EXPERIMENT:
  CALENDAR: standard
  CHUNKINI: 0
  CHUNKSIZE: 1
  CHUNKSIZEUNIT: hour
  DATELIST: 20201001
  MEMBERS: m1
  NUMCHUNKS: 4
JOBS:
  DUMMY:
    ADDITIONAL_FILES: []
    DEPENDENCIES: {}
    FILE: dummy.sh
    RUNNING: chunk
PLATFORMS:
  DUMMY:
    HOSTNAME: dummy
    TYPE: slurm
PROJDIR: /home/dbeltran/new_autosubmit/a00p/proj/project_files
ROOTDIR: /home/dbeltran/new_autosubmit/a00p
SETTINGS:
  CHUNKS: '4'
STORAGE: {}

```

This works for me, as you can see in the final unified conf..

Maybe the issue is in other configuration files that you have that I can't replicate
