### ISSUE TITLE
Reservation key is not passed to the scripts

### ISSUE THREAD

**Issue by kinow** [BSC-ES/autosubmit#1074]
In GitLab by @ainagaya on Jul 6, 2023, 13:30

Hello @dbeltrankyl and @kinow,

### Autosubmit Version

4.0.0b

### Expid affected(If applicable)

Tried with a009 in the VM (vainilla workflow), and a06v.

### Summary

I was trying to use the `RESERVATION` key. I tried both in Lumi and MN4:

```
PLATFORMS:
   LUMI:
      RESERVATION: "secret-name-to-skip-queues"
      PARTITION: "standard"
      TYPE: slurm

```

And in both cases the `--reservation="secret-name-to-skip-queues"` does not appear in the `.cmd` files. I put it in the custom directives, but it might be useful to have this key, and also it's quite easy to make mistakes with the custom directives key since it might be overwritten in another place unintentionally (trying to use completely different custom directives). As you said it might be easy to solve it so I can try to do it myself with your guidance! 

Thanks,

PD: maybe we could also have a key to exclude nodes. For Lumi especially.

()
