### ISSUE TITLE
DELETE_WHEN_EDGELESS job parameter not processed

### ISSUE THREAD

**Issue by kinow** [BSC-ES/autosubmit#1090]
In GitLab by @abaer-kit on Jul 17, 2023, 16:43

Hello @dbeltrankyl and @kinow,

### Autosubmit Version

v4.0.80

### Summary

A job without dependencies (neither providing nor receiving) is always in the workflow and thus executed.
However, following the [changelog](https://autosubmit.readthedocs.io/en/master/troubleshooting/changelog.html#changelog), I suspect that these are the edgeless that jobs should be deleted by default.
Furthermore, the parameter `DELETE_WHEN_EDGELESS` is evaluated by `autosubmit create` but does have no influence on this.

### Steps to reproduce

1. Create a dummy experiment
```
autosubmit expid -dm -d "Test for DELETE_WHEN_EDGELESS."
```
2. Add a new job to the jobs definition file:
```
JOBS:
  ANOTHER_JOB:
    FILE: INI.sh
    RUNNING: once
    WALLCLOCK: 00:05
    DELETE_WHEN_EDGELESS: True
```
3. Create the experiment
```
autosubmit create <expid>
```

### What is the current bug behavior?

The job is included in the workflow without any dependencies to the "main" workflow.

### What is the expected correct behavior?

I suspect that this is an edgeless job that should be deleted, i.e. neither included in the plot nor executed on experiment run.

### Relevant logs and/or screenshots(if applicable)

[20230717_163445_create.log](https://earth.bsc.es/gitlab/es/autosubmit/uploads/09cd7f31079e0279c66b0118520104f1/20230717_163445_create.log)

**Comment by kinow** [comment]
In GitLab by @dbeltrankyl on Jul 18, 2023, 08:52

Hello, 

Maybe it is misleading. This parameter only affects jobs that have some dependency added and then removed by using the task-to-task dependencies. Therefore, it has no effect when the job initially, hadn't a dependency

**Comment by kinow** [comment]
In GitLab by @abaer-kit on Jul 18, 2023, 09:04

Ok, I see. With task-to-task dependencies you mean e.g. chunks 1 to chunk 5 are running and a task that would depend only on chunk 6 (which never runs) is then deleted?

**Comment by kinow** [comment]
In GitLab by @dbeltrankyl on Jul 18, 2023, 09:08

quick example,

```yaml
chunks: 6
JOBS:
  JOB_A:
    running: chunk
    ...
  JOB_B:
    dependencies: 
     JOB_A:
       chunks_from: 
         [4:6]:
           chunks_to: none
           dates_to: none
           members_to: none
           splits_to: none
```

What will happen there is that. the JOB_B chunks 4,5,6 will disappear from the workflow as they don't have any other dependency, and 1-3 will run as normal
