### ISSUE TITLE
Fine-tune wrappers

### ISSUE THREAD

**Issue by kinow** [BSC-ES/autosubmit#1095]
In GitLab by @dbeltrankyl on Jul 27, 2023, 08:59

This issue is a follow-up of https://earth.bsc.es/gitlab/es/autosubmit/-/issues/1092#note_224686 

The idea is to add min/max wrapped by section. 

Per example, 

```yaml
WRAPPERS:
  Wrapper:
    JOBS_IN_WRAPPER: SIM&DA&OTHER
    MIN_WRAPPED: 2:2:2
    MAX_WRAPPED: 6:2:4
    ...
```
