### ISSUE TITLE
Booleans and strings transformations in the templates

### ISSUE THREAD

**Issue by kinow** [BSC-ES/autosubmit#1109]
In GitLab by @ainagaya on Aug 11, 2023, 09:25

Hello @dbeltrankyl and @kinow,

### Autosubmit Version

v4.0.0b 

### Expid affected(If applicable)

`a07q` (development experiment of IFS-Nemo)

### Which task has issues? Where is the log(If applicable)

* **Full_name**: fort_20200120_fc0_INI

* **Log_Path:** /appl/AS/AUTOSUBMIT_DATA/a07q/tmp/fort_20200120_fc0_INI

### Summary

I'm using a namelist as a template. This is snipped of it (https://earth.bsc.es/gitlab/digital-twins/de_340/workflow/-/blob/feature/mod-namelists/templates/namelists/fort.4 for more):

```
&NAMTRANS
LUSEFLT=%NAMTRANS.LUSEFLT%,
LFFTW=%NAMTRANS.LFFTW%,
LUSERPNM=%NAMTRANS.LUSERPNM%,
LKEEPRPNM=%NAMTRANS.LKEEPRPNM%,
/
&NAMPPC
NRSACCFRQ=%NAMPPC.NRSACCFRQ%,
/
&NAMIOS
CFRCF=%NAMIOS.CFRCF%,
CIOSPRF=%NAMIOS.CIOSPRF%,
/
&NAMGRIB
NLOCGRB=%NAMGRIB.NLOCGRB%,
NSTREAM=%NAMGRIB.NSTREAM%,
NWINOFF=%NAMGRIB.NWINOFF%,
CFCLASS=%NAMGRIB.CFCLASS%,
NCYCLE=%NAMGRIB.NCYCLE%,
/
&NAMCVER
LVERTFE=%NAMCVER.LVERTFE%,
NVSCH=%NAMCVER.NVSCH%,
LVFE_GWMPA=%NAMCVER.LVFE_GWMPA%,
LVFE_GW=%NAMCVER.LVFE_GW%,
LVFE_Z_TERM=%NAMCVER.LVFE_Z_TERM%,
LVFE_X_TERM=%NAMCVER.LVFE_X_TERM%,
LVFE_LAPL_BC=%NAMCVER.LVFE_LAPL_BC%,
LVFE_LAPL=%NAMCVER.LVFE_LAPL%,
NDLNPR=%NAMCVER.NDLNPR%,
```
And I wanted to fill it with the default values, so I have another file (https://earth.bsc.es/gitlab/digital-twins/de_340/workflow/-/blob/feature/mod-namelists/lib/namelists/fort.4.yaml for more):

```
NAMTRANS:
        LUSEFLT: false
        LFFTW: true
        LUSERPNM: true
        LKEEPRPNM: true

NAMPPC:
        NRSACCFRQ: -1

NAMIOS:
        CFRCF: "../rcf"
        CIOSPRF: "../srf"

NAMGRIB:
        NLOCGRB: 36
        NSTREAM: 1247
        NWINOFF: 9
        CFCLASS: "rd"
        NCYCLE: 154

NAMCVER:
        LVERTFE: true
        NVSCH: 3
        LVFE_GWMPA: true
        LVFE_GW: false
        LVFE_Z_TERM: false
        LVFE_X_TERM: false
        LVFE_LAPL_BC: true
        LVFE_LAPL: true
        NDLNPR: 0

``` 

As you see, there are some booleans in lowercase, and some strings between "". I thought that they would be exactly like this in the parsed template, but it was not (`/appl/AS/AUTOSUBMIT_DATA/a07q/tmp/fort_20200120_fc0_INI`):

```
&NAMTRANS
LUSEFLT=False,
LFFTW=True,
LUSERPNM=True,
LKEEPRPNM=True,
/
&NAMPPC
NRSACCFRQ=-1,
/
&NAMIOS
CFRCF=../rcf,
CIOSPRF=../srf,
/
&NAMGRIB
NLOCGRB=36,
NSTREAM=1247,
NWINOFF=9,
CFCLASS=rd,
NCYCLE=154,
/
&NAMCVER
LVERTFE=True,
NVSCH=3,
LVFE_GWMPA=True,
LVFE_GW=False,
LVFE_Z_TERM=False,
LVFE_X_TERM=False,
LVFE_LAPL_BC=True,
LVFE_LAPL=True,
NDLNPR=0,
```

In my case I think that the booleans are not gonna give problems, and for the strings, I'm adding `""` in the variables that need it (that's how I have it right now in the experiment and the repository), and I can force the type of the variable as you suggested yesterday. But just if you want to take it into account. 

### Any other relevant information(if applicable)

()
