### ISSUE TITLE
Rename CURRENT_PROJDIR for CURRENT_SCRATCH_PROJDIR and PROJDIR for CURRENT_PROJDIR

### ISSUE THREAD

**Issue by kinow** [BSC-ES/autosubmit#1155]
In GitLab by @dbeltrankyl on Nov 16, 2023, 12:05

There are shallow variables names in the parameters exported, and the idea is to fix that. 

Actual:

```
PARAMETERS['CURRENT_PROJDIR'] == SCRATCH_PROJ_DIR
PARAMETERS['PROJDIR'] == CURRENT_PROJ_DIR
```

Should be:

```
PARAMETERS['CURRENT_PROJDIR'] == CURRENT_PROJ_DIR
PARAMETERS['CURRENT_SCRATCH_PROJ_DIR'] == SCRATCH_PROJ_DIR
```

FYI: @ainagaya

**Comment by kinow** [comment]
In GitLab by @ainagaya on Nov 17, 2023, 10:39

Hi Dani! 

One thing: right now the `PROJDIR` takes the path of the proj from the local machine (in my case, `/appl/AS/AUTOSUBMIT_DATA/a07q/proj/git_project/`). What I want is a variable to load the "proj_dir" the same way as the "scratch_dir". In my `platforms.yml` I have (under `PLATFORMS`):

```
  lumi:
    TYPE: slurm
    HOST: lumi-cluster
    PROJECT: project_465000454
    PROJ_DIR: /projappl/project_465000454
    USER: <to-be-overloaded-in-user-conf>
    QUEUE: ""
    SCRATCH_DIR: /scratch
    ADD_PROJECT_TO_HOST: False
    TEMP_DIR: ''
    BUDGET: "project_465000454"
    EXECUTABLE: "/bin/bash --login"
```

And I want a variable equivalent to `PLATFORMS.LUMI.PROJ_DIR` but platform independent. I mean, is not the proj directory inside the experiment, but the general project directory of the platform. I don't know it that is possible (or if it's for another issue). 

Thanks!!
