### ISSUE TITLE
[DestinE] Add a new filter keyword (previous//next)

### ISSUE THREAD

**Issue by kinow** [BSC-ES/autosubmit#1175]
In GitLab by @dbeltrankyl on Dec 4, 2023, 16:35

Hello @franra9 , @mcastril  fyi: @kinow 

I've added a new keyword for the filters named "previous" to the 4-0-XXX-branch. ( I'll update the lumi module )  

Right now it will only work for splits in the most simple way..

```yaml

  DN:
    FILE: "templates/dn.sh,conf/mother_request.yml"
    DEPENDENCIES:
      INI:
      DN:
        SPLITS_FROM:
          'all':
              SPLITS_TO: 'previous'
    RUNNING: chunk
    WALLCLOCK: '00:15'
    SPLITS: 50
    #(not all months!)

```

The idea is to extend its functionality to work for members, dates .. and even we can substitute the -1 // +1 by this at the chunk level? 

Also, right now, it will only contemplate the -1. -2,-3 etc is not contemplated. +1,+2 should be added as well as "next" 

So, for 4.1+ the idea is to make it work for all filters and admit previous2,previous3 ... next2,next3

The quick addition is for https://earth.bsc.es/gitlab/digital-twins/de_340/project_management/-/issues/520#note_245238 and only this simple addition is necessary
