### ISSUE TITLE
Include calendar information in Splits and change their number every month

### ISSUE THREAD

**Issue by kinow** [BSC-ES/autosubmit#1177]
In GitLab by @franra9 on Dec 5, 2023, 10:20

Hello @dbeltrankyl and @kinow,

### Autosubmit Version

4.0.103 (need for further development)

### Expid affected(If applicable)

a09s

### Which task has issues? Where is the log(If applicable)

-

### Summary

For Destination earth we need 2 things (maybe it is worth to split this issue in 2):

* The splits to have some kind of calendar information, in a similar way the chunks have %CHUNK_DATE% and similar.
* The jobs.yml to account for different number of splits per month. So far, it is hardcoded to 744 (31 days) but this changes every month. (see jobs.yml [here](https://earth.bsc.es/gitlab/digital-twins/de_340/workflow/-/blob/app-downstream/conf/jobs.yml)) 

(This potential issue was already detected [here](https://earth.bsc.es/gitlab/digital-twins/de_340/workflow/-/issues/56#note_238001) but I focused on other priorities)

### Steps to reproduce

- 

### What is the current bug behavior?

-

### What is the expected correct behavior?

-

### Relevant logs and/or screenshots(if applicable)

-

### Any other relevant information(if applicable)

cc @mcastril @ainagaya @Lerriola @fdoblasreyes 

()

**Comment by kinow** [comment]
In GitLab by @franra9 on Dec 5, 2023, 17:08

Similar problem arises with the splits that do not represent hours/days but have a temporal/ successive meaning that have different time origins. Let me give the example:

```
JOBS:
  (...)
  INI:
    FILE: templates/ini.sh
    PLATFORM: "%DEFAULT.HPCARCH%"
    DEPENDENCIES: REMOTE_SETUP
    RUNNING: member
    WALLCLOCK: '00:30'
  DN:
    FILE: "templates/dn.sh,conf/mother_request.yml"
    DEPENDENCIES: INI
    RUNNING: chunk
    WALLCLOCK: '00:15'
    PLATFORM: "%DEFAULT.HPCARCH%-login"
    SPLITS: 744 #(not all months!)
  OPA:
    FOR:
      NAME: "%RUN.OPA_NAMES%" #"%OPA_NAMES"
      SPLITS: "[31,31,31,31,31,31,31,31,31]" #"%OPA_SPLITS%"
      DEPENDENCIES:
        - DN:
            SPLITS_FROM: # From OPA
              "all":
                  SPLITS_TO: "[24:%JOBS.DN.SPLITS%]*\\24" #To DN
        - DN:
            SPLITS_FROM: # From OPA
              "all":
                  SPLITS_TO: "[1:%JOBS.DN.SPLITS%]*\\24"  # To DN
        - DN:
            SPLITS_FROM: # From OPA
              "all":
                  SPLITS_TO: "[1:%JOBS.DN.SPLITS%]*\\24"  # To DN
        - DN:
            SPLITS_FROM: # From OPA
              "all":
                  SPLITS_TO: "[1:%JOBS.DN.SPLITS%]*\\24"  # To DN
        - DN:
            SPLITS_FROM: # From OPA
              "all":
                  SPLITS_TO: "[1:%JOBS.DN.SPLITS%]*\\24"  # To DN
        - DN:
            SPLITS_FROM: # From OPA
              "all":
                  SPLITS_TO: "[1:%JOBS.DN.SPLITS%]*\\24" # To DN 
        - DN:
            SPLITS_FROM: # From OPA
              "all":
                  SPLITS_TO: "[1:%JOBS.DN.SPLITS%]*\\24" # To DN
        - DN:
            SPLITS_FROM: # From OPA
              "all":
                  SPLITS_TO: "[1:%JOBS.DN.SPLITS%]*\\24" # To DN
        - DN:
            SPLITS_FROM: # From OPA
              "all":
                  SPLITS_TO: "[1:%JOBS.DN.SPLITS%]*\\24" # To DN
    FILE: templates/opa.sh
    PLATFORM: "%DEFAULT.HPCARCH%"
    RUNNING: chunk
  APP:
    FOR:
      NAME: "%RUN.APP_NAMES%"
      SPLITS: "[31,31,31,31]" #%APP.SPLITS% <== issue here
      DEPENDENCIES:
        - OPA_10U_RAW_DAILY_NOON:
            SPLITS_FROM:
              'all':
                  SPLITS_TO: 'all' #"[1:%JOBS.DN.SPLITS%]*"
          (...)
        - OPA_2T_MEAN_DAILY:
            SPLITS_FROM:
              'all':
                  SPLITS_TO: 'all' #"[1:%JOBS.DN.SPLITS%]*"
          (...)  
        - OPA_SKT_MEAN_MONTHLY:
            SPLITS_FROM:
              'all':
                  SPLITS_TO: 'all' #"[1:%JOBS.DN.SPLITS%]*"    
        - OPA_2T_MIN_DAILY:
            SPLITS_FROM:
              'all':
                  SPLITS_TO: 'all' #"[1:%JOBS.DN.SPLITS%]*" 
    FILE: "templates/application.sh"
    DEPENDENCIES: OPA
    RUNNING: chunk
    WALLCLOCK: '00:05'
    PLATFORM: "%DEFAULT.HPCARCH%"
```

In this example `OPA` and `APP` run daily, so 31 stands for 31 days. This is an issue that is similar to the hourly-splits one, as at the end 31 can be derived as `744h/month /24h = 31 days`, `720h/month /24h = 30 days` and so on. 

In the case that we want to run the app in weeks, for example (mon-sun according to OPA) it will happen that the split 1 does not correspond to days 1-7 but maybe the week mon-sun corresponds to 3-9. That's why the splits if possible should bring information about the true calendar days.

**Comment by kinow** [comment]
In GitLab by @mcastril on Dec 11, 2023, 21:28

@dbeltrankyl how much effort do you think would be needed to implement this new type of splits ? These splits would introduce a sequence, in the same way as CHUNKS do, in opposition to a parallelization, as STARTDATES, MEMBERS or SPLITS do.

**Comment by kinow** [comment]
In GitLab by @dbeltrankyl on Dec 12, 2023, 09:43

Hello @mcastril ,


If I understood it correctly, instead of specify a determinate amount of splits, we need:

```
  JOBS:
   OPA:
    RUNNING: <whatever>
    CALENDAR: standard  
    SIZE: N
    SIZEUNIT: month/week/day

```

And underneath, autosubmit would translate this into N amount of splits? And these splits would have the same dependencies* behavior but instead of a number, they would be a date? ( that underneath would be the same number to simplify the code regarding the splits_to splits_from I guess ). 

Edit: So the only addition would be the export of the dates in the template, while all the rest remain the same?
