### ISSUE TITLE
[documentation] Jobs are renamed to uppercase, we need to document it and update our images

### ISSUE THREAD

**Issue by kinow** [BSC-ES/autosubmit#1178]
Found this while testing !395 

Testing the job frequency example, https://autosubmit.readthedocs.io/en/master/userguide/defining_workflows/index.html#job-frequency, I compared my plot with the docs plot, and noticed the difference.

I had copied the jobs from our docs:

```yaml
ini:
    FILE: ini.sh
    RUNNING: member

sim:
    FILE: sim.sh
    DEPENDENCIES: ini sim-1
    RUNNING: chunk

postprocess:
    FILE: postprocess.sh
    DEPENDENCIES: sim
    RUNNING: chunk
    FREQUENCY: 3

combine:
    FILE: combine.sh
    DEPENDENCIES: postprocess
    RUNNING: member
```

But in my plot the job names are all in upper case (that does not apply to expid or members, only job names).

![image](https://earth.bsc.es/gitlab/es/autosubmit/uploads/c9e504c92f0a20c0da968b4d66d6e53c/image.png)
