### ISSUE TITLE
[bug] Weak dependencies not working?

### ISSUE THREAD

**Issue by kinow** [BSC-ES/autosubmit#1205]
Hello @dbeltrankyl,

### Autosubmit Version

Tested

`master`
`v4.0.103`
`suaq

### Expid affected(If applicable)

NA

### Which task has issues? Where is the log(If applicable)

NA

### Summary

I created the example below following our documentation, https://autosubmit.readthedocs.io/en/master/userguide/defining_workflows/index.html#example-3-weak-dependencies

```yaml
JOBS:
  JOB1:
    FILE: ok.sh
    RUNNING: once
  JOB2:
    FILE: nok.sh
    RUNNING: once
    DEPENDENCIES: JOB1
  JOB3:
    FILE: ok.sh
    RUNNING: once
    DEPENDENCIES: JOB2?
```

I expected `JOB3` to be triggered but on `master` and 4.0.103 only `JOB2` is launched. In !395 's branch it crashes with an exception (will report it there).

### Steps to reproduce

Configure the experiment, `autosubmit create ` and `autosubmit run`. Then `autosubmit monitor` and `JOB3` is never executed.

![image](https://earth.bsc.es/gitlab/es/autosubmit/uploads/5fddeca3ae8eee6f7daa13612a45f66d/image.png)

### What is the current bug behavior?

![image](https://earth.bsc.es/gitlab/es/autosubmit/uploads/1d95b89bb3ad8cda5a4d788e7fdfafe8/image.png)

### What is the expected correct behavior?

JOB3 was supposed to be triggered as its dependency on `JOB2?` is weak/optional.

### Relevant logs and/or screenshots(if applicable)

```bash
Creating jobs...
Loading JobList
Adding dependencies...
Removing redundant dependencies...
Using existing valid structure.
Looking for edgeless jobs...
Checking scripts...
1 of 3 checked
2 of 3 checked
3 of 3 checked
Scripts OK
Autosubmit is running with v4.0.103
Checking the connection to all platforms in use
[local] Correct user privileges for host localhost
[local] Connection successful to host localhost


3 of 3 jobs remaining (13:40)
No jobs to check for platform local
a002_JOB1 submitted
Call from a002_JOB1 with status SUBMITTED


3 of 3 jobs remaining (13:40)
Checking 1 jobs for platform local
Job a002_JOB1 is COMPLETED
a002_JOB2 submitted
Call from a002_JOB2 with status SUBMITTED


2 of 3 jobs remaining (13:40)
Checking 1 jobs for platform local
[ERROR] Job a002_JOB2 completion check failed. There is no COMPLETED file[eCode=6009]
[ERROR] Job a002_JOB2 completion check failed. There is no COMPLETED file[eCode=6009]
No more jobs to run.
Some jobs have failed and reached maximum retrials
```

### Any other relevant information(if applicable)

()

**Comment by kinow** [comment]
created branch [`1205-bug-weak-dependencies-not-working`](/gitlab/es/autosubmit/-/compare/master...1205-bug-weak-dependencies-not-working) to address this issue

**Comment by kinow** [comment]
cc @igonzal-bsc , @franra9

**Comment by kinow** [comment]
Ideally, we should

i. fix this issue (if it is confirmed by @dbeltrankyl to be a bug), 
ii. improve the docs (the text doesn't match the graph, we can write it simpler I think)
iii. write tests (unit?) to prevent a regression and cover that part (given it might be used in important workflows in EDITO, BSC, ClimateDT)

**Comment by kinow** [comment]
In GitLab by @dbeltrankyl on Jan 12, 2024, 08:26

Hello @kinow and all,

This usage has been deprecated since the introduction of the start conditions, we should update the docs so it is not misleading.

https://autosubmit.readthedocs.io/en/master/userguide/defining_workflows/index.html#start-conditions

You should use the updated one that allows you to set failed but also the rest of status

```yaml

JOBS:
  JOB1:
    FILE: ok.sh
    RUNNING: once
  JOB2:
    FILE: nok.sh
    RUNNING: once
    DEPENDENCIES: JOB1
  JOB3:
    FILE: ok.sh
    RUNNING: once
    DEPENDENCIES: 
      JOB2:
        STATUS: "FAILED"

```
