### ISSUE TITLE
Differences in autosubmit create autosubmit 4.0.104 vs 4.1.0-beta-dev

### ISSUE THREAD

**Issue by kinow** [BSC-ES/autosubmit#1222]
In GitLab by @franra9 on Feb 2, 2024, 12:59

Hello @dbeltrankyl and @kinow,

### Autosubmit Version

v4.0.104 vs v4.1.0-beta-dev

### Expid affected(If applicable)

same graph created

### Summary
autosubmit create differs. (app jobs not created)

### Steps to reproduce

autosubmit create with the different modules loaded.

### What is the current bug behavior?

create differs 

### What is the expected correct behavior?

get the same graph for both
### Relevant logs and/or screenshots(if applicable)

![Screenshot_from_2024-02-02_12-52-32](https://my-gitlab-bucket.s3.amazonaws.com/902354155/8fd688d683fe9018fa6b9b09d71432cb16f35477192441206c7ff6bcca549b13/Screenshot_from_2024-02-02_12-52-32.png)!

[Screenshot_from_2024-02-02_12-57-19](https://my-gitlab-bucket.s3.amazonaws.com/902354155/8555a9e79d727c715bcbeb91aefdf292ae565f8b941573ea96a9db5ef95f6e8b/Screenshot_from_2024-02-02_12-57-19.png)

### Any other relevant information(if applicable)

You may be aware already of this, as I know it is not a "real" realease.

jobs.yml used:

<details><summary>jobs.yml</summary>

```yaml
JOBS:
  APP:
    DEPENDENCIES: null
    FILE: templates/application.sh,templates/only_lra.yaml
    FOR:
      DEPENDENCIES:
      - OPA_MHM_1:
          SPLITS_FROM:
            all:
              SPLITS_TO: '[1:%JOBS.DN.SPLITS%]*\\1'
        OPA_MHM_2:
          SPLITS_FROM:
            all:
              SPLITS_TO: '[1:%JOBS.DN.SPLITS%]*\\1'
      - OPA_URBAN_1:
          SPLITS_FROM:
            all:
              SPLITS_TO: '[1:%JOBS.DN.SPLITS%]*\\1'
      - OPA_AQUA_1:
          SPLITS_FROM:
            all:
              SPLITS_TO: '[1:%JOBS.DN.SPLITS%]*\\1'
      - OPA_WILDFIRES_FWI_1:
          SPLITS_FROM:
            all:
              SPLITS_TO: '[1:%JOBS.DN.SPLITS%]*\\1'
        OPA_WILDFIRES_FWI_2:
          SPLITS_FROM:
            all:
              SPLITS_TO: '[1:%JOBS.DN.SPLITS%]*\\1'
        OPA_WILDFIRES_FWI_3:
          SPLITS_FROM:
            all:
              SPLITS_TO: '[1:%JOBS.DN.SPLITS%]*\\1'
        OPA_WILDFIRES_FWI_4:
          SPLITS_FROM:
            all:
              SPLITS_TO: '[1:%JOBS.DN.SPLITS%]*\\1'
        OPA_WILDFIRES_FWI_5:
          SPLITS_FROM:
            all:
              SPLITS_TO: '[1:%JOBS.DN.SPLITS%]*\\1'
      NAME: '%RUN.APP_NAMES%'
      SPLITS: '[31, 31, 31, 31]'
    PLATFORM: '%DEFAULT.HPCARCH%'
    RUNNING: chunk
    WALLCLOCK: 00:05
  DN:
    DEPENDENCIES:
      DN:
        SPLITS_FROM:
          all:
            SPLITS_TO: previous
      SIM:
        STATUS: RUNNING
    FILE: templates/dn.sh,conf/mother_request.yml
    PLATFORM: '%DEFAULT.HPCARCH%-login'
    RUNNING: chunk
    SPLITS: 31
    WALLCLOCK: 00:15
  INI:
    DEPENDENCIES: REMOTE_SETUP
    FILE: templates/ini.sh
    PLATFORM: '%DEFAULT.HPCARCH%-login'
    RUNNING: member
    WALLCLOCK: 00:30
  LOCAL_SETUP:
    FILE: templates/local_setup.sh
    PLATFORM: LOCAL
    RUNNING: once
  OPA:
    DEPENDENCIES: null
    FILE: templates/opa.sh
    FOR:
      DEPENDENCIES:
      - DN:
          SPLITS_FROM:
            all:
              SPLITS_TO: "[1:%JOBS.DN.SPLITS%]*\\1"
      - DN:
          SPLITS_FROM:
            all:
              SPLITS_TO: "[1:%JOBS.DN.SPLITS%]*\\1"
      - DN:
          SPLITS_FROM:
            all:
              SPLITS_TO: "[1:%JOBS.DN.SPLITS%]*\\1"
      - DN:
          SPLITS_FROM:
            all:
              SPLITS_TO: "[1:%JOBS.DN.SPLITS%]*\\1"
      - DN:
          SPLITS_FROM:
            all:
              SPLITS_TO: "[1:%JOBS.DN.SPLITS%]*\\1"
      - DN:
          SPLITS_FROM:
            all:
              SPLITS_TO: "[1:%JOBS.DN.SPLITS%]*\\1"
      - DN:
          SPLITS_FROM:
            all:
              SPLITS_TO: "[1:%JOBS.DN.SPLITS%]*\\1"
      - DN:
          SPLITS_FROM:
            all:
              SPLITS_TO: "[1:%JOBS.DN.SPLITS%]*\\1"
      - DN:
          SPLITS_FROM:
            all:
              SPLITS_TO: "[1:%JOBS.DN.SPLITS%]*\\1"
      NAME: '%RUN.OPA_NAMES%'
      SPLITS: '[31, 31, 31, 31, 31, 31, 31, 31, 31]'
    PLATFORM: '%DEFAULT.HPCARCH%'
    RUNNING: chunk
  REMOTE_SETUP:
    DEPENDENCIES: SYNCHRONIZE
    FILE: templates/remote_setup.sh,templates/fdb/confignative.yaml,templates/fdb/configregularll.yaml,templates/fdb/confighealpix.yaml
    PLATFORM: '%DEFAULT.HPCARCH%-login'
    RUNNING: once
    WALLCLOCK: 02:00
  SIM:
    DEPENDENCIES: INI SIM-1
    FILE: <to-be-replaced-by-user-conf>
    PLATFORM: '%DEFAULT.HPCARCH%'
    WALLCLOCK: 00:30
    running: chunk
  SYNCHRONIZE:
    DEPENDENCIES: LOCAL_SETUP
    FILE: templates/synchronize.sh
    PLATFORM: LOCAL
    RUNNING: once
RUN:
  APP_NAMES:
  - MHM
  - URBAN
  - AQUA
  - WILDFIRES_FWI
  OPA_NAMES:
  - mhm_1
  - mhm_2
  - urban_1
  - aqua_1
  - wildfires_fwi_1
  - wildfires_fwi_2
  - wildfires_fwi_3
  - wildfires_fwi_4
  - wildfires_fwi_5

```
</details>

()
