### ISSUE TITLE
Reservation key doesn't apply in wrappers

### ISSUE THREAD

**Issue by kinow** [BSC-ES/autosubmit#1223]
In GitLab by @ainagaya on Feb 2, 2024, 16:56

( This is a template for bug reports. Please fill in the relevant information and delete the rest. )

Hello @dbeltrankyl and @kinow,

### Autosubmit Version

4.0.104

### Expid affected(If applicable)

-

### Which task has issues? Where is the log(If applicable)

Wrappers

### Summary

If the reservation key is used and wrappers are applied, the reservation key is not in the ASThreads files, so it doesn't apply (it is in the SIMs).

### Steps to reproduce

Create an experiement, add wrappers and reservation to the platform. 

### Any other relevant information(if applicable)

I know it doesn't make a lot of sense to use a vertical wrapper if you have a reservation, but it confused us a bit (@ingwag )

()

**Comment by kinow** [comment]
In GitLab by @dbeltrankyl on Feb 5, 2024, 08:55

Thanks @ainagaya ,

I was not aware. I think nobody is using wrappers with reservation keys ( as there are no queue times)

You can use custom_directives in the wrapper section to bypass that issue, but we will add that the parameter is inherited from the jobs as in the other cases.

**Comment by kinow** [comment]
In GitLab by @ainagaya on May 22, 2024, 11:53

Hi @dbeltrankyl , its a very "edgy" case, but today I was trying to submit jobs in a reservation with a wrapper with the following config:

```
JOBS:
  TRANSFER:
    FILE: templates/transfer.sh
    PLATFORM: lumi
    DEPENDENCIES: REMOTE_SETUP
    RUNNING: chunk
    WALLCLOCK: '04:00'
    NODES: 1
    PROCESSORS: 1
    TASKS: 1
    THREADS: 1
    

WRAPPERS:
  WRAPPER_0:
    JOBS_IN_WRAPPER: TRANSFER
    METHOD: ASTHREAD
    TYPE: horizontal
    POLICY: mixed
    RETRIALS: 5
    MIN_WRAPPED: 1
    MAX_WRAPPED: 16
    CUSTOM_DIRECTIVES: "[--reservation DT_transfer]"  <-----I added this because JOB.RESERVATION was not being applied
```

What you posted above is working so it's completely fine but just to have an example of usage.

cc @Lerriola
