### ISSUE TITLE
Autosubmit v4 interoperability with MN5

### ISSUE THREAD

**Issue by kinow** [BSC-ES/autosubmit#1246]
Following @dbeltrankyl's suggestion from today's meeting, this is a placeholder to collect issues related to MN5 and AS.

**Comment by kinow** [comment]
marked this issue as related to #1241

**Comment by kinow** [comment]
In GitLab by @dbeltrankyl on Mar 13, 2024, 10:31

I looked at the documentation:

Logins with internet ( same as mn0.bsc.es ) , VPN required

* glogin4.bsc.es 
* alogin4.bsc.es 

https://www.bsc.es/supportkc/docs/MareNostrum5/slurm#standard-queues
Queue list ( or using bsc_queues) 

Filesystems can be found at https://www.bsc.es/supportkc/docs/MareNostrum5/storage#gpfs-filesystems

Fairshare can be viewed with `sshare -la`

-----
https://www.bsc.es/supportkc/docs/MareNostrum5/new_essentials#slurm-changes-with-performance-implications

It seems that --cpu-per-tasks will be ignored ( THREADS ) ( templates issue, can't do anything in AS ) 

----
Submission

Not sure about the implications of this  

https://www.bsc.es/supportkc/docs/MareNostrum5/new_essentials#submitting-jobs

I found an example in https://www.bsc.es/supportkc/docs/MareNostrum5/slurm

`sbatch job.sh -A bsc21 -q acc_bsccase`

But I don't know if we can have this -A inside the cmd file as we do now. 

Our current submission is with 

`sbatch --no-requeue -D /gpfs/scratch/bsc32/bsc32070/a03b/LOG_a03b /gpfs/scratch/bsc32/bsc32070/a03b/LOG_a03b/a03b_20000101_fc0_1_SIM.cmd`

* [x] test submission

Edit: Success after mkdir the user folder

-----

https://www.bsc.es/supportkc/docs/MareNostrum5/slurm#interactive-jobs
* [ ] test x11 ( low prio)
-----

https://www.bsc.es/supportkc/docs/MareNostrum5/slurm#job-examples
* [ ] Add GPU directives ( ACC,alogin ) 
-----

https://www.bsc.es/supportkc/docs/MareNostrum5/slurm#job-state-codes
* [x] Check job state codes ( I guess they're the same )

Edit: Completing was missing, added in mn5-additions branch

-----

**Comment by kinow** [comment]
In GitLab by @dbeltrankyl on Mar 13, 2024, 11:01

Ran successfully using 4.1.2 @mcastril cc

```yaml
DEFAULT:
  # Job experiment ID.
  EXPID: "a03k"
  # Default HPC platform name.
  HPCARCH: "marenostrum5"

JOBS:
  SIM_gpp:
    FILE: SIM.sh
    RUNNING: once
    WALLCLOCK: 00:05
  SIM_acc:
    FILE: SIM.sh
    RUNNING: once
    WALLCLOCK: 00:05
    PLATFORM: MARENOSTRUM5ACC
...

  MARENOSTRUM5:
    TYPE: slurm
    HOST: glogin1.bsc.es
    PROJECT: bsc32
    USER: bsc032070
    QUEUE: gp_debug
    SCRATCH_DIR: /gpfs/scratch
    ADD_PROJECT_TO_HOST: false
    MAX_WALLCLOCK: 02:00
    MAX_PROCESSORS: 3584
    TEMP_DIR: ''
  MARENOSTRUM5ACC:
    TYPE: slurm
    HOST: alogin1.bsc.es
    PROJECT: bsc32
    USER: bsc032070
    QUEUE: acc_debug
    SCRATCH_DIR: /gpfs/scratch
    ADD_PROJECT_TO_HOST: false
    MAX_WALLCLOCK: 02:00
    MAX_PROCESSORS: 640
    TEMP_DIR: ''
```

`autosubmit run a03k `

Fails in the connectivity check

ssh bsc032070@glogin1.bsc.es

mkdir /gpfs/scratch/bsc32/bsc032070 

`autosubmit run a03k `

```bash
Run successful
```

So we don't need the -A or the -q in the sbatch submission.
