### ISSUE TITLE
Autosubmit 4 interoperability with Fugaku

### ISSUE THREAD

**Issue by kinow** [BSC-ES/autosubmit#1275]
In GitLab by @dbeltrankyl on Apr 18, 2024, 08:51

This is the issue to comment on regarding utilizing Autosubmit 4 and Fugaku.

Autosubmit should already support Fugaku( pjm scheduler was added in #921 ) as we did some tests with CTE-ARM , but I have not performed tests with the Fugaku itself as I didn't have access until yesterday. 

I am tagging all persons involved in the project ( I think, (https://earth.bsc.es/gitlab/ces/hanami/-/issues/1#note_271945 ) ). In case there are issues or something to discuss 

FYI: @ macosta , @mcastril , @Lerriola , @eferre1 , @kellekai , @manuel-g-castro , @malerany , @ghosh97

**Comment by kinow** [comment]
In GitLab by @dbeltrankyl on Apr 18, 2024, 11:46

Overview: https://www.fugaku.r-ccs.riken.jp/en/fugaku_information

"Queues limits": https://www.fugaku.r-ccs.riken.jp/en/resource_group_config

our project: ra000012 ( /home/ra000012/ , is there scratch? or the scratch is /home/ra000012/data? )

Issues: 

I don't have a folder with my name, and I don't have permission to create a folder under /home/ra000012

```bash
login4$ pwd
/home/ra000012
login4$ mkdir u12690
mkdir: cannot create directory ‘u12690’: Permission denied
```

However, I can create a folder under /home/ra000012/data.

```yaml

JOBS:
  test:
    FILE: SIM.sh
    RUNNING: once
    WALLCLOCK: 00:05
PLATFORMS:
  FUGAKU:
    TYPE: PJM
    HOST: Fugaku
    PROJECT: ra000012
    USER: u12690
    QUEUE: small
    SCRATCH_PROJECT_DIR: . # to use data folder and avoid to create ra000012
    SCRATCH_DIR: /home/ra000012/data
    ADD_PROJECT_TO_HOST: false
    MAX_WALLCLOCK: 72:00
    TEMP_DIR: ''

```
/home/ra000012/data/u12690/a03r

(minor issue ) From docs: 

> "You can check size of each resource group (RSCGRP_SIZE) by executing pjstat command with --rsc option." 

```bash
login4$ pjstat --rsc

RSCUNIT                                  RSCUNIT_SIZE  RSCGRP                                   RSCGRP_SIZE  
```

-----------------------
Autosubmit:

- Connection ok
- Submission ok~ ( just noticed that the log is reporting the submission twice, but only one submission is made )
- job status check failing: 

``` pjstat Invalid option argument: --filter jid=31920291,```

In cte-arm this was available... working on a fix

- Logs and Stats are being retrieved.

**Comment by kinow** [comment]
In GitLab by @dbeltrankyl on Apr 18, 2024, 11:53

After the fix the checker is behaving wrongly 

```
[ERROR] check_job() The job id (31920374) status is -2.
[WARNING] Job a03r_TEST is UNKNOWN. Checking completed files to confirm the failure...[eCode=3000]
Job a03r_TEST is COMPLETED
```

Seems that AS doesn't receive any output from the pjstat, but it is set as completed later because the COMPLETED file is found

**Comment by kinow** [comment]
In GitLab by @dbeltrankyl on Apr 18, 2024, 14:51

Autosubmit basic functionality working now fine, 

Question: Do we need het jobs in Fugaku? Het jobs are only implemented in SLURM

I'm checking the wrappers as the code has been changed since last year. How much priority we will have for the jobs? Just to see how prioritary is it in case that it doesn't work as in slurm

**Comment by kinow** [comment]
In GitLab by @dbeltrankyl on Apr 18, 2024, 14:56

PJM was implemented also in 3.15, so yes I'll port the changes the code should be the same more or less

**Comment by kinow** [comment]
In GitLab by @dbeltrankyl on Apr 18, 2024, 14:57

The only issue about 3.15 would be the HET jobs if we need to have them

**Comment by kinow** [comment]
In GitLab by @dbeltrankyl on Apr 23, 2024, 16:44

Tomorrow, I'll update v4.1.5 which will have the changes to all features working in PJM except for het jobs

**Comment by kinow** [comment]
In GitLab by @dbeltrankyl on Apr 30, 2024, 16:58

4.1.5 available in hubs and lumi vm

**Comment by kinow** [comment]
In GitLab by @Lerriola on May 13, 2024, 10:16

Hi @dbeltrankyl last week I configured my creds. to be able to access **Fugaku** (I'm using `fugaku-cluster` as host) from the hubs and from the climateDT-VM.

I then tested a simple workflow (expid `a1b4`) to test the interoperability and  run something on fugaku, I think you briefly reported it above but I'll go over the minor issue I found:

- During the run command, while AS checks connectivity, it constructs a root_path: 

```
Check the parameters that build the root_path are correct:{scratch_dir/project/user} = {/home/ra000012/data/ra000012/u12690}`
```
- AS forces you to create the path `/home/ra000012/data/ra000012/u12690`. This complicates stuff a bit because the Fugaku folder structure is a bit different, and doesn't follow the `scratch_dir/project/user` structure.

**Comment by kinow** [comment]
In GitLab by @dbeltrankyl on May 13, 2024, 10:17

> 
```yaml
  FUGAKU:
    TYPE: PJM
    HOST: Fugaku
    PROJECT: ra000012
    USER: u12690
    QUEUE: small
    SCRATCH_PROJECT_DIR: . # to use data folder and avoid to create ra000012
    SCRATCH_DIR: /home/ra000012/data
    ADD_PROJECT_TO_HOST: false
    MAX_WALLCLOCK: 72:00
    TEMP_DIR: ''
```

In 3.15 this is not possible tho
