### ISSUE TITLE
Wrong hetjob processor sum

### ISSUE THREAD

**Issue by kinow** [BSC-ES/autosubmit#1293]
In GitLab by @Lerriola on May 14, 2024, 10:32

Hello @dbeltrankyl and @mcastril,

### Autosubmit Version

autosubmit version: 4.1.2

### Expid affected(If applicable)

t015 (testing suite mostly)

### Summary

The #PROCS shown/retrieved by the testing suite https://earth.bsc.es/gitlab/digital-twins/de_340/workflow/-/issues/358#note_279334 don't seem to match up with what is configured in the experiment conf. (Which uses **HETJOBS**)

```
JOBS:
  SIM:
    WALLCLOCK: "00:15"
    MEMORY:
        - 0
        - 0
        - 0
    NODES:
        - 1
        - 1
        - 1
    TASKS:
        - 8
        - 56
        - 8
    THREADS:
        - 1
        - 1
        - 7
```
If I'm not mistaken, with the current configuration, and asuming Autosubmit calculates the #PROCS in this way, we should have:

- For the first hetgroup:      
    `1 node * 8 tasks * 1 thread = 8 processors`      
- For the second hetgroup:      
    `1 node * 56 tasks * 1 thread = 56 processors`       
- For the third hetgroup:       
    `1 node * 8 tasks * 7 threads = 56 processors`       

Adding them together:           
`8 processors + 56 processors + 56 processors = 120 processors`

And not 1, which is what AS reports.

### Steps to reproduce

Not exactly sure what testing suite command it is.

### What is the current bug behavior?

It shows 1 #PROC and should show 120.

### What is the expected correct behavior?

It should add up all the hetgroup procs.

()
