### ISSUE TITLE
Flexible debug by adding inline custom_templates

### ISSUE THREAD

**Issue by kinow** [BSC-ES/autosubmit#1301]
In GitLab by @dbeltrankyl on May 23, 2024, 09:03

This issue is to add a customizable template for each job.

This is mainly useful for debugging, although it can be used to write short scripts.

The idea of adding is that instead of using PROJECT_TYPE: None, in which the default code is sleep 5 for each template, use this to have different sleep times, force jobs to fail, etc, or even only "skip" some workflow jobs. 

Usage:

```yaml
JOBS:
 JOB:
   FILE: bla.sh
   TYPE: bash
   CUSTOM_TEMPLATE: "sleep 5" 
 PYTHON_JOB:
   FILE: bla.sh
   TYPE: python3
   CUSTOM_TEMPLATE: |
      from time import sleep
      sleep(10)

```

The goal is to have a faster debug process
