### ISSUE TITLE
Autosubmit upgrade from v3 to v4 feedback

### ISSUE THREAD

**Issue by kinow** [BSC-ES/autosubmit#1308]
In GitLab by @ainagaya on May 28, 2024, 11:11

Hello @dbeltrankyl and @kinow,

I'm porting auto-nemo from AS3 to AS4. I'm using autosubmit 4.0.98 (latest available in the bscautosubmit machines). I used `autosubmit upgrade $expid` and it works really well!! Nevertheless, I wanted to tell you what didn't work in case you want to fix it. The first error I encountered is that custom directives have syntax errors:

The original experiment had:

```
[marenostrum5]
# Queue type. Options: ps, SGE, LSF, SLURM, PBS, eceaccess
TYPE = slurm
HOST = glogin1.bsc.es
PROJECT = bsc32
USER = bsc032627
QUEUE = gp_bsces
SCRATCH_DIR = /gpfs/scratch
ADD_PROJECT_TO_HOST = false
MAX_WALLCLOCK = 48:00
CUSTOM_DIRECTIVES = ["#SBATCH --hint=nomultithread"]
```

And it became:
```
PLATFORMS:
  marenostrum5:
    TYPE: slurm
    HOST: glogin1.bsc.es
    PROJECT: bsc32
    USER: bsc032627
    QUEUE: gp_bsces
    SCRATCH_DIR: /gpfs/scratch
    ADD_PROJECT_TO_HOST: 'false'
    MAX_WALLCLOCK: 48:00
    CUSTOM_DIRECTIVES: '["'
```
 
So the string is cut. This happens in more than one config file.

I'll tell you if I find more small issues. But in general the behavior of the command is amazing :smile: 

(Sorry for not following the template I thought this was a "special" issue)
