### ISSUE TITLE
Skipping of arbitrary jobs if certain jobs are completed/failed

### ISSUE THREAD

**Issue by kinow** [BSC-ES/autosubmit#1316]
In GitLab by @abaer-kit on Jun 3, 2024, 13:17

Hello @dbeltrankyl and @kinow,

### Summary of the feature

Is there a possibility to skip arbitrary jobs if certain dependencies are fulfilled, e.g. if a previous job has failed? If I understand the "skippable" keyword correctly, this only works for members/chunks.

### Describe your use case

I would like to check if some required input files are already present. If yes, start the simulation, if no create them from scratch.

My intuitive approach uses three jobs:
- A: check if input is there (lightweight, can run e.g. on the login node of the cluster)
- B: create the input data (some computational power required, runs in the batch system)
- C: simulation

With the straight dependencies A -> B -> C. However, if A succeeds, I can just skip B, because there is no need for B anymore.

### Describe the problem

I see four solutions for this
1. Make a configurable switch for the user to use existing or create new files. Quite elegant for the resulting workflow, slightly more complicated for the user.
2. Combine jobs A and B into one job, that does the check. However, this introduces some overhead of submitting a job to the batch system that does barely anything if the files do exist.
3. Make job A fail if the files do not exist and set the dependency A -> B to the status FAILED. With a weak dependency of C on both A and B, C will be started as soon as A is successful or (if not), after B is successful. But B will always be started, just to the quit without doing anything. More complicated than 1 with few benefit in runtime.
4. `>> new feature <<`: make a dependency A -> B "if and only if A has FAILED" and combine it with the weak dependencies as in 2.

Is there an alternative way to do something like this, or is this already implemented and I did not find out how?

**Comment by kinow** [comment]
In GitLab by @dbeltrankyl on Jun 3, 2024, 13:20

Hello @abaer-kit ,

Yes, I think that you're looking for this: https://autosubmit.readthedocs.io/en/master/userguide/defining_workflows/index.html#start-conditions

**Comment by kinow** [comment]
In GitLab by @abaer-kit on Jun 3, 2024, 13:53

Yes, I tried it with this, but it did not work out as I understood it. My config is:

`basic_conf.yml` (included in the minimmal):
```yaml
INPUT_FILE: "/home/andreas/tmp/test_input_file.txt"
DEFAULT:
  CUSTOM_CONFIG:
    PRE:
      - "%PROJDIR%/dummy_conf.yml"
      - "%PROJDIR%/jobs.yml"
```

`jobs.yml`:
```yaml
JOBS:
  FILE_CHECKER:
    FILE: file_checker.sh
  FILE_CREATOR:
    FILE: file_creator.sh
    DEPENDENCIES:
      FILE_CHECKER:
        STATUS: FAILED
  RUN:
    FILE: run.sh
    DEPENDENCIES: FILE_CREATOR? FILE_CHECKER?
```

`dummy_conf.yml` only contains some dummy experiment and platforms conf that Autosubmit does not fail.

The three jobs are:
`file_checker.sh`:
```bash
FILE2CHECK="%INPUT_FILE%"
if [ ! -f "$FILE2CHECK" ]
then
    exit 1
fi
```
`file_creator.sh`:
```bash
FILE2CHECK="%INPUT_FILE%"
touch "$FILE2CHECK"
sleep 30
date >> "$FILE2CHECK"
```
`run.sh`:
```bash
FILE2CHECK="%INPUT_FILE%"
echo "Using file '$FILE2CHECK'"
ls -la "$FILE2CHECK"
cat "$FILE2CHECK"
```

When running the experiment with the input file not existing, all three jobs run in order as expected (`FILE_CHECKER` fails, then `FILE_CREATOR` starts and once it is finished, `RUN` starts).

When running the experiment with the input file already existing, `FILE_CHECKER` completes (as expected), however then `FILE_CREATOR` starts and `RUN` does not. Only after `FILE_CREATOR` successfully started, `RUN` is started.

**Comment by kinow** [comment]
In GitLab by @dbeltrankyl on Jun 3, 2024, 15:48

Hello @abaer-kit , 

The Start_conditions replaces the weak_dependencies, so the "?" char is deprecated, and what does is the same as it would do if ? is not set? 

The old weak dependencies expect that a job finishes ( either in FAILED OR COMPLETED STATUS ).

The new Status works similarly, with the difference that you can put any status ( and in a finer granularity, you can, for example, specify a chunk of a section.

I think that right now, the only option is: 

```yaml
JOBS:
  FILE_CHECKER:
    FILE: file_checker.sh
  FILE_CREATOR:
    FILE: file_creator.sh
    DEPENDENCIES:
      FILE_CHECKER:
        STATUS: FAILED
  RUN:
    FILE: run.sh
    DEPENDENCIES: 
      FILE_CREATOR:
        STATUS: FAILED
```

Run will start  once file creator finishes is completed or failed



```yaml
JOBS:
  FILE_CHECKER:
    FILE: file_checker.sh
  FILE_CREATOR:
    FILE: file_creator.sh
    DEPENDENCIES:
      FILE_CHECKER:
        STATUS: FAILED
  RUN:
    FILE: run.sh
    DEPENDENCIES: 
      FILE_CREATOR:
        STATUS: RUNNING # includes completed,failed
      FILE_CHECKER:
        STATUS: FAILED
```

Run will start once file creator starts, and file_checker is completed or failed.


> 1. `>> new feature <<`: make a dependency A -> B "if and only if A has FAILED" and combine it with the weak dependencies as in 2.


Now that you raised this issue about start conditions/weak dependencies, we forgot to address this. That is similar to what we commented on at our internal meeting some months ago when we did this rework: 

Change STATUS: FAILED # that imitates the weak_dependency to STATUS: FINAL ( which contains completed and failed ) and STATUS: FAILED only when the job is failed.

**Comment by kinow** [comment]
In GitLab by @abaer-kit on Jun 3, 2024, 16:17

Ok, I think, I understand now how it works. Thanks a lot for the explanation and the quick response!

> Change STATUS: FAILED # that imitates the weak_dependency to STATUS: FINAL ( which contains completed and failed ) and STATUS: FAILED only when the job is failed.

This sounds exactly, what I thought of :smile:

**Comment by kinow** [comment]
In GitLab by @dbeltrankyl on Jun 13, 2024, 10:00

Implemented in From_status_final branch

![Selection_152](https://earth.bsc.es/gitlab/es/autosubmit/uploads/0427cd2c3e3d877d4ccbd19c85a46f85/Selection_152.png)

G2 <- Skipped because some dependencies are skipped.

G <- Completed because all dependencies are Failed, Completed.

Final means: Completed, Unknown, Skipped, Failed

Final_no_skip means: Completed, Unknown, Failed

```yaml
JOBS:
  A:
    SCRIPT: |
      echo ""
    running: once
  B:
    SCRIPT: |
      echo "Failure"
      forcesyntaxerror
    running: once
  C:
    SCRIPT: |
      echo ""
    running: once
    DEPENDENCIES:
      A:
        STATUS: FAILED
  D:
    SCRIPT: |
      echo ""
    running: once
    DEPENDENCIES:
      B:
        STATUS: FAILED
  E:
    SCRIPT: |
      echo ""
    running: once
    DEPENDENCIES:
      B:
        STATUS: COMPLETED
  F:
    SCRIPT: |
      echo ""
    running: once
    DEPENDENCIES:
      A
  G:
    SCRIPT: |
      echo ""
    DEPENDENCIES:
      A:
        STATUS: FINAL
      B:
        STATUS: FINAL
      E:
        STATUS: FINAL
      F:
        STATUS: FINAL
      D:
        STATUS: FINAL
      C:
        STATUS: FINAL

  A2:
    SCRIPT: |
      echo ""
    running: once
  B2:
    SCRIPT: |
      echo "Failure"
      forcesyntaxerror
    running: once
  C2:
    SCRIPT: |
      echo ""
    running: once
    DEPENDENCIES:
      A2:
        STATUS: FAILED
  D2:
    SCRIPT: |
      echo ""
    running: once
    DEPENDENCIES:
      B2:
        STATUS: FAILED
  E2:
    SCRIPT: |
      echo ""
    running: once
    DEPENDENCIES:
      B2:
        STATUS: COMPLETED
  F2:
    SCRIPT: |
      echo ""
    running: once
    DEPENDENCIES:
      A2:
  G2:
    SCRIPT: |
      echo ""
    DEPENDENCIES:
      A2:
        STATUS: FINAL_NO_SKIP
      B2:
        STATUS: FINAL_NO_SKIP
      E2:
        STATUS: FINAL_NO_SKIP
      F2:
        STATUS: FINAL_NO_SKIP
      D2:
        STATUS: FINAL_NO_SKIP
      C2:
        STATUS: FINAL_NO_SKIP
```

Working on docs, and will ~~be added in 4.1.8 today~~

Edit: It won't be in 4.1.8. There are some concerns about the complexity due the words "final" and "final_Skipped" other ideas are welcome

Edit2: Changed image, and definition

**Comment by kinow** [comment]
In GitLab by @mcastril on Jun 13, 2024, 19:25

Thanks Daniel. I'll try to help with feedback.

* Why is the arrow from B to E dashed and gray? The dependency is COMPLETED. Shouldn't it be an alias to `DEPENDENCIES: B`?
* What is the impact of `SKIPPED` in this example? Both workflows are identical, and so is their behavior.
* What exactly does `DEPENDENCIES: A2:` mean? Is it an alias for `DEPENDENCIES: A2`?

My idea was that the interface (the logic can be more complex) could be as easy as:

* STATUS: FAILED  # When we want a task to start ONLY when the parent is FAILED
* STATUS: FAILED? # When we want a task to start when the parent is FAILED or COMPLETED (similar to the previous ?)

Comments? Do I miss something?

**Comment by kinow** [comment]
I won't have time to review/comment on this until after the EDITO deliverable at least. But I think the `?` option @mcastril mentioned above might be simpler, although I am not sure if that would include SKIPPED, nor if we could have control over whether skipped is included or not.

Having `STATUS: $something-that's-not-status` will make validation of config a much harder task, but I guess we can live with that and push validation to AS5 if that's the case, or perform partial validation, etc.

So for me the priority would be to get user feedback to choose how to implement this, and be aware that if we add a syntax like that, we won't be able to change that until AS5... especially if that's used in DestinE or BSC-ES workflows at some point...

**Comment by kinow** [comment]
In GitLab by @dbeltrankyl on Aug 5, 2024, 09:17

mentioned in issue digital-twins/de_340-2/workflow#465

**Comment by kinow** [comment]
In GitLab by @dbeltrankyl on Oct 23, 2024, 15:03

This was not finished so I'm reopening it

**Comment by dbeltrankyl** [comment]
I'll prioritize this issue for 4.1.13. Sorry for the delay.

**Comment by dbeltrankyl** [comment]
Added in #2619 

Shortly in summary: 

All this code has moved to the new structures_table DB

Users can now set a specific parent with: 

```
child:
  dependencies:
       parent: 
          Status: Failed? -> failed or completed


child:
  dependencies:
       parent: 
         Status: Failed -> only failed
```

As before, it also works with the advanced dependencies
