### ISSUE TITLE
Autosubmit config checker: Vertical wrapper enabled and Max_wallclock

### ISSUE THREAD

**Issue by kinow** [BSC-ES/autosubmit#1386]
In GitLab by @dbeltrankyl on Aug 8, 2024, 11:25

Hello @kinow , @edgano 

Context:

We have a function to check the mandatory AS parameters before running an autosubmit command. This function should raise an AutosubmitCritical and show what is missing. 

Problem:

We missed a check when the max_wallclock is lower than one inner_job of the wrapper.

Example:

```yaml
Marenostrum5:
  MAX_WALLCLOCK: 02:30
Lumi:
  MAX_WALLCLOCK : 00:30
Sim:
 WALLCLOCK: 04:00
WRAPPERS:
 WRAPPER:
   JOBS_IN_WRAPPER: SIM
```

Excepted: 

Raise an Autosubmit Critical error similar to the msg: `"Invalid configuration, max_wallclock for {platform} is lower than the {wrapper} defined. Check {current_wrapper.jobs_in_wrapper}  or/and {platform} configuration`

Current behavior:

Autosubmit deadlock when trying to make the vertical wrapper.

Edit: I don't remember if this check was in the autosubmit configparser side.
