### ISSUE TITLE
calendar splits issue with chunksize

### ISSUE THREAD

**Issue by kinow** [BSC-ES/autosubmit#1420]
In GitLab by @franra9 on Sep 23, 2024, 15:30

( This is a template for bug reports. Please fill in the relevant information and delete the rest. )

Hello @dbeltrankyl and @kinow,

### Autosubmit Version

4.1.10

### Expid affected(If applicable)

a1q3 (not much relevant)

### Which task has issues? Where is the log(If applicable)

* **Full_name**: -

* **Log_Path:** -

### Steps to reproduce

Create the experiment with the joblist in the experiment.

### What is the current bug behavior?

If the chunksize is changed, it only takes the last month of the chunk to compute the splits :thinking: and only one month is created (not a 2-month-long chunk)

That is:

for chunksize 1 starting on November, I get a month of 30 splits. That is ok.

for chunksize 2 starting on November, I get a single month of 31 splits Instead of a 2 month-long chunk.

### What is the expected correct behavior?

I would assume that with chunksize 2 I would get a single chunk of 30 + 31 days.

### Relevant logs and/or screenshots(if applicable)

example conf:
```
EXPERIMENT:
   DATELIST: 20221101 #Startdate
   MEMBERS: fc0
   CHUNKSIZEUNIT: month
   SPLITSIZEUNIT: day
   CHUNKSIZE: 2
   #SPLITSIZE: 1
   SPLITPOLICY: flexible
   NUMCHUNKS: 1
   CALENDAR: standard

```

### Any other relevant information(if applicable)

Source issue in the workflows DestinE repository https://earth.bsc.es/gitlab/digital-twins/de_340-2/workflow/-/merge_requests/322

()
