### ISSUE TITLE
Split selection starting with 0

### ISSUE THREAD

**Issue by kinow** [BSC-ES/autosubmit#1422]
In GitLab by @franra9 on Sep 23, 2024, 16:52

( This is a template for bug reports. Please fill in the relevant information and delete the rest. )

Hello @dbeltrankyl and @kinow,

### Autosubmit Version

4.1.10

### Expid affected(If applicable)

a1q3

### Which task has issues? Where is the log(If applicable)

create step

* **Full_name**: -

* **Log_Path:** -

### Summary

I don't know if this is a bug or that some documentation is missing. I found that selecting SPLITS_FROM: 1 takes the second split of the chunk instead of the first one. (see example below)

### Steps to reproduce

Create with SPLITS_FROM: 1

### What is the current bug behavior?

it takes the second split

### What is the expected correct behavior?

take the first split

(it order to take the first split I hafe to do SPLITS_FROM: 0, which is not in the documentation, from here my doubts).

## examples of what I get:

![Screenshot_from_2024-09-23_16-45-26](https://earth.bsc.es/gitlab/es/autosubmit/uploads/c57de2dd1d88b573f24cbeff6d47b4e2/Screenshot_from_2024-09-23_16-45-26.png)
```
  DN:
    CHECK: on_submission
    DEPENDENCIES:
      APP_ENERGY_ONSHORE-1:
        SPLITS_FROM:
          0:
            SPLITS_TO: '%JOBS.DN.SPLITS%'
```

![Screenshot_from_2024-09-23_16-46-02](https://earth.bsc.es/gitlab/es/autosubmit/uploads/a8ad1b477ae852f0cb75a6e8e664e191/Screenshot_from_2024-09-23_16-46-02.png)
```
  DN:
    CHECK: on_submission
    DEPENDENCIES:
      APP_ENERGY_ONSHORE-1:
        SPLITS_FROM:
          1:
            SPLITS_TO: '%JOBS.DN.SPLITS%'
```

## What I would expect:

![Screenshot_from_2024-09-23_16-45-26](https://earth.bsc.es/gitlab/es/autosubmit/uploads/c57de2dd1d88b573f24cbeff6d47b4e2/Screenshot_from_2024-09-23_16-45-26.png)

```
  DN:
    CHECK: on_submission
    DEPENDENCIES:
      APP_ENERGY_ONSHORE-1:
        SPLITS_FROM:
          1:
            SPLITS_TO: '%JOBS.DN.SPLITS%'
```
```


### Any other relevant information(if applicable)

()
