### ISSUE TITLE
autosubmit plots should use natural order to sort entries

### ISSUE THREAD

**Issue by kinow** [BSC-ES/autosubmit#1427]
I was playing with some workflows for an issue from @franra9 (#1421), and noticed that plotting the splits I get each split appearing in an order with splits starting `10`, `11`, `12`, `13`, ..., `1`, then `20, `21`, ..., `2`. This is confusing for users, and displaying in natural order (i.e. `1`, `2`, `3`, ..., `9`, `10`, `11`, ...) would be more user friendly.

Not sure if for 4.1.11 or later. Maybe something Irene could work on too, to get familiar with the code.

**Comment by kinow** [comment]
![image](https://earth.bsc.es/gitlab/es/autosubmit/uploads/92eba84200f25ec980b5977ce96659bf/image.png)

Config example:

```
EXPERIMENT:
  # List of start dates
  DATELIST: '20001101'
  # List of members.
  MEMBERS: fc0
  # Unit of the chunk size. Can be hour, day, month, or year.
  CHUNKSIZEUNIT: month
  # Size of each chunk.
  CHUNKSIZE: '4'
  # Number of chunks of the experiment.
  NUMCHUNKS: '1'
  CHUNKINI: ''
  # Calendar used for the experiment. Can be standard or noleap.
  CALENDAR: standard

  SPLITSIZEUNIT: day
  # SPLITSIZE: 1
  SPLITPOLICY: flexible
```

With the default jobs, minus the `POST` replaced by `APP`:

```
  SIM:
    FILE: SIM.sh
    DEPENDENCIES: INI SIM-1
    RUNNING: chunk
    WALLCLOCK: 00:05
  APP:
    FILE: app.sh
    DEPENDENCIES: SIM
    RUNNING: chunk
    SPLITS: auto
    WALLCLOCK: 00:05
```
