### ISSUE TITLE
Possible bug in STATUS: RUNNING dependencies

### ISSUE THREAD

**Issue by kinow** [BSC-ES/autosubmit#1435]
In GitLab by @franra9 on Oct 16, 2024, 15:52

Hello @dbeltrankyl and @kinow,

### Autosubmit Version

4.1.10

### Expid affected(If applicable)

a1q3

### Which task has issues? Where is the log(If applicable)

* **Full_name**: does not apply

* **Log_Path:** does not apply

### Summary

DN is submitted on SIM submission and not on running despite the jobs.yml does not say so.

### Steps to reproduce

Try copying a1q3 but there is some issue before.

### What is the current bug behavior?

DN submitted on SIM on submission instead of Running (SIM is on the queue but DN already running)

### What is the expected correct behavior?

DN submitted on SIM on running instead.

### Relevant logs and/or screenshots(if applicable)

```
Job a1q3_20200101_fc0_1_SIM is QUEUING
Checking 1 jobs for platform LUMI-LOGIN
Job a1q3_20200101_fc0_1_1_DN is RUNNING
```

```
(...)
  DN:
    CHECK: on_submission
    DEPENDENCIES:
      APP_ENERGY_ONSHORE-1:
        SPLITS_FROM:
          '0':
            SPLITS_TO: '%JOBS.DN.SPLITS%'
      DN:
        SPLITS_FROM:
          all:
            SPLITS_TO: previous
      REMOTE_SETUP:
        STATUS: COMPLETED
      SIM:
        STATUS: RUNNING
(...)
```
### Any other relevant information(if applicable)

()
