### ISSUE TITLE
Issues with wrappers and splits

### ISSUE THREAD

**Issue by kinow** [BSC-ES/autosubmit#1445]
In GitLab by @franra9 on Oct 30, 2024, 14:54

( This is a template for bug reports. Please fill in the relevant information and delete the rest. )

Hello @dbeltrankyl and @kinow,

### Autosubmit Version

4.1.10

### Expid affected(If applicable)

a1tw

### Which task has issues? Where is the log(If applicable)

Create and monitor step if `-cw` flag is activated.

### Summary

AS enters into a kind of infinite loop where the create or monitor process is never stoped.

### Steps to reproduce

copy the experiment and create with this joblist:

```
JOBS:
  APP:
    CHECK: on_submission
    DEPENDENCIES: OPA
    FILE: templates/application.sh
    FOR:
      DEPENDENCIES:
      - APP_ENERGY_ONSHORE:
          SPLITS_FROM:
            all:
              SPLITS_TO: previous
        OPA_ENERGY_ONSHORE_1:
          SPLITS_FROM:
            all:
              SPLITS_TO: "[1:%JOBS.DN.SPLITS%]*\\1"
        OPA_ENERGY_ONSHORE_2:
          SPLITS_FROM:
            all:
              SPLITS_TO: "[1:%JOBS.DN.SPLITS%]*\\1"
        OPA_ENERGY_ONSHORE_3:
          SPLITS_FROM:
            all:
              SPLITS_TO: "[1:%JOBS.DN.SPLITS%]*\\1"
        OPA_ENERGY_ONSHORE_4:
          SPLITS_FROM:
            all:
              SPLITS_TO: "[1:%JOBS.DN.SPLITS%]*\\1"
        OPA_ENERGY_ONSHORE_5:
          SPLITS_FROM:
            all:
              SPLITS_TO: "[1:%JOBS.DN.SPLITS%]*\\1"
        OPA_ENERGY_ONSHORE_6:
          SPLITS_FROM:
            all:
              SPLITS_TO: "[1:%JOBS.DN.SPLITS%]*\\1"
        OPA_ENERGY_ONSHORE_7:
          SPLITS_FROM:
            all:
              SPLITS_TO: "[1:%JOBS.DN.SPLITS%]*\\1"
      NAME: '%RUN.APP_NAMES%'
      SPLITS: auto
    NODES: 1
    PARTITION: '%CURRENT_APP_PARTITION%'
    PLATFORM: '%DEFAULT.HPCARCH%'
    PROCESSORS: 1
    RUNNING: chunk
    TASKS: 1
    THREADS: 1
    WALLCLOCK: 00:10
  DN:
    CHECK: on_submission
    DEPENDENCIES:
      APP_ENERGY_ONSHORE-1:
        SPLITS_FROM:
          '0':
            SPLITS_TO: '%JOBS.DN.SPLITS%'
      DN:
        SPLITS_FROM:
          all:
            SPLITS_TO: previous
      REMOTE_SETUP:
        STATUS: COMPLETED
    FILE: templates/dn.sh,conf/mother_request.yml
    PLATFORM: '%DEFAULT.HPCARCH%-login'
    RUNNING: chunk
    SPLITS: auto
    TOTALJOBS: 1
    WALLCLOCK: 02:00
  LOCAL_SETUP:
    CHECK: on_submission
    FILE: templates/local_setup.sh
    PLATFORM: LOCAL
    RUNNING: once
  OPA:
    CHECK: on_submission
    DEPENDENCIES: null
    FILE: templates/opa.sh
    FOR:
      DEPENDENCIES:
      - DN:
          SPLITS_FROM:
            all:
              SPLITS_TO: "[1:%JOBS.DN.SPLITS%]*\\1"
        OPA_ENERGY_ONSHORE_1:
          SPLITS_FROM:
            all:
              SPLITS_TO: previous
      - DN:
          SPLITS_FROM:
            all:
              SPLITS_TO: "[1:%JOBS.DN.SPLITS%]*\\1"
        OPA_ENERGY_ONSHORE_2:
          SPLITS_FROM:
            all:
              SPLITS_TO: previous
      - DN:
          SPLITS_FROM:
            all:
              SPLITS_TO: "[1:%JOBS.DN.SPLITS%]*\\1"
        OPA_ENERGY_ONSHORE_3:
          SPLITS_FROM:
            all:
              SPLITS_TO: previous
      - DN:
          SPLITS_FROM:
            all:
              SPLITS_TO: "[1:%JOBS.DN.SPLITS%]*\\1"
        OPA_ENERGY_ONSHORE_4:
          SPLITS_FROM:
            all:
              SPLITS_TO: previous
      - DN:
          SPLITS_FROM:
            all:
              SPLITS_TO: "[1:%JOBS.DN.SPLITS%]*\\1"
        OPA_ENERGY_ONSHORE_5:
          SPLITS_FROM:
            all:
              SPLITS_TO: previous
      - DN:
          SPLITS_FROM:
            all:
              SPLITS_TO: "[1:%JOBS.DN.SPLITS%]*\\1"
        OPA_ENERGY_ONSHORE_6:
          SPLITS_FROM:
            all:
              SPLITS_TO: previous
      - DN:
          SPLITS_FROM:
            all:
              SPLITS_TO: "[1:%JOBS.DN.SPLITS%]*\\1"
        OPA_ENERGY_ONSHORE_7:
          SPLITS_FROM:
            all:
              SPLITS_TO: previous
      NAME: '%RUN.OPA_NAMES%'
      SPLITS: '[''auto'', ''auto'', ''auto'', ''auto'', ''auto'', ''auto'', ''auto'']'
    NODES: 1
    PARTITION: '%CURRENT_APP_PARTITION%'
    PLATFORM: '%DEFAULT.HPCARCH%'
    PROCESSORS: 1
    RUNNING: chunk
    TASKS: 1
    THREADS: 1
  REMOTE_SETUP:
    CHECK: on_submission
    DEPENDENCIES: SYNCHRONIZE
    FILE: templates/remote_setup.sh,templates/fdb/confignative.yaml,templates/fdb/configlatlon.yaml,templates/fdb/config.yaml
    PLATFORM: '%DEFAULT.HPCARCH%-login'
    RUNNING: once
    WALLCLOCK: 02:00
  SYNCHRONIZE:
    CHECK: on_submission
    DEPENDENCIES: LOCAL_SETUP
    FILE: templates/synchronize.sh
    PLATFORM: LOCAL
    RUNNING: once
RUN:
  APP_NAMES:
  - ENERGY_ONSHORE
  OPA_NAMES:
  - energy_onshore_1
  - energy_onshore_2
  - energy_onshore_3
  - energy_onshore_4
  - energy_onshore_5
  - energy_onshore_6
  - energy_onshore_7

WRAPPERS:
  WRAPPER_0:
    TYPE: "vertical"
    JOBS_IN_WRAPPER: "OPA_ENERGY_ONSHORE_1"
    METHOD: SRUN #  
```

### What is the current bug behavior?

Visuals never appear. I don't know if the wrapper exists or if I can just don't see it. I am checking if the wrappers are active but just only not visualized.

### What is the expected correct behavior?

monitor and create runs and created the visuals.

### Relevant logs and/or screenshots(if applicable)

```
[froura@climatedt-wf conf]$ autosubmit create a1tw -cw
/appl/AS/4.1.10/lib64/python3.9/site-packages/paramiko-3.4.0-py3.9.egg/paramiko/pkey.py:100: CryptographyDeprecationWarning: TripleDES has been moved to cryptography.hazmat.decrepit.ciphers.algorithms.TripleDES and will be removed from this module in 48.0.0.
  "cipher": algorithms.TripleDES,
/appl/AS/4.1.10/lib64/python3.9/site-packages/paramiko-3.4.0-py3.9.egg/paramiko/transport.py:259: CryptographyDeprecationWarning: TripleDES has been moved to cryptography.hazmat.decrepit.ciphers.algorithms.TripleDES and will be removed from this module in 48.0.0.
  "class": algorithms.TripleDES,
Autosubmit is running with 4.1.10
Preparing .lock file to avoid multiple instances with same expid.
Using project folder: /appl/AS/AUTOSUBMIT_DATA/a1tw/proj

Checking configuration files...
Expdef config file is correct
Platforms sections: OK
Jobs sections OK
wrappers OK
Autosubmit general sections OK
Configuration files OK

Loading parameters...

Creating the jobs list...
Loading JobList
Loading JobList
Creating jobs...
For the section DN with date:20240202 the number of splits is 29.
For the section DN with date:20240302 the number of splits is 31.
For the section APP_ENERGY_ONSHORE with date:20240202 the number of splits is 29.
For the section APP_ENERGY_ONSHORE with date:20240302 the number of splits is 31.
For the section OPA_ENERGY_ONSHORE_1 with date:20240202 the number of splits is 29.
For the section OPA_ENERGY_ONSHORE_1 with date:20240302 the number of splits is 31.
For the section OPA_ENERGY_ONSHORE_2 with date:20240202 the number of splits is 29.
For the section OPA_ENERGY_ONSHORE_2 with date:20240302 the number of splits is 31.
For the section OPA_ENERGY_ONSHORE_3 with date:20240202 the number of splits is 29.
For the section OPA_ENERGY_ONSHORE_3 with date:20240302 the number of splits is 31.
For the section OPA_ENERGY_ONSHORE_4 with date:20240202 the number of splits is 29.
For the section OPA_ENERGY_ONSHORE_4 with date:20240302 the number of splits is 31.
For the section OPA_ENERGY_ONSHORE_5 with date:20240202 the number of splits is 29.
For the section OPA_ENERGY_ONSHORE_5 with date:20240302 the number of splits is 31.
For the section OPA_ENERGY_ONSHORE_6 with date:20240202 the number of splits is 29.
For the section OPA_ENERGY_ONSHORE_6 with date:20240302 the number of splits is 31.
For the section OPA_ENERGY_ONSHORE_7 with date:20240202 the number of splits is 29.
For the section OPA_ENERGY_ONSHORE_7 with date:20240302 the number of splits is 31.
Adding dependencies to the graph..
Adding dependencies to the job..
Transitive reduction...
Looking for edgeless jobs...

Saving the jobs list...
Loading JobList
Load finished
Creating jobs...
For the section DN with date:20240202 the number of splits is 29.
For the section DN with date:20240302 the number of splits is 31.
For the section APP_ENERGY_ONSHORE with date:20240202 the number of splits is 29.
For the section APP_ENERGY_ONSHORE with date:20240302 the number of splits is 31.
For the section OPA_ENERGY_ONSHORE_1 with date:20240202 the number of splits is 29.
For the section OPA_ENERGY_ONSHORE_1 with date:20240302 the number of splits is 31.
For the section OPA_ENERGY_ONSHORE_2 with date:20240202 the number of splits is 29.
For the section OPA_ENERGY_ONSHORE_2 with date:20240302 the number of splits is 31.
For the section OPA_ENERGY_ONSHORE_3 with date:20240202 the number of splits is 29.
For the section OPA_ENERGY_ONSHORE_3 with date:20240302 the number of splits is 31.
For the section OPA_ENERGY_ONSHORE_4 with date:20240202 the number of splits is 29.
For the section OPA_ENERGY_ONSHORE_4 with date:20240302 the number of splits is 31.
For the section OPA_ENERGY_ONSHORE_5 with date:20240202 the number of splits is 29.
For the section OPA_ENERGY_ONSHORE_5 with date:20240302 the number of splits is 31.
For the section OPA_ENERGY_ONSHORE_6 with date:20240202 the number of splits is 29.
For the section OPA_ENERGY_ONSHORE_6 with date:20240302 the number of splits is 31.
For the section OPA_ENERGY_ONSHORE_7 with date:20240202 the number of splits is 29.
For the section OPA_ENERGY_ONSHORE_7 with date:20240302 the number of splits is 31.
Adding dependencies to the graph..
Adding dependencies to the job..
Transitive reduction...
Looking for edgeless jobs...
Calculating possible ready jobs for LUMI
Calculating possible ready jobs for local
Section:LOCAL_SETUP can submit 2 jobs at this time
Calculating wrapper packages
Calculating possible ready jobs for LUMI-LOGIN
Calculating possible ready jobs for LUMI
Calculating possible ready jobs for local
Section:SYNCHRONIZE can submit 2 jobs at this time
Calculating wrapper packages
Calculating possible ready jobs for LUMI-LOGIN
Calculating possible ready jobs for LUMI
Calculating possible ready jobs for local
Calculating possible ready jobs for LUMI-LOGIN
Section:REMOTE_SETUP can submit 1 jobs at this time
Calculating wrapper packages
Calculating possible ready jobs for LUMI
Calculating possible ready jobs for local
Calculating possible ready jobs for LUMI-LOGIN
Section:DN can submit 1 jobs at this time
Calculating wrapper packages
Calculating possible ready jobs for LUMI
Section:OPA_ENERGY_ONSHORE_1 can submit 2 jobs at this time
Section:OPA_ENERGY_ONSHORE_2 can submit 2 jobs at this time
Section:OPA_ENERGY_ONSHORE_3 can submit 2 jobs at this time
Section:OPA_ENERGY_ONSHORE_4 can submit 2 jobs at this time
Section:OPA_ENERGY_ONSHORE_5 can submit 2 jobs at this time
Section:OPA_ENERGY_ONSHORE_6 can submit 2 jobs at this time
Section:OPA_ENERGY_ONSHORE_7 can submit 2 jobs at this time
Calculating wrapper packages
Building packages for WRAPPER_0
Built 1 wrappers for WRAPPER_0
Calculating possible ready jobs for local
Calculating possible ready jobs for LUMI-LOGIN
Section:DN can submit 1 jobs at this time
Calculating wrapper packages
Calculating possible ready jobs for LUMI
Section:OPA_ENERGY_ONSHORE_1 can submit 2 jobs at this time
Section:OPA_ENERGY_ONSHORE_2 can submit 2 jobs at this time
Section:OPA_ENERGY_ONSHORE_3 can submit 2 jobs at this time

```

### Any other relevant information(if applicable)

()
