### ISSUE TITLE
Problems with custom_directives

### ISSUE THREAD

**Issue by kinow** [BSC-ES/autosubmit#1457]
In GitLab by @franra9 on Nov 19, 2024, 12:42

( This is a template for bug reports. Please fill in the relevant information and delete the rest. )

Hello @dbeltrankyl and @kinow,

### Autosubmit Version

4.1.10
### Expid affected(If applicable)

OPA_ENERGY_ONSHORE_1

### Which task has issues? Where is the log(If applicable)

* **Full_name**: a1tz_20240101_fc0_1_1_OPA_ENERGY_ONSHORE_6

* **Log_Path:** /gpfs/scratch/ehpc01/bsc032056/a1tz/LOG_a1tz

### Summary

apparently not parsed correctly from opa.yml configuration file:

```
# Options for different HPCs here
PLATFORMS:
  LUMI:
    OPA_CUSTOM_DIRECTIVES: '#SBATCH --mem=100G'
    OPA_EXCLUSIVE: False
  MARENOSTRUM5:
    OPA_CUSTOM_DIRECTIVES: "['#SBATCH -t 00:29:00','#SBATCH --exclusive']"
    OPA_EXCLUSIVE: 'True'
```
This is parsed in the jobs_apps.yml as

```
(...)
  OPA:
    CHECK: on_submission
    CUSTOM_DIRECTIVES: '%CURRENT_OPA_CUSTOM_DIRECTIVES%'

(...)
```

and in the `.cmd` appears as:

```
#SBATCH -t 48:00:00
#SBATCH -J a1tz_20240101_fc0_1_1_OPA_ENERGY_ONSHORE_6
#SBATCH --output=/gpfs/scratch/ehpc01/bsc032056/a1tz/LOG_a1tz/a1tz_20240101_fc0_1_1_OPA_ENERGY_ONSHORE_6.cmd.out.0
#SBATCH --error=/gpfs/scratch/ehpc01/bsc032056/a1tz/LOG_a1tz/a1tz_20240101_fc0_1_1_OPA_ENERGY_ONSHORE_6.cmd.err.0
['#SBATCH -t 00:29:00','#SBATCH --exclusive']
```

I tried as well setting

```
OPA:
  MARENOSTRUM5:
    OPA_CUSTOM_DIRECTIVES: ['#SBATCH -t 00:29:00','#SBATCH --exclusive']

```
Unsuccessfully

### Steps to reproduce

Create the template using the keys provided above.

### What is the current bug behavior?

I'm getting this `['#SBATCH -t 00:29:00','#SBATCH --exclusive']` in the .cmd instead of an expanded list

### What is the expected correct behavior?

```
#SBATCH -t 00:29:00
#SBATCH --exclusive
```

### Any other relevant information(if applicable)

Maybe it is just some dumb quote thing, but as the `inspect` command is very slow, it is hard to try the different combinations.

I tried as well to use the `EXCLUSIVE: 'True'` flag but I was getting an error 

```
Calculating possible ready jobs for MARENOSTRUM5
^[[1m ^[[31m[CRITICAL] A not admitted configuration or error in the code has happened: object of type 'bool' has no len().
```

Funfact: with `EXCLUSIVE: False` I was not getting any error

IDK if I should add a separate issue for that. You tell me ;)

Thanks!

()

**Comment by kinow** [comment]
In GitLab by @dbeltrankyl on Nov 19, 2024, 12:53

Hello @franra9 

Can you test it with 4.1.11? Available at climate-dt.

I've tested with the current master, and it is working for me: 

File I used: 

```yaml
CONFIG:
  # Current version of autosubmit.
  AUTOSUBMIT_VERSION: "4.1.10"
  # Maximum number of jobs permitted in the waiting status.
  MAXWAITINGJOBS: 20
  # Total number of jobs in the workflow.
  TOTALJOBS: 20
  SAFETYSLEEPTIME: 0
  RETRIALS: 0
MAIL:
  NOTIFICATIONS: False
  TO:
STORAGE:
  TYPE: pkl
  COPY_REMOTE_LOGS: true

EXPERIMENT:
  DATELIST: 20221101
  MEMBERS: fc0
  CHUNKSIZEUNIT: month
  #SPLITSIZEUNIT: day
  CHUNKSIZE: 2
  NUMCHUNKS: 1
  #SPLITSIZE: 1
  SPLITPOLICY: flexible
  CHUNKINI: ''
  CALENDAR: standard
PROJECT:
  # Type of the project.
  PROJECT_TYPE: git
  # Folder to hold the project sources.
  PROJECT_DESTINATION: git_project
GIT:
  PROJECT_ORIGIN: "blabla"
  PROJECT_BRANCH: "blabla"
  PROJECT_COMMIT: ''
  PROJECT_SUBMODULES: ''
  FETCH_SINGLE_BRANCH: true
PLATFORMS:
  MARENOSTRUM5:
    TYPE: slurm
    HOST: mn5-gpp2
    PROJECT: bsc32
    USER: bsc032070
    QUEUE: gp_debug
    SCRATCH_DIR: /gpfs/scratch
    ADD_PROJECT_TO_HOST: false
    MAX_WALLCLOCK: 48:00
    TEMP_DIR: ''
    MAX_PROCESSORS: 99999

JOBS:
  E:
    SCRIPT: |
      echo ""
    running: once
    CUSTOM_DIRECTIVES: "%TEST%"
    PLATFORM: marenostrum5


Test: "['#SBATCH -t 00:29:00','#SBATCH --exclusive']"

```

```bash
###############################################################################
#
#SBATCH --qos=gp_debug
#
#
#SBATCH -A bsc32
#
#SBATCH --cpus-per-task=1
#
#
#SBATCH -n 1
#
#SBATCH -t 48:00:00
#SBATCH -J a000_E
#SBATCH --output=/gpfs/scratch/bsc32/bsc032070/a000/LOG_a000/a000_E.cmd.out.0
#SBATCH --error=/gpfs/scratch/bsc32/bsc032070/a000/LOG_a000/a000_E.cmd.err.0
#SBATCH -t 00:29:00 # <- 
#SBATCH --exclusive # <-
#
#

```

**Comment by kinow** [comment]
In GitLab by @dbeltrankyl on Nov 19, 2024, 12:55

> Maybe it is just some dumb quote thing, but as the `inspect` command is very slow, it is hard to try the different combinations.

This is also improved in 4.1.11 ( confirmed by @ainagaya )

**Comment by kinow** [comment]
In GitLab by @dbeltrankyl on Nov 19, 2024, 12:58

Nvm, 

There is an issue when it is used along with current. 

```yaml
PLATFORMS:
  MARENOSTRUM5:
    TYPE: slurm
    HOST: mn5-gpp2
    PROJECT: bsc32
    USER: bsc032070
    QUEUE: gp_debug
    SCRATCH_DIR: /gpfs/scratch
    ADD_PROJECT_TO_HOST: false
    MAX_WALLCLOCK: 48:00
    TEMP_DIR: ''
    MAX_PROCESSORS: 99999
    Test: "['#SBATCH -t 00:29:00','#SBATCH --exclusive']"
```

Works
```yaml
    CUSTOM_DIRECTIVES: "%PLATFORMS.MARENOSTRUM5.TEST%"
```

Doesn't work, it is literally added as you detected
```yaml
    CUSTOM_DIRECTIVES: "%CURRENT_TEST%"
```
