### ISSUE TITLE
Issue with EXCLUSIVE: True

### ISSUE THREAD

**Issue by kinow** [BSC-ES/autosubmit#1461]
In GitLab by @franra9 on Nov 22, 2024, 16:42

( This is a template for bug reports. Please fill in the relevant information and delete the rest. )

Hello @dbeltrankyl and @kinow,

### Autosubmit Version

4.1.10

### Expid affected(If applicable)

t02s

### Which task has issues? Where is the log(If applicable)

* **Full_name**: autosubmit inspect $expid

* **Log_Path:** ASLOGS

### Summary

the inspect command is failing if I state EXCLUSIVE: True

and then I call it using `CURRENT_*`

### Steps to reproduce

autosubmit inspect after copying the expid that has issues

### What is the current bug behavior?

inspect not successful

### What is the expected correct behavior?

inspect successful

### Relevant logs and/or screenshots(if applicable)

```
[froura@climatedt-wf conf]$ autosubmit inspect t02s
/appl/AS/4.1.10/lib64/python3.9/site-packages/paramiko-3.4.0-py3.9.egg/paramiko/pkey.py:100: CryptographyDeprecationWarning: TripleDES has been moved to cryptography.hazmat.decrepit.ciphers.algorithms.TripleDES and will be removed from this module in 48.0.0.
  "cipher": algorithms.TripleDES,
/appl/AS/4.1.10/lib64/python3.9/site-packages/paramiko-3.4.0-py3.9.egg/paramiko/transport.py:259: CryptographyDeprecationWarning: TripleDES has been moved to cryptography.hazmat.decrepit.ciphers.algorithms.TripleDES and will be removed from this module in 48.0.0.
  "class": algorithms.TripleDES,
Autosubmit is running with 4.1.10
Inspecting experiment t02s
Starting inspect command


Checking configuration files...
Expdef config file is correct
Platforms sections: OK
Jobs sections OK
Autosubmit general sections OK
Configuration files OK

Loading JobList
Load finished
Creating jobs...
For the section DN with date:20240101 the number of splits is 1.
For the section APP_ENERGY_ONSHORE with date:20240101 the number of splits is 1.
For the section APP_HYDROLAND with date:20240101 the number of splits is 1.
For the section OPA_ENERGY_ONSHORE_1 with date:20240101 the number of splits is 1.
For the section OPA_ENERGY_ONSHORE_2 with date:20240101 the number of splits is 1.
For the section OPA_ENERGY_ONSHORE_3 with date:20240101 the number of splits is 1.
For the section OPA_ENERGY_ONSHORE_4 with date:20240101 the number of splits is 1.
For the section OPA_ENERGY_ONSHORE_5 with date:20240101 the number of splits is 1.
For the section OPA_ENERGY_ONSHORE_6 with date:20240101 the number of splits is 1.
For the section OPA_ENERGY_ONSHORE_7 with date:20240101 the number of splits is 1.
For the section OPA_HYDROLAND_1 with date:20240101 the number of splits is 1.
For the section OPA_HYDROLAND_2 with date:20240101 the number of splits is 1.
Adding dependencies to the graph..
Adding dependencies to the job..
Transitive reduction...
Looking for edgeless jobs...
Loading JobList
Load finished
Creating jobs...
For the section DN with date:20240101 the number of splits is 1.
For the section APP_ENERGY_ONSHORE with date:20240101 the number of splits is 1.
For the section APP_HYDROLAND with date:20240101 the number of splits is 1.
For the section OPA_ENERGY_ONSHORE_1 with date:20240101 the number of splits is 1.
For the section OPA_ENERGY_ONSHORE_2 with date:20240101 the number of splits is 1.
For the section OPA_ENERGY_ONSHORE_3 with date:20240101 the number of splits is 1.
For the section OPA_ENERGY_ONSHORE_4 with date:20240101 the number of splits is 1.
For the section OPA_ENERGY_ONSHORE_5 with date:20240101 the number of splits is 1.
For the section OPA_ENERGY_ONSHORE_6 with date:20240101 the number of splits is 1.
For the section OPA_ENERGY_ONSHORE_7 with date:20240101 the number of splits is 1.
For the section OPA_HYDROLAND_1 with date:20240101 the number of splits is 1.
For the section OPA_HYDROLAND_2 with date:20240101 the number of splits is 1.
Adding dependencies to the graph..
Adding dependencies to the job..
Transitive reduction...
Looking for edgeless jobs...
Starting to generate cmd scripts
Generating cmd scripts only for selected jobs
Calculating possible ready jobs for local
Section:LOCAL_SETUP can submit 20 jobs at this time
Calculating possible ready jobs for MARENOSTRUM5-LOGIN
Calculating possible ready jobs for MARENOSTRUM5
Calculating possible ready jobs for local
Section:SYNCHRONIZE can submit 20 jobs at this time
Script t02s_SYNCHRONIZE OK
Calculating possible ready jobs for MARENOSTRUM5-LOGIN
Calculating possible ready jobs for MARENOSTRUM5
Calculating possible ready jobs for local
Calculating possible ready jobs for MARENOSTRUM5-LOGIN
Section:REMOTE_SETUP can submit 20 jobs at this time
Calculating possible ready jobs for MARENOSTRUM5
Calculating possible ready jobs for local
Calculating possible ready jobs for MARENOSTRUM5-LOGIN
Section:DN can submit 1 jobs at this time
Calculating possible ready jobs for MARENOSTRUM5
Calculating possible ready jobs for local
Calculating possible ready jobs for MARENOSTRUM5-LOGIN
Calculating possible ready jobs for MARENOSTRUM5
 [CRITICAL] A not admitted configuration or error in the code has happened: object of type 'bool' has no len().
 Please report it to Autosubmit Developers through Git
More info at https://autosubmit.readthedocs.io/en/master/troubleshooting/error-codes.html

```

### Any other relevant information(if applicable)

This issue may be related to #1458 

()

**Comment by kinow** [comment]
@franra9 I think you are using `CURRENT_OPA_EXCLUSIVE` in another job, to get the `EXCLUSIVE` value from the `OPA` top-level object? From what I could see, the config looks like this, simplified?

```yaml
OPA:
  OPA_PARAM_1: ...
  OPA_PARAM_etc: ...
  EXCLUSIVE: True
# other values in multiple files

# in jobs_apps.yml
JOBS:
  OPA:
    EXCLUSIVE: '%CURRENT_OPA_EXCLUSIVE%'
```

But I am not sure if there is a `CURRENT_OPA` set by Autosubmit? I think this could work, instead?

```yaml
# in jobs_apps.yml or some other file
JOBS:
  OPA:
    EXCLUSIVE: '%OPA.EXCLUSIVE%'
```

That should replace the `OPA.EXCLUSIVE` by the value you have in that `OPA` top-level dict/object.

**Comment by kinow** [comment]
In GitLab by @franra9 on Nov 25, 2024, 12:11

thanks @kinow for the suggestion. I think though this would unfortunately not work as the `EXCLUSIVE` key is platform. That's why we are setting it under platforms. That's why we need `CURRENT_`

What I am using is:

```
# Options for different HPCs here
PLATFORMS:
  LUMI:
    OPA_CUSTOM_DIRECTIVES: '#SBATCH --mem=100G'
    OPA_EXCLUSIVE: False
  MARENOSTRUM5:
    OPA_CUSTOM_DIRECTIVES: '#SBATCH -t 00:29:00'
    OPA_EXCLUSIVE: True
```
plus this key in jobs:

```
    CUSTOM_DIRECTIVES: "%CURRENT_OPA_CUSTOM_DIRECTIVES%"
    EXCLUSIVE: "%CURRENT_OPA_EXCLUSIVE%"
```
(https://earth.bsc.es/gitlab/digital-twins/de_340-2/workflow/-/blob/670-check-that-multi-applications-app-wf-is-still-working/conf/jobs_template.yml_tmp#L69)

For now I could overcome this by asking for all the cores in a node:
```
# Options for different HPCs here
PLATFORMS:
  LUMI:
    OPA_CUSTOM_DIRECTIVES: '#SBATCH --mem=100G'
    OPA_EXCLUSIVE: False
    OPA_PROCESSORS: 1
  MARENOSTRUM5:
    OPA_CUSTOM_DIRECTIVES: '#SBATCH -t 00:29:00'
    OPA_PROCESSORS: 112
```

**Comment by kinow** [comment]
In GitLab by @dbeltrankyl on Nov 25, 2024, 12:15

In that case, I think it may be the same issue as in #1458. 

I'll include the EXCLUSIVE directive in the pytests ( not done yet) there https://earth.bsc.es/gitlab/es/autosubmit/-/merge_requests/518

**Comment by dbeltrankyl** [comment]
Closing this issue, 

Not sure when it was solved, but I've just tested in master:

```yaml
PLATFORMS:
 mn5:
  Exclusive: True
```
The inspect is working, and #SBATCH --exclusive is added
