### ISSUE TITLE
Automate the documentation of Autosubmit variables (for job, platform, and project) - [merged]

### ISSUE THREAD

**Issue by kinow** [BSC-ES/autosubmit#1828]
_Merges automate-variables-doc -> master_

Closes #951

Getting there. This draft produces the rst syntax that looks like the existing code.

![image](https://earth.bsc.es/gitlab/es/autosubmit/uploads/ec642d93f7ab1493b8e9a4e17a19a9d4/image.png)

(top is produced by the directive reading the code, bottom is the written docs text; section is duplicated as I hadn't time to complete that today).

The decorator added in this merge request populates a list of parameters. This list is used by the Sphinx directive to produce the documentation. This part is already unit-tested, 100% covered. The rest of the work before this is ready for review includes:

- [x] add a decorator to mark the parameters
- [x] use properties to define parameters
- [x] generate the three sections with variables for jobs, platforms, and projects, automatically
- [x] use the same list of parameters and docs to populate the comments in the YAML configuration where these parameters appear
- [x] add unit tests to the parts changed, or new code
- [x] make sure RTD rendered output matches the locally generated site - https://autosubmit--340.org.readthedocs.build/en/340/userguide/variables.html

**Comment by kinow** [comment]
p.s. this merge request includes more changes, mainly for testing. Not worth reviewing the code yet.

**Comment by kinow** [comment]
added 1 commit

<ul><li>56236298 - WIP adding some more variables and updating the markdown</li></ul>

[Compare with previous version](/gitlab/es/autosubmit/-/merge_requests/340/diffs?diff_id=14612&start_sha=655da18bf9ffd122e1a846e9efc2d903c7dbf781)

**Comment by kinow** [comment]
added 1 commit

<ul><li>6798e66e - Parametrize the sphinx directive</li></ul>

[Compare with previous version](/gitlab/es/autosubmit/-/merge_requests/340/diffs?diff_id=14614&start_sha=56236298ab4c17aef18a838e9687910ebc8df220)

**Comment by kinow** [comment]
added 1 commit

<ul><li>61a89ac1 - Fix typos, re-word text a bit</li></ul>

[Compare with previous version](/gitlab/es/autosubmit/-/merge_requests/340/diffs?diff_id=14618&start_sha=6798e66eb5a2144d7ae801164aaa2d4e33eae868)

**Comment by kinow** [comment]
added 1 commit

<ul><li>2a90bf4d - Create decorators to meta-programmatically create the</li></ul>

[Compare with previous version](/gitlab/es/autosubmit/-/merge_requests/340/diffs?diff_id=14626&start_sha=61a89ac1aa35f3ecf17ad3884a57b6d005ea89b5)

**Comment by kinow** [comment]
marked the checklist item **use properties to define parameters** as completed

**Comment by kinow** [comment]
marked the checklist item **generate the three sections with variables for jobs, platforms, and projects, automatically** as completed

**Comment by kinow** [comment]
Productive day! The automated documentation part is working for me. I reviewed the Sphinx formatting (things like VARIABLE are now displayed as `VARIABLE`), fixed some typos, added variables that were missing, and hooked Sphinx with the values created with the Python decorators.

Some values are computed on runtime, and cannot be moved to a `@property` at the moment. I think that could be refactored to have a `Job` object with less logic in its functions (i.e. instead of a long function that computes the parameters, isolate the logic of each parameter in `@property`). But that will be for another issue.

Next is to go through the templates in `autosubmit4-config-parser`. Find where these are used in Autosubmit (probably somewhere in the `expid` logic), and process the YAML file, augmenting it with the same text from the Variables page.

**Comment by kinow** [comment]
What is better, we can preview the documentation for this pull request :slight_smile: (after #878)

https://autosubmit--340.org.readthedocs.build/en/340/userguide/variables.html

It is missing some extra variables I created with a second decorator. I will investigate why later (it works on my local environment).

![Screen_Shot_2023-05-22_at_17.40.59-fullpage](https://earth.bsc.es/gitlab/es/autosubmit/uploads/3737bb63a66701ec756fbbc4f574633e/Screen_Shot_2023-05-22_at_17.40.59-fullpage.png)

**Comment by kinow** [comment]
Oh yeah, other changes in this merge request:

- Variables are now all in alphabetical order (it was hard to keep the previous order with the automation, although not impossible).
- All variables are caps-locks/upper case (before some had mixed case).
- The variable description always has the first letter in upper case, and ends with a period.
- Added some example syntax on how the variables can be used in the template scripts (preparing for #952).

**Comment by kinow** [comment]
>Next is to go through the templates in `autosubmit4-config-parser`. Find where these are used in Autosubmit (probably somewhere in the `expid` logic), and process the YAML file, augmenting it with the same text from the Variables page.

AS configuration is copied from the templates at `generate_as_config`: https://earth.bsc.es/gitlab/es/autosubmit/-/blob/9592607b231bb0e6e5a0f68ebf97d343dbc6f041/autosubmit/autosubmit.py#L1042

**Comment by kinow** [comment]
added 1 commit

<ul><li>5bcc3722 - Augment the copied/generated Autosubmit configuration with the comments for...</li></ul>

[Compare with previous version](/gitlab/es/autosubmit/-/merge_requests/340/diffs?diff_id=14644&start_sha=2a90bf4d2abeb555c73f93aacb1febc5bdcb8c04)

**Comment by kinow** [comment]
`Tworks!

<details>
<summary>snippet used for testing - for posteriority</summary>

```python
# noinspection PyUnresolvedReferences
from autosubmit.job.job import Job
from autosubmit.helpers.parameters import PARAMETERS

from typing import Dict, List, Tuple, Union

from ruamel.yaml import YAML

import sys


def test1():
    origin = '/home/bdepaula/Development/python/workspace/autosubmit4-config-parser/autosubmitconfigparser/' \
             'config/files/local-minimal.yml'

    def add_comments_to_yaml(yaml_data, parameters, /, keys=None):
        """A recursive generator that visits every leaf node and yields the flatten parameter."""
        if keys is None:
            keys = []
        if isinstance(yaml_data, dict):
            for key, value in yaml_data.items():
                if isinstance(value, dict):
                    add_comments_to_yaml(value, parameters, [*keys, key])
                else:
                    parameter_key = '.'.join([*keys, key]).upper()
                    if parameter_key in parameters:
                        comment = parameters[parameter_key]
                        yaml_data.yaml_set_comment_before_after_key(key, before=comment, indent=yaml_data.lc.col)

    def recurse_into_parameters(parameters: Dict[str, Union[Dict, List, str]], keys=None) -> Tuple[str, str]:
        """Recurse into the ``PARAMETERS`` dictionary, and emits a dictionary.

        The key in the dictionary is the flattened parameter key/ID, and the value
        is the parameter documentation.

        :param parameters: Global parameters dictionary.
        :param keys: For recursion, the accumulated keys.
        :return: A dictionary with the
        """
        if keys is None:
            keys = []
        if isinstance(parameters, dict):
            for key, value in parameters.items():
                if isinstance(value, dict):
                    yield from recurse_into_parameters(value, [*keys, key])
                else:
                    key = key.upper()
                    # Here's the reason why ``recurse_into_yaml`` and ``recurse_into_parameters``
                    # are not one single ``recurse_into_dict`` function. The parameters have some
                    # keys that contain ``${PARENT}.key`` as that is how they are displayed in
                    # the Sphinx docs. So we need to detect it and handle it. p.s. We also know
                    # the max-length of the parameters dict is 2! See the ``autosubmit.helpers.parameters``
                    # module for more.
                    if not key.startswith(f'{keys[0]}.'):
                        yield '.'.join([*keys, key]).upper(), value
                    else:
                        yield key, value

    with open(origin) as f:
        parameter_comments = dict(recurse_into_parameters(PARAMETERS))

        # data = yaml.round_trip_load(f, preserve_quotes=True)
        yaml = YAML(typ='rt')
        data = yaml.load(f)
        add_comments_to_yaml(data, parameter_comments)
        yaml.dump(data, sys.stdout)

```
</details>

The current code creates an experiment with the following comments (most generated automatically from the code commetns):

**Exp**

```yaml
DEFAULT:
  # Job experiment ID.
  EXPID: "a008"
  # Default HPC platform name.
  HPCARCH: "local"
EXPERIMENT:
  # List of start dates
  DATELIST: '20000101'
  # List of members.
  MEMBERS: fc0
  # Unit of the chunk size. Can be hour, day, month, or year.
  CHUNKSIZEUNIT: month
  # Size of each chunk.
  CHUNKSIZE: '4'
  # Number of chunks of the experiment.
  NUMCHUNKS: '2'
  CHUNKINI: ''
  # Calendar used for the experiment. Can be standard or noleap.
  CALENDAR: standard
PROJECT:
  # Type of the project.
  PROJECT_TYPE: none
  # Folder to hold the project sources.
  PROJECT_DESTINATION: ''
GIT:
  PROJECT_ORIGIN: ''
  PROJECT_BRANCH: ''
  PROJECT_COMMIT: ''
  PROJECT_SUBMODULES: ''
  FETCH_SINGLE_BRANCH: true
SVN:
  PROJECT_URL: ''
  PROJECT_REVISION: ''
LOCAL:
  PROJECT_PATH: ''
PROJECT_FILES:
  FILE_PROJECT_CONF: ''
  FILE_JOBS_CONF: ''
  JOB_SCRIPTS_TYPE: ''
RERUN:
  RERUN: false
  RERUN_JOBLIST: ''
```

**autosubmit**

```yaml
CONFIG:
  # Current version of Autosubmit.
  AUTOSUBMIT_VERSION: "4.0.0b"
  # Maximum number of jobs permitted in the waiting status.
  MAXWAITINGJOBS: 20
  # Total number of jobs in the workflow.
  TOTALJOBS: 20
  SAFETYSLEEPTIME: 10
  RETRIALS: 0
#wrappers:
#  wrapper_sim:
#    TYPE: "vertical"
#    JOBS_IN_WRAPPER: "SIM"
MAIL:
  NOTIFICATIONS: False
  TO:
STORAGE:
  TYPE: pkl
  COPY_REMOTE_LOGS: true
```

These values match 100% what's in the Python code, and what is also in the generated Sphinx HTML docs (as this one also uses the code as source).
