### ISSUE TITLE
Avoid & as a char of a filename - [merged]

### ISSUE THREAD

**Issue by kinow** [BSC-ES/autosubmit#1965]
In GitLab by @dbeltrankyl on Aug 26, 2024, 09:05

_Merges 4.1.11-Vertical-cyclic -> master_

Hello @kinow , @edgano 

Closes #1287

There is a bug when a filename is written with &; this happens for vertical-mixed wrappers, so I've changed it to _, and now it works. 

Not sure how to write a pytest for it, but if we include a vertical-mixed testcase when we implement the regression tests, we should cover it as it was crashing the create command ( and send_command)

https://earth.bsc.es/gitlab/es/autosubmit/-/blob/master/autosubmit/job/job_packages.py#L57

Changing `return "&".join(jobs_in_wrapper)`

for

`return "_".join(jobs_in_wrapper)`

works

How to test:

1- Master branch, with an experiment generated with -dm and marenostrum5 platform, and a jobs.yml configured like this: 

```yaml
  SIM:
    SCRIPT: |
      echo sim.sh
    RUNNING: chunk
    PROCESSORS: 4
    DEPENDENCIES:
      PP-1:
    wallclock: 00:10
  PP:
    SCRIPT: |
      echo sim.sh
    RUNNING: chunk
    PROCESSORS: 4
    DEPENDENCIES:
      SIM:
    wallclock: 00:10
WRAPPERS:
  WRAPPER_V:
    TYPE: "vertical"
    JOBS_IN_WRAPPER: "SIM PP"
    MIN_WRAPPED: 2
    MAX_WRAPPED: 16
```

Try to plot an experiment.

2- With this branch, try the same 

Correct filename(this branch): a002_ASThread_SIM_PP_17246553097434_4_6.cmd*

Wrong filename(master): 'a002_ASThread_SIM&PP_17246558988328_4_6.cmd'*

As you can see, it appears '' that makes AS crash.
