### ISSUE TITLE
Gl 1421+1423 splits - [merged]

### ISSUE THREAD

**Issue by kinow** [BSC-ES/autosubmit#1988]
In GitLab by @dbeltrankyl on Oct 23, 2024, 14:51

_Merges gl-1421-Splits-chunksize -> master_

Hello @kinow , fyi @franra9 

This merge request means to fix the #1421 and #1423 issues. 

General:

* Added recipes folder in the test. These are complete yml files in case we need them in the future or/and to write how-to recipes docs in the future 

For #1421:

I'm not sure what the issue was, I believe that in the tests I did that day it also happened to me but it doesn't happen anymore with the rebased master or what I tested today. 

So Basically, If you uncomment the Splitsize: 1

```yaml
EXPERIMENT:
  DATELIST: 20221101
  MEMBERS: fc0
  CHUNKSIZEUNIT: month
  #SPLITSIZEUNIT: day
  CHUNKSIZE: 2
  NUMCHUNKS: 1
  #SPLITSIZE: 1 # <----
  SPLITPOLICY: flexible
  CHUNKINI: ''
  CALENDAR: standard
PROJECT:
  PROJECT_TYPE: 'none'
PLATFORMS:
  debug:
    type: ps
    host: localhost
JOBS:
  APP:
    SCRIPT: |
        echo "Chunk start date: %CHUNK_START_DATE%"
        echo "Chunk end date: %CHUNK_END_DATE%"
        echo "Split start date: %SPLIT_START_DATE%"
        echo "Split end date: %SPLIT_END_DATE%"
        echo "Split size: %SPLIT_SIZE%"
        echo "Split number: %SPLIT_NUMBER%"
        echo "Chunk size: %CHUNK_SIZE%"
    DEPENDENCIES:
      APP:
        SPLITS_FROM:
          ALL:
            SPLITS_TO: previous
    running: chunk
    SPLITS: auto
  DN:
    SCRIPT: |
      echo "Chunk start date: %CHUNK_START_DATE%"
      echo "Chunk end date: %CHUNK_END_DATE%"
      echo "Split start date: %SPLIT_START_DATE%"
      echo "Split end date: %SPLIT_END_DATE%"
      echo "Split size: %SPLIT_SIZE%"
      echo "Split number: %SPLIT_NUMBER%"
      echo "Chunk size: %CHUNK_SIZE%"
    CHECK: True
    DEPENDENCIES:
      DN:
        SPLITS_FROM:
          ALL:
            SPLITS_TO: previous
      APP:
        SPLITS_FROM:
          ALL: # You want to set all the DN jobs to depend on the last APP split, otherwise the DN would be need to be tuned one by one.
            SPLITS_TO: "%JOBS.APP.SPLITS%"
    SPLITS: auto
    running: chunk
```

The result is the expected:

![Seminar_001_14_34_27](https://earth.bsc.es/gitlab/es/autosubmit/uploads/5662854ebbc971ea4e6fb736f15bed49/Seminar_001_14_34_27.png)

I only found that the default split size value is wrong. It is now always one if not specified instead of taking the chunksize value

For #1423: 

This is a funny one.

The one you posted does not work. Instead, it relies on the natural dependencies code as the split_from: 0 is not understood by Autosubmit. But also, the dependency that you should add doesn't work either ( without this fix )

Currently, you have this: 

```yaml
  DN:
    DEPENDENCIES:
      APP-1:
        SPLITS_FROM:
          0: 
            SPLITS_TO: "auto"
      DN:
        SPLITS_FROM:
          ALL:
            SPLITS_TO: previous
      REMOTE_SETUP:
      SIM:
        STATUS: RUNNING
```

And you reported that this doesn't work:

```yaml
  DN:
    DEPENDENCIES:
      APP-1:
        SPLITS_FROM:
          1: 
            SPLITS_TO: "auto"
      DN:
        SPLITS_FROM:
          ALL:
            SPLITS_TO: previous
      REMOTE_SETUP:
      SIM:
        STATUS: RUNNING
```

But in fact, it is working. However, that is not what you wanted to achieve, as with this, you're not setting the rest of the DN dependencies that can lead to weird graphs.

Also, there was another issue: the "auto" keyword was always being applied to the auto of the current chunk. However, you don't want that in that case; you want to obtain the value of the APP-1 that is different from the current_app. To fix it, I wrote a new function.

So why did your example work? 

```yaml
  DN:
    DEPENDENCIES:
      APP-1:
        SPLITS_FROM:
          0: 
            SPLITS_TO: "auto"
      DN:
        SPLITS_FROM:
          ALL:
            SPLITS_TO: previous
      REMOTE_SETUP:
      SIM:
      
```

Which in that specific workflow seems to work, is the same as put

```yaml
  DN:
    DEPENDENCIES:
      APP-1:
      DN:
        SPLITS_FROM:
          ALL:
            SPLITS_TO: previous
      REMOTE_SETUP:
      SIM:
        Status: Running
```

Because Autosubmit does not understand filter 0, the Autosubmit code jumps to the "natural" dependencies function.

But what you actually wanted to do is:

```yaml
  DN:
    DEPENDENCIES:
      APP-1:
        SPLITS_FROM:
          ALL: # You want to set all the DN jobs to depend on the last APP split. Otherwise, the DN would need to be tuned one by one.
            SPLITS_TO: "auto"
      DN:
        SPLITS_FROM:
          ALL:
            SPLITS_TO: previous
      REMOTE_SETUP:
      SIM:
        Status: Running
```
Simplified workflow: 

![Seminar_001_14_47_56](https://earth.bsc.es/gitlab/es/autosubmit/uploads/cd8d5faa8f44fe683c50bc9dc244f13b/Seminar_001_14_47_56.png)

Additionally, the autosubmit inspect now shows the template paths as the result of the command.

**Comment by kinow** [comment]
In GitLab by @dbeltrankyl on Oct 23, 2024, 14:51

requested review from @kinow

**Comment by kinow** [comment]
In GitLab by @franra9 on Oct 23, 2024, 17:40

Thanks @dbeltrankyl for working on it !

Tell me if you want me to double-check any of the configurations you posted above.

![image](https://earth.bsc.es/gitlab/es/autosubmit/uploads/50682c1722c6cc417ec1bb3d21923f80/image.png) this plot is what I was looking after! :smile:

Apologies if any of the issues I posted were due to Splits missusage from my side :sweat_smile:  I tried to follow all documentation and issues I found regarding them.

**Comment by kinow** [comment]
Hi @dbeltrankyl , I'm messing around with a few different configuration settings, looking at the graph produced, and got one that looks a bit awkward.

```yaml
EXPERIMENT:
   DATELIST: 20221101 #Startdate
   MEMBERS: fc0
   CHUNKSIZEUNIT: month
   SPLITSIZEUNIT: day
   CHUNKSIZE: 2
   #SPLITSIZE: 1
   SPLITPOLICY: flexible
   NUMCHUNKS: 2
   CALENDAR: standard
JOBS:
  A_A_A:
    FILE: chunk_info.sh
    RUNNING: chunk
  B_B_B:
    FILE: chunk_info.sh
    RUNNING: chunk
    DEPENDENCIES:
      A_A_A-1:
      B_B_B:
        SPLITS_FROM:
          ALL:
            SPLITS_TO: previous
    SPLITS: auto
```

It looks like that results in `B_B_B` chunk `1` being created with all its chunks. Then the first `A_A_A` is created with chunk `1`, and `B_B_B` chunk `2` and splits have a dependency on it. Finally, `A_A_A` chunk `2` has no dependency to anything at all.

With the configuration above, shouldn't we have `A_A_A` running per chunk, with `B_B_B` running per chunk with a dependency to the previous `A_A_A`, and also with splits chained, that automatically adjust to the chunk calendar, i.e. something like `A_A_A` chunk `1`, that triggers `B_B_B` chunk `2`, and then `A_A_A` chunk `2`, and no `B_B_B` chunk `2` as there was no previous `A_A_A`?

This is the plot with the SPLITS_FROM and SPLITS_TO filters, and splits auto.

![image](https://earth.bsc.es/gitlab/es/autosubmit/uploads/77a9b581a578d737a5ee9d1c718adaa9/image.png)

And this is the plot if I remove the splits auto and splits_from/to.

```yaml
JOBS:
  A_A_A:
    FILE: chunk_info.sh
    RUNNING: chunk
  B_B_B:
    FILE: chunk_info.sh
    RUNNING: chunk
    DEPENDENCIES:
      A_A_A-1:
```

![image](https://earth.bsc.es/gitlab/es/autosubmit/uploads/4202ebd3248b092bb316e7a915639ffa/image.png)

It looks like enabling the splits is causing the chunk-level dependencies to behave differently, but I am no sure if that's intentional? There are a few other tests that I am planning to try, but I will leave it here for now.

I tested the fix for #1421 and that seems to be fixed here. With monthly chunks, and 2 chunks-size, I got the correct number of splits-day, 61 and 29 for nov-dec, and jan-feb. :clap: Great job on that! Will continue testing after you have time to look into this.

Thank you!

**Comment by kinow** [comment]
In GitLab by @dbeltrankyl on Oct 30, 2024, 14:46

Thanks for the deep review @kinow ! 

I'll try to have a look between today and tomorrow,

About the release of 4.1.11 I think I should also take a look at #1443 ( and merge !506 assigned to Irene )  before releasing it

**Comment by kinow** [comment]
In GitLab by @dbeltrankyl on Oct 31, 2024, 08:22

added 10 commits

<ul><li>6af2be72...b6a70717 - 6 commits from branch <code>master</code></li><li>b5f7c6b4 - (wip) splits</li><li>d2ad5ed3 - Added recipes to test</li><li>84d5f656 - Added normalize_auto_keyword function</li><li>7c28903d - Merge remote-tracking branch &#39;origin/gl-1421-Splits-chunksize&#39; into gl-1421-Splits-chunksize</li></ul>

[Compare with previous version](/gitlab/es/autosubmit/-/merge_requests/500/diffs?diff_id=34409&start_sha=6af2be728530cb9bb6457353b092af6a79a030c0)

**Comment by kinow** [comment]
In GitLab by @dbeltrankyl on Oct 31, 2024, 08:24

added 1 commit

<ul><li>db2e75ce - Moved file from (rebased) master to the correct folder</li></ul>

[Compare with previous version](/gitlab/es/autosubmit/-/merge_requests/500/diffs?diff_id=34410&start_sha=7c28903d157fb2cb2d9c503b87248dcdba225b81)

**Comment by kinow** [comment]
In GitLab by @dbeltrankyl on Oct 31, 2024, 08:44

Hello @kinow 

I believe that graph is correctly produced, 

```yaml
JOBS:
  A_A_A:
    FILE: chunk_info.sh
    RUNNING: chunk
  B_B_B:
    FILE: chunk_info.sh
    RUNNING: chunk
    DEPENDENCIES:
      A_A_A-1:
      B_B_B:
        SPLITS_FROM:
          ALL:
            SPLITS_TO: previous
    SPLITS: 2 # or auto doesn't matter
```

You're telling to: 

* B_B_B chunk 1_X splits to depend on A_A_A chunk 0, which doesn't exist ( as it should) 
* B_B_B chunk 2_X splits to depend on A_A_A chunk 1, that it does it
* A_A_A chunk 2 remains without dependencies because there is no B_B_B chunk 3

You can add the flag: 

    DELETE_WHEN_EDGELESS: true

To avoid nomad chunks:

![Seminar_001_08_43_34](https://earth.bsc.es/gitlab/es/autosubmit/uploads/2bbfae6941176a3a30365fdda4f91dc3/Seminar_001_08_43_34.png)

Edit: And Autosubmit was always calculated the dependencies like that

**Comment by kinow** [comment]
The issue, I think, is that without the splits and without `DELETE_WHEN_EDGELESS`, the chunk dependency brings only 

![image](https://earth.bsc.es/gitlab/es/autosubmit/uploads/976a2e5ba3776273c40961b39cc3a4a6/image.png)

With the given start date, and 2 chunks, `A_A_A` should have the chunk number 1 and number 2. And since `B_B_B` has a dependency on `A_A_A-1`, then the `B_B_B` for chunks `A_A_A` number 0 and number 1 should be created. We exclude number 0 as it doesn't exist, and we should really have just one `B_B_B`, as is the case without splits.

Then, if you have a split dependency in `B_B_B`, I thought that shouldn't override the chunk dependency (i.e. the chunk did not exist without splits, adding splits should not forcefully add it to the graph?)

**Comment by kinow** [comment]
In GitLab by @dbeltrankyl on Oct 31, 2024, 09:34

Hmm, I see your point, but it is not like the split is adding it.

They're not showing up because the job has no dependencies and is not considered a ROOT job ( job without DEPENDENCIES: key set)

You can fine-tune the `DELETE_WHEN_EDGELESS: true` to TRUE/FALSE ( Default values: "true" when it is not "root" false when it is root)

Let's see a more complete example: 

```yaml
EXPERIMENT:
   DATELIST: 20221101 #Startdate
   MEMBERS: fc0
   CHUNKSIZEUNIT: month
   SPLITSIZEUNIT: day
   CHUNKSIZE: 2
   #SPLITSIZE: 1
   SPLITPOLICY: flexible
   NUMCHUNKS: 2
   CALENDAR: standard
JOBS:
  ROOT_JOB:
    SCRIPT: |
      echo "Running"
    running: chunk
  A_A_A:
    FILE: chunk_info.sh
    RUNNING: chunk
  B_B_B:
    FILE: chunk_info.sh
    RUNNING: chunk
    DEPENDENCIES:
      A_A_A-1:
  POST:
    FiLE: chunk_info.sh
    RUNNING: once
    DEPENDENCIES:
      B_B_B:
      A_A_A:
```

![Seminar_001_09_33_54](https://earth.bsc.es/gitlab/es/autosubmit/uploads/629b9d700cfc4bf595b921c128eff7cc/Seminar_001_09_33_54.png)

So, it is not the splits the source of that behaviour is the DELETE_WHEN_EDGELESS value.

Edit: Usually a chunk is not defined at the "start" of the workflow like in the example we're doing with the A_A_A job
