### ISSUE TITLE
Job metrics retrieval

### ISSUE THREAD

**Issue by LuiggiTenorioK** [BSC-ES/autosubmit#2031]
**Purpose**: Give the user instant access to user-defined job metrics they want to track when a job finishes in the workflow

**Description**: As discussed in https://github.com/BSC-ES/autosubmit-api/issues/75, the idea is to give the users a way to retrieve metrics that are calculated during the execution of their workflow. In this line, the API should give the interface for the user and Autosubmit should handle the transfer of the files from remote to local.

Document with some of the metrics: https://docs.google.com/document/d/12yWDwXsohf4G4MPeP6e3Eil4ZL-YeIN71dBcoWRliEg/edit

### Requirements

- Autosubmit should get the output file specification from the YAML files
- Autosubmit should get the metric depending on the selector that the user defines (directly from a text file or JSON with a key selector)
- Autosubmit should store the metric from the output file in the DDBB
- Autosubmit should read and store when the job finishes

### Acceptance Criteria
 
- Autosubmit correctly identifies the output files, their paths, and how to read the metric value
- The metric in the DDBB should be the one expected by the user-defined specification
- The metric should be updated once the job finishes
 
Related issue: https://github.com/BSC-ES/autosubmit-api/issues/75

**Comment by LuiggiTenorioK** [comment]
@mcastril I updated the requirements and acceptance criteria based on what we discussed last Thursday. Feel free to modify it or confirm that we can close the scope of this new feature.

**Comment by LuiggiTenorioK** [comment]
Following the possible design, here is an example of the user flow:

The user will have to define their metrics in the `JOBS` section like this:

```yaml
JOBS:
  SETUP:
    METRICS:
      - NAME: model
        PATH: /remote_folder/model.txt
  SIM:
    METRICS:
      - NAME: custom_metric_1
        PATH: /remote_folder/metrics.json
        SELECTOR:
          TYPE: JSON   # Default is TEXT
          KEY: METRIC_1
      - NAME: custom_metric_2
        PATH: /remote_folder/metrics.json
        SELECTOR:
          TYPE: JSON
          KEY: MISCS.METRIC_2
```

Then, it will be expected that once the jobs are finished the `/remote_folder/` will have 2 files:

`model.txt`, e.g.:

```
ICON
```

`metrics.json`, e.g.:

```json
{
  "METRIC_1": "HIGH",
  "MISC": {
    "METRIC_2": 640.28
  }
}
```

Later, the DDBB table should look like this:

| job_name  | metric_name |metric_value |
| ------------- | ------------- | ------------- |
| <job_name_prefix>_SETUP | model | ICON | 
| <job_name_prefix>_SIM  | custom_metric_1 | HIGH  |
| <job_name_prefix>_SIM  | custom_metric_2 | 640.28  |


At this point, it might be feasible to add the `run_id` in the column to versioning the metrics by run, since that information could be available in the retrieval.

**Comment by LuiggiTenorioK** [comment]
Some disadvantages of the approach described above are:

- Users will have to define one by one the metrics they want to track
- Only allows fixed file names. For traceability users might want to add additional information in the filenames like timestamps e.g. `metrics_2025_01_12T18_54_30.txt` which is not allowed.
- Greater risk of failing when reading the files due to malformed content (especially reading JSONs), or miswritten paths/filenames

I think we can simplify the metric specification by just asking for the path:

```yaml
JOBS:
  SIM:
    METRICS_DIR: /remote/sim_metrics/
```

Then, metrics will be searched inside those paths with their job names appended i.e. `/remote/sim_metrics/%JOBNAME%/` where each file is a metric where the filename is the name of the metric and the content is the value.

Example:

```bash
$ ls /remote/sim_metrics/%JOBNAME%/
metric1.txt         metric2.out

$ cat /remote/sim_metrics/%JOBNAME%/metric1.txt
value1

$ cat /remote/sim_metrics/%JOBNAME%/metric2.out
value2
```

Later, the DDBB table should look like this:

| job_name  | metric_name |metric_value |
| ------------- | ------------- | ------------- |
| <job_name_prefix>_SIM | metric1.txt | value1 | 
| <job_name_prefix>_SIM  | metric2.out | value2  |


Also, @kinow suggested to, instead of asking the path, use a subdir of the %HPCROOTDIR% where the remote logs are located which is a good alternative :+1:
