### ISSUE TITLE
CURRENT_ variables are not substituted in the conf/metadata/experiment_data.yml file

### ISSUE THREAD

**Issue by kinow** [BSC-ES/autosubmit#2053]
Hi,

When I have this job:

```yaml
JOBS:
  TRANSFER:
    PLATFORM: MARENOSTRUM4
    PROCESSORS: 1
    CHECK: on_submission
    FILE: test.sh
    JOB_EXPID: "%DEFAULT.EXPID%"
```

running `autosubmit create -v -np a005` gives me:

```yaml
JOBS:
  TRANSFER:
    PLATFORM: MARENOSTRUM4
    PROCESSORS: 1
    CHECK: on_submission
    FILE: test.sh
    JOB_EXPID: a005
    DEPENDENCIES: {}
    ADDITIONAL_FILES: []
```

Now, if instead of using a normal variable like `DEFAULT.EXPID` I use a `CURRENT_` variable, the behaviour is different:

```yaml
PLATFORMS:
  MARENOSTRUM4:
    TYPE: slurm
    HOST: mn1.bsc.es
    PROJECT: bsc32
    USER: bruno
    QUEUE: debug
    SCRATCH_DIR: /gpfs/scratch
    ADD_PROJECT_TO_HOST: false
    MAX_WALLCLOCK: 48:00
    TEMP_DIR: ''
    MAX_PROCESSORS: 128
JOBS:
  TRANSFER:
    PLATFORM: MARENOSTRUM4
    PROCESSORS: 1
    CHECK: on_submission
    FILE: test.sh
    JOB_EXPID: "%CURRENT_QUEUE%"
```

If I run `autosubmit create` my `conf/metadata/experiment_data.yml` contains:

```yaml
PLATFORMS:
  MARENOSTRUM4:
    TYPE: slurm
    HOST: mn1.bsc.es
    PROJECT: bsc32
    USER: bruno
    QUEUE: debug
    SCRATCH_DIR: /gpfs/scratch
    ADD_PROJECT_TO_HOST: false
    MAX_WALLCLOCK: 48:00
    TEMP_DIR: ''
    MAX_PROCESSORS: 128
JOBS:
  TRANSFER:
    PLATFORM: MARENOSTRUM4
    PROCESSORS: 1
    CHECK: on_submission
    FILE: test.sh
    JOB_EXPID: '%CURRENT_QUEUE%'
    DEPENDENCIES: {}
    ADDITIONAL_FILES: []
```

So the `CURRENT_QUEUE` was not substituted in the unified YAML file. If I run `autosubmit report -all`, the variable appears as available and with the expected value.

```yaml
JOBS.TRANSFER.CURRENT_TYPE=slurm
JOBS.TRANSFER.CURRENT_HOST=mn1.bsc.es
JOBS.TRANSFER.CURRENT_PROJECT=bsc32
JOBS.TRANSFER.CURRENT_USER=bruno
JOBS.TRANSFER.CURRENT_QUEUE=debug
```

And what's more, is that if I run `autosubmit inspect` I get the correct Bash values:

```bash
# File: a005_TRANSFER.cmd
...
...
###################
# Autosubmit job
###################

#!/bin/bash

echo "debug"
```

Where my template had only:

```bash
#!/bin/bash

echo "%CURRENT_QUEUE%"
```

I think this is a blocker (or at least not very convenient) for @mandresm 's issue about provenance [in the workflow configuration files](https://earth.bsc.es/gitlab/digital-twins/de_340-2/workflow/-/issues/591), and also makes it more difficult when troubleshooting issues with `CURRENT_` values. For instance, I saw this last Friday, when I was looking for a `CURRENT_` value that @franra9 may have used in one of his experiments (I needed the value, the amount of memory, not the variable), and for a second I didn't understand if the memory was being set or not, if I needed to update something in main.

Now it's clear that this is a bug and you can just look at the platform for the memory, but took me a moment to realize it was Autosubmit that was not writing the substituted values in the `experiment_data.yml`. I think this could be because the `CURRENT_` values are resolved in Autosubmit code #2052 , and not in the AS config parser -- cc @mcastril
