### ISSUE TITLE
Weak dependencies in slpits

### ISSUE THREAD

**Issue by franra9** [BSC-ES/autosubmit#2067]
Hi @dbeltrankyl @kinow ,

I tried adding weak dependencies between jobs in the applciations workflow following the instructions of the user guide (https://autosubmit.readthedocs.io/en/latest/userguide/defining_workflows/index.html#dependencies-rework) but I get the following error:

```
 [CRITICAL] A not admitted configuration or error in the code has happened: invalid literal for int() with base 10: '1?'.
 Please report it to Autosubmit Developers through Git
```

It complains about having the "?" symbol. The example in the documentation do not contain SPLITS, so I wonder if the issue comes from the fact of using the feature with SPLITS.

The section with problems is:

```
  DN:
    CHECK: on_submission
    DEPENDENCIES:
      APP_ENERGY_ONSHORE?-1:
        SPLITS_FROM:
          '0':
            SPLITS_TO: '%JOBS.DN.SPLITS%'
```

The autosubmit version I used is 4.1.10

In AS 4.1.12-dev-2b553f0

I get a different error:

```
 [CRITICAL] Unexpected error: 'APP_ENERGY_ONSHORE?'.
 Please report it to Autosubmit Developers through Git
```

The full joblist I use is this one:

```
JOBS:
  APP:
    CHECK: on_submission
    DEPENDENCIES: OPA
    FILE: templates/application.sh
    FOR:
      DEPENDENCIES:
      - APP_ENERGY_ONSHORE?:
          SPLITS_FROM:
            all:
              SPLITS_TO: previous
        OPA_ENERGY_ONSHORE:
          SPLITS_FROM:
            all:
              SPLITS_TO: "[1:%JOBS.DN.SPLITS%]*\\1"
      - APP_WILDFIRES_WISE?:
          SPLITS_FROM:
            all:
              SPLITS_TO: previous
        OPA_WILDFIRES_WISE:
          SPLITS_FROM:
            all:
              SPLITS_TO: "[1:%JOBS.DN.SPLITS%]*\\1"
      NAME: '%RUN.APP_NAMES%'
      SPLITS: '[''auto'', ''auto'']'
    NODES: 1
    PARTITION: '%CURRENT_APP_PARTITION%'
    PLATFORM: '%DEFAULT.HPCARCH%'
    PROCESSORS: 1
    RUNNING: chunk
    TASKS: 1
    THREADS: 1
    WALLCLOCK: 00:20
  DN:
    CHECK: on_submission
    DEPENDENCIES:
      APP_ENERGY_ONSHORE?-1:
        SPLITS_FROM:
          '0':
            SPLITS_TO: '%JOBS.DN.SPLITS%'
      APP_WILDFIRES_WISE?-1:
        SPLITS_FROM:
          '0':
            SPLITS_TO: '%JOBS.DN.SPLITS%'
      DN:
        SPLITS_FROM:
          all:
            SPLITS_TO: previous
      SIM:
        STATUS: RUNNING
    FILE: templates/dn.sh,conf/mother_request.yml
    PLATFORM: '%DEFAULT.HPCARCH%-login'
    RUNNING: chunk
    SPLITS: auto
    TOTALJOBS: 1
    WALLCLOCK: 02:00
  INI:
    CHECK: on_submission
    DEPENDENCIES: REMOTE_SETUP
    FILE: templates/ini.sh
    PLATFORM: '%DEFAULT.HPCARCH%-login'
    RUNNING: member
    WALLCLOCK: 00:30
  LOCAL_SETUP:
    CHECK: on_submission
    FILE: templates/local_setup.sh
    PLATFORM: LOCAL
    RUNNING: once
  OPA:
    CHECK: on_submission
    CUSTOM_DIRECTIVES: '%CURRENT_OPA_CUSTOM_DIRECTIVES%'
    DEPENDENCIES: null
    EXCLUSIVE: '%CURRENT_OPA_EXCLUSIVE%'
    FILE: templates/opa.sh
    FOR:
      DEPENDENCIES:
      - DN:
          SPLITS_FROM:
            all:
              SPLITS_TO: "[1:%JOBS.DN.SPLITS%]*\\1"
        OPA_ENERGY_ONSHORE:
          SPLITS_FROM:
            all:
              SPLITS_TO: previous
      - DN:
          SPLITS_FROM:
            all:
              SPLITS_TO: "[1:%JOBS.DN.SPLITS%]*\\1"
        OPA_WILDFIRES_WISE:
          SPLITS_FROM:
            all:
              SPLITS_TO: previous
      NAME: '%RUN.OPA_NAMES%'
      SPLITS: '[''auto'', ''auto'']'
    NODES: 1
    PARTITION: '%CURRENT_APP_PARTITION%'
    PLATFORM: '%DEFAULT.HPCARCH%'
    PROCESSORS: '%CURRENT_OPA_PROCESSORS%'
    RUNNING: chunk
    TASKS: 1
    THREADS: 1
  REMOTE_SETUP:
    CHECK: on_submission
    DEPENDENCIES: SYNCHRONIZE
    FILE: templates/remote_setup.sh,templates/fdb/confignative.yaml,templates/fdb/configlatlon.yaml,templates/fdb/config.yaml
    PLATFORM: '%DEFAULT.HPCARCH%-login'
    RUNNING: once
    WALLCLOCK: 02:00
  SIM:
    CHECK: on_submission
    DEPENDENCIES: INI SIM-1 DQC_BASIC-10
    FILE: templates/sim_%MODEL.NAME%.sh
    PLATFORM: '%DEFAULT.HPCARCH%'
    WALLCLOCK: 02:00
    running: chunk
  SYNCHRONIZE:
    CHECK: on_submission
    DEPENDENCIES: LOCAL_SETUP
    FILE: templates/synchronize.sh
    PLATFORM: LOCAL
    RUNNING: once
RUN:
  APP_NAMES:
  - ENERGY_ONSHORE
  - WILDFIRES_WISE
  OPA_NAMES:
  - energy_onshore
  - wildfires_wise
```

**Comment by dbeltrankyl** [comment]
Hello @franra9 

The "?" (re)support is not there yet. 

```yaml
  DN:
    CHECK: on_submission
    DEPENDENCIES:
      APP_ENERGY_ONSHORE?-1:
        SPLITS_FROM:
          '0':
            SPLITS_TO: '%JOBS.DN.SPLITS%'
```

Should be 

```yaml
  DN:
    CHECK: on_submission
    DEPENDENCIES:
      APP_ENERGY_ONSHORE-1:
        SPLITS_FROM:
          '0':
            SPLITS_TO: '%JOBS.DN.SPLITS%'
            STATUS: FAILED
```

If I remember well ( which is hard because there is a branch with a rework) that is equivalent to weak dependencies

Rework should be coming at some point https://github.com/BSC-ES/autosubmit/issues/1316

**Comment by dbeltrankyl** [comment]
Docs are here https://autosubmit.readthedocs.io/en/latest/userguide/defining_workflows/index.html#start-conditions

**Comment by franra9** [comment]
Thanks @dbeltrankyl ! I will have a look at the solution you suggested :)

**Comment by dbeltrankyl** [comment]
@franra9 

Right now it does this: 

Examples:

```yaml
JOBS:
  A:
    SCRIPT: |
      echo "Hello World"
    PLATFORM: LOCAL
    RUNNING: once
  C:
    SCRIPT: |
      echo "hello world"
    DEPENDENCIES:
      A:
        STATUS: "FAILED"
  B:
    SCRIPT: |
      echo "hello world"
    DEPENDENCIES:
      A:
```

![Image](https://github.com/user-attachments/assets/b9156421-6f31-47ab-a51a-bd80b9ccb0a5)


```yaml
JOBS:
  A:
    SCRIPT: |
      decho "Hello World" # forced typo
    PLATFORM: LOCAL
    RUNNING: once
  C:
    SCRIPT: |
      echo "hello world"
    DEPENDENCIES:
      A:
        STATUS: "FAILED"
  B:
    SCRIPT: |
      echo "hello world"
    DEPENDENCIES:
      A:
```

![Image](https://github.com/user-attachments/assets/dfecb25d-1a9a-487a-a1ec-b78037ca8b0d)

Is this what do you want?
