### ISSUE TITLE
DEFAULT.DESCRIPTION

### ISSUE THREAD

**Issue by vlap** [BSC-ES/autosubmit#2068]
It would be nice to be able to access the description of the experiment, created by `autosubmit expid -H HPCname -d Description`. Right now the other two variables (DEFAULT.EXPID and DEFAULT.HPCARCH) are available, but not the description DEFAULT.DESCRIPTION

It is not a critical issue but more of a "quality of life" issue. The context of my request is that in auto-ecearth4 there is a diagnostic workflow which creates some plots and then uploads them to the portal by creating an issue, e.g. https://dev.ec-earth.org/issues/1390 . This issue needs a description and I create it manually.  It would be nice to put %DEFAULT.DESCRIPTION% there instead
```yaml
- base.context:
    scratch: %CURRENT_ROOTDIR%
    experiment:
      id: %DEFAULT.EXPID%
      description: %DEFAULT.DESCRIPTION%
```

@dbeltrankyl @kinow @mandresm
