### ISSUE TITLE
Plotting arrow with wrong colors and dependency

### ISSUE THREAD

**Issue by VindeeR** [BSC-ES/autosubmit#2076]
I was trying to generate graphs in sequence with the command

> `autosubmit create XXXX`

for different jobs with different dependency levels like exemplified below and as we go back and forth between the files the plot keep the previous dependency styling.
If the previous plot has a complex dependency based on the status and current one doesn't the plot will show some arrows with the color of the previous status, and vice-versa, if the previous is not status dependent and the following one is the generation comes without the dependency for the first plot.

[Graph1_no_dependecy_right.pdf](https://github.com/user-attachments/files/18506702/Graph1_no_dependecy_right.pdf)
[Graph1_no_dependency_wrong.pdf](https://github.com/user-attachments/files/18506705/Graph1_no_dependency_wrong.pdf)
[Graph2_dependency_wrong.pdf](https://github.com/user-attachments/files/18506704/Graph2_dependency_wrong.pdf)
[Graph2_dependency_right.pdf](https://github.com/user-attachments/files/18506703/Graph2_dependency_right.pdf)

expdef_xxxx.yml
```
DEFAULT:
  # Job experiment ID.
  EXPID: expid
  # Default HPC platform name.
  HPCARCH: "local"
EXPERIMENT:
  # List of start dates
  DATELIST: '19900101'
  # List of members.
  MEMBERS: Member1 Member2
  # Unit of the chunk size. Can be hour, day, month, or year.
  CHUNKSIZEUNIT: month
  # Size of each chunk.
  CHUNKSIZE: '4'
  # Number of chunks of the experiment.
  NUMCHUNKS: '5'
  CHUNKINI: ''
  # Calendar used for the experiment. Can be standard or noleap.
  CALENDAR: standard
PROJECT:
  # Type of the project.
  PROJECT_TYPE: none
  # Folder to hold the project sources.
  PROJECT_DESTINATION: ''
GIT:
  PROJECT_ORIGIN: ''
  PROJECT_BRANCH: ''
  PROJECT_COMMIT: ''
  PROJECT_SUBMODULES: ''
  FETCH_SINGLE_BRANCH: true
SVN:
  PROJECT_URL: ''
  PROJECT_REVISION: ''
LOCAL:
  PROJECT_PATH: ''
PROJECT_FILES:
  FILE_PROJECT_CONF: ''
  FILE_JOBS_CONF: ''
  JOB_SCRIPTS_TYPE: ''
RERUN:
  RERUN: false
  RERUN_JOBLIST: ''
```

Jobs_xxxx.yml
```
JOBS:
  ini:
      FILE: ini.sh
      RUNNING: member

  sim:
      FILE: sim.sh
      DEPENDENCIES: ini sim-1
      RUNNING: chunk

  postprocess:
      FILE: postprocess.sh
      DEPENDENCIES: sim
      RUNNING: chunk

  combine:
      FILE: combine.sh
      DEPENDENCIES: postprocess
      RUNNING: member
```
```
JOBS:
  ini:
      FILE: ini.sh
      RUNNING: member

  sim:
      FILE: sim.sh
      DEPENDENCIES: ini sim-1
      RUNNING: chunk

  postprocess:
      FILE: postprocess.sh
      DEPENDENCIES:
          SIM:
              STATUS: "RUNNING"
      RUNNING: chunk
```
