### ISSUE TITLE
SPLIT_LAST parameter commented out in the code

### ISSUE THREAD

**Issue by ainagaya** [BSC-ES/autosubmit#2099]
Hi @kinow @dbeltrankyl ,

I was checking the available variables with calendar information about the splits. I wanted a variable that tells me if that SPLIT is the last split of the chunk or not. For that, what I tried was SPLIT_LAST (even though I thought that maybe it meant the last split of the whole simulation, meaning the last SPLIT of the last CHUNK), but I saw that the block of code defining that variable is commented out: https://github.com/search?q=repo%3ABSC-ES%2Fautosubmit+SPLIT_LAST&type=code

I think that is a nice parameter that could be (re)included.

Thanks!

**Comment by dbeltrankyl** [comment]
Uh, not sure why it is commented. 

You can do this meanwhile:

[ %SPLIT% -eq %SPLITSIZE% ] (%SPLIT% starts in 1 )

**Comment by ainagaya** [comment]
Hi @dbeltrankyl , thanks! But this gives the equivalent to SPLIT_FIRST, doesn't it?

**Comment by dbeltrankyl** [comment]
I think, it is the last, no? 

Having a job_date_member_chunk configured like this
```bash
job_date_member_chunk_1
..
job_date_member_chunk_31
%JOBS.JOB.SPLITS%: 31 ( or auto) 
```

template:
```
%SPLITS% == 31 ( or auto ) # This is what you define, it returns the value as it was set 
%SPLITSIZE% == 31  # this the actual definitive  size

%SPLIT% == 1 for job_date_member_chunk_1

%SPLIT% == 31 for job_date_member_chunk_31

[ 1 -eq 31 ] # job_date_member_chunk_1
 don't enter

[ 31 -eq 31 ] # job_date_member_chunk_31
 enter
```

**Comment by ainagaya** [comment]
In my case I have this values for the latest split:

```
SPLIT=${27:-31}
SPLITSIZE=${28:-1}
```

That comes from:

```
JOBS:
  TRANSFER:
    FILE: templates/transfer.sh
    PLATFORM: lumi-transfer
    DEPENDENCIES: SIM TRANSFER-1
    RUNNING: chunk
    SPLITS: 'auto'
EXPERIMENT:
  SPLITSIZEUNIT: day # default CHUNKSIZEUNIT-1 (month-1 == day)
  # Split size. NUMERIC: 4, 6, 12
  SPLITSIZE: 2
  # Split policy. STRING: flexible, strict
  SPLITPOLICY: flexible
```

So I think that since I'm using `auto` the splitsize varies among splits.

What I want to know is if the current split is the latest in that chunk or not.
