### ISSUE TITLE
Memory leak in 4.1.11 and 4.1.12

### ISSUE THREAD

**Issue by kinow** [BSC-ES/autosubmit#2160]
Breaking down the issue into a sub issue so that's easier to distinguish which PRs are fixing what.

See parent issue for more details.

**Comment by kinow** [comment]
The example workflow we are using:

```yaml
TEST:
  JOB: &job
    SCRIPT: sleep 2
  PLATFORM: &platform
    USER: kinow
    PROJECT: ehpc01
# mkdir -p /tmp/scratch/ehpc01/kinow/

CONFIG:
  AUTOSUBMIT_VERSION: "4.1.12"
  TOTALJOBS: 20
  MAXWAITINGJOBS: 20
DEFAULT:
  EXPID: "a034"
  HPCARCH: "MARENOSTRUM5"
EXPERIMENT:
  DATELIST: 19900101
  MEMBERS: fc0
  CHUNKSIZEUNIT: month
  SPLITSIZEUNIT: day
  CHUNKSIZE: 1
  NUMCHUNKS: 1
  CALENDAR: standard
PROJECT:
  PROJECT_TYPE: local
  PROJECT_DESTINATION: local_project
LOCAL:
  PROJECT_PATH: ~/autosubmit/project
PLATFORMS:
  MARENOSTRUM5:
    <<: *platform
    TYPE: ps
    HOST: localhost
    QUEUE: gp_debug
    SCRATCH_DIR: /tmp/scratch
    ADD_PROJECT_TO_HOST: false
    MAX_WALLCLOCK: 02:00
    TEMP_DIR: ''
    MAX_PROCESSORS: 99999
    PROCESSORS_PER_NODE: 112
  MARENOSTRUM5-login:
    <<: *platform
    TYPE: ps
    HOST: localhost
    SCRATCH_DIR: /tmp/scratch
    ADD_PROJECT_TO_HOST: false
    MAX_WALLCLOCK: 02:00
    TEMP_DIR: ''
    MAX_PROCESSORS: 99999
JOBS:
  LOCAL_SETUP:
    <<: *job
    CHECK: on_submission
    PLATFORM: LOCAL
    RUNNING: once
  SYNCHRONIZE:
    <<: *job
    CHECK: on_submission
    DEPENDENCIES:
      LOCAL_SETUP: {}
    PLATFORM: LOCAL
    RUNNING: once
  REMOTE_SETUP:
    <<: *job
    CHECK: on_submission
    DEPENDENCIES:
      SYNCHRONIZE: {}
    PLATFORM: MARENOSTRUM5-login
    RUNNING: once
    WALLCLOCK: 02:00
  APP_ENERGY_ONSHORE:
    <<: *job
    CHECK: on_submission
    DEPENDENCIES:
      APP_ENERGY_ONSHORE:
        SPLITS_FROM:
          ALL:
            SPLITS_TO: previous
      OPA_ENERGY_ONSHORE:
        SPLITS_FROM:
          ALL:
            SPLITS_TO: '[1:auto]*\1'
    NODES: 1
    PARTITION: '%CURRENT_APP_PARTITION%'
    PLATFORM: MARENOSTRUM5
    PROCESSORS: 1
    RUNNING: chunk
    TASKS: 1
    THREADS: 1
    WALLCLOCK: 00:20
    NAME: ENERGY_ONSHORE
    SPLITS: auto
  DN:
    <<: *job
    CHECK: on_submission
    DEPENDENCIES:
      APP_ENERGY_ONSHORE-1:
        SPLITS_FROM:
          '0':
            SPLITS_TO: auto
      DN:
        SPLITS_FROM:
          ALL:
            SPLITS_TO: previous
      REMOTE_SETUP:
        STATUS: COMPLETED
        ANY_FINAL_STATUS_IS_VALID: false
    PLATFORM: MARENOSTRUM5-login
    RUNNING: chunk
    SPLITS: auto
    TOTALJOBS: 1
    WALLCLOCK: 02:00
  OPA_ENERGY_ONSHORE:
    <<: *job
    CHECK: on_submission
    CUSTOM_DIRECTIVES: '%CURRENT_OPA_CUSTOM_DIRECTIVES%'
    DEPENDENCIES:
      DN:
        SPLITS_FROM:
          ALL:
            SPLITS_TO: '[1:auto]*\1'
      OPA_ENERGY_ONSHORE:
        SPLITS_FROM:
          ALL:
            SPLITS_TO: previous
    EXCLUSIVE: '%CURRENT_OPA_EXCLUSIVE%'
    NODES: 1
    PARTITION: '%CURRENT_APP_PARTITION%'
    PLATFORM: MARENOSTRUM5
    PROCESSORS: '1'
    RUNNING: chunk
    TASKS: 1
    THREADS: 1
    NAME: energy_onshore
    SPLITS: auto
```
