### ISSUE TITLE
Port AS3 -> AS4 for eMONARCH training data generation

### ISSUE THREAD

**Issue by DMathas** [BSC-ES/autosubmit#2184]
Hi, I have a AS4 autoMONARCH question regarding our eMONARCH training data generation workflow, which I today ported from AS3 to AS4. I am currently working in expid `a8oq` (AS4) and the corresponding (fully functional) AS3 workflow is in expid `a8mi`. The question is about the dependencies, they don't show up correctly when checking the AS GUI:

```
 PERTURB_EMIS:
    FILE: templates/hermes/eMONARCH_perturb_emissions.sh
    DEPENDENCIES: REMOTE_COMPILE PERTURB_EMIS-5
    RUNNING: chunk
    WALLCLOCK: 00:20
    PROCESSORS: '48'
    NOTIFY_ON: FAILED
    RETRIALS: '2'
```

So PERTURB_EMIS depends on REMOTE_COMPILE, but in GUI doesnt look right see screenshot:
How can I fix this?

![Image](https://github.com/user-attachments/assets/3250cfd1-e1eb-4b7b-8ac5-b9af5c8c8ed3)

![Image](https://github.com/user-attachments/assets/76dc90b1-1277-411f-8377-b079cc80a2bc)

When I use `6` chunks it looks like this, seems from the AS GUI that the `PERTURB_EMIS` jobs would never get launched:

![Image](https://github.com/user-attachments/assets/a2ffe5da-3956-42bb-9aba-a138b093cfef)

Could you help me figure out how to solve this issue with the AS4 AutoMONARCH dependencies? Thanks in advance! I was discussing this on the autoMonarch gitlab before.

**Comment by dbeltrankyl** [comment]
Hello @DMathas 

One question: Does the GUI and autosubmit monitor plots the same graph? Or do you see that the GUI has a wrong dependency set?

If that's not the case

Since this is Auto-monarch and @agarci3 recently tried to port monarch to AS3->AS4, he can help you better or encountered the same issue.

If not, I'll take a look when I can ( currently a bit busy)

**Comment by agarci3** [comment]
Hi @dbeltrankyl ,

Yes, this has happened to me as well, but only when `DELAY` is present and the job depends on itself. Example:

```
  LOCAL_SEND_EMISSIONS:
    FILE: templates/hermes/local_send_emissions.sh
    PLATFORM: marenostrum_archive
    DEPENDENCIES: LOCAL_SETUP LOCAL_SEND_EMISSIONS-1
    RUNNING: chunk
    SYNCHRONIZE: member
    DELAY: '1'
    NOTIFY_ON: FAILED
```

For example, in this case, `LOCAL_SEND_EMISSIONS_2` has no dependencies in AS4, whereas in AS3, `LOCAL_SEND_EMISSIONS_2` depended on `LOCAL_SETUP`.

I also saw a similar case from @DMathas  the other day, where the issue seemed to be related to dependencies different than -1.

**Comment by DMathas** [comment]
@dbeltrankyl thanks! With autosubmit monitor you mean `autosubmit check <expid>`?

**Comment by dbeltrankyl** [comment]
Hello @DMathas 

There is indeed a bug, I don't have time to fix it soon, but I have a workaround

You can modify PERTURB_EMIS and SIM like this:

```yaml
  PERTURB_EMIS:
    FILE: templates/hermes/eMONARCH_perturb_emissions.sh
    DEPENDENCIES:
      REMOTE_COMPILE:
      PERTURB_EMIS:
        chunks_from:
          1,2,3,4,5:
            chunks_to: None
          6:
            chunks_to: 1

    RUNNING: chunk
    WALLCLOCK: 00:20
    PROCESSORS: '48'
    NOTIFY_ON: FAILED
    RETRIALS: '2'
  SIM:
    FILE: templates/05b_sim.sh
    DEPENDENCIES:
      PERTURB_EMIS: 
        chunks_from:
          1:
            chunks_to: 1
      SIM-1: 
    RUNNING: chunk
    PROCESSORS: '264'
    WALLCLOCK: 00:40
    NOTIFY_ON: FAILED COMPLETED
````

> @dbeltrankyl thanks! With autosubmit monitor you mean autosubmit check <expid>?

No, I mean `autosubmit monitor $expid`. That should give you a workflow

![Image](https://github.com/user-attachments/assets/67eac108-606d-4044-9a64-e53e7130c264)

**Comment by DMathas** [comment]
Hi @dbeltrankyl thanks a lot I'll try this right away!

**Comment by kinow** [comment]
Note, from today's AS meeting, to be tested (cc @dbeltrankyl),

```
chunks_from:
          [1-5]:
```

**Comment by dbeltrankyl** [comment]
I'll soon start working on this so the proper syntax ( the one that was working on AS3) works again.

**Comment by agarci3** [comment]
Hi,

I tried to reproduce the workflow that AS3 would generate (running 10 chunks), but I have not been able to.

My closest attempt was this:

```
PERTURB_EMIS:
    FILE: templates/hermes/eMONARCH_perturb_emissions.sh
    DEPENDENCIES:
        PERTURB_EMIS:
            chunks_from:
                "[1:5]":
                    chunks_to: None
        REMOTE_COMPILE:
        PERTURB_EMIS-5:
    RUNNING: chunk
    WALLCLOCK: 00:20
    PROCESSORS: '48'
    NOTIFY_ON: FAILED
    RETRIALS: '2'
```
