### ISSUE TITLE
Detect and prevent recursive variable definitions

### ISSUE THREAD

**Issue by ainagaya** [BSC-ES/autosubmit#2195]
Hi!

While defining a workflow configuration, I accidentally introduced a recursive variable definition, which caused autosubmit create to take excessive time and eventually get killed due to high memory usage (don't worry about the Autosubmit VM from DestinE, I'm doing this in my laptop's autosubmit installation). It would be helpful if the config parser could detect such cases and raise an error.

A recursive variable definition might look like this:  

```yaml
VAR:
  VAR1: %VAR.VAR1%
```

Of course, this wasn't intentional. I was refactoring my configuration to improve flexibility:

#### Previous config

```yaml
MODEL:
  NAME: neuralgcm
  CHECKPOINT: "/gpfs/scratch/bsc32/bsc032376/tfm/models_v1_stochastic_1_4_deg.pkl"
  ICS: era5
  SIMULATION: test
EXPERIMENT:
  MEMBERS: "1"
```

#### Updated config

```yaml
MODEL:
  NAME: neuralgcm
  CHECKPOINT_PATH: /gpfs/scratch/bsc32/bsc032376/tfm
  CHECKPOINT_NAME: models_v1_stochastic_1_4_deg.pkl
  CHECKPOINT: "%MODEL.CHECKPOINT_PATH%/%MODEL.CHECKPOINT_NAME%"
  ICS: era5
  SIMULATION: test
EXPERIMENT:
  MEMBERS: "1"
```

At some point, I mistakenly defined:

```yaml
MODEL:
  CHECKPOINT: %MODEL.CHECKPOINT%/%MODEL.CHECKPOINT_NAME%
```

`autosubmit create` was running indefinitely and eventually killed due to excessive memory usage.
The issue was not obvious initially, since no error message pointed to the recursive reference, so I would suggest that:

- Autosubmit should detect and report recursive variable references.
- Ideally, it should raise an explicit error indicating which variable is causing the loop.
