### ISSUE TITLE
TASKS_PER_NODE not working (tasks/ntasks)

### ISSUE THREAD

**Issue by lauherrero** [BSC-ES/autosubmit#2196]
Hi @dbeltrankyl @kinow 

The job variable TASKS_PER_NODE is not working for me. I found it on the [documentation page](https://autosubmit.readthedocs.io/en/master/userguide/variables.html#job-variables). 

The job variable TASKS is working as `--ntasks-per-node`.

Is there a difference between `--tasks-per-node` and `--ntasks-per-node`?  SBATCH man page at MN5 does not define `--tasks`, `--tasks-per-node`, etc.

I am using Autosubmit version 4.1.11

Thank you very much :)

**Comment by dbeltrankyl** [comment]
Hello @lauherrero 

Hmm, this can be confusing. 

These variables are variables that you can use inside your templates. But if you're defining the TASKS, there is only a valid one that is the TASKS

So,  inside templates:

%TASK% == %TASK_PER_NODES% 

```yaml
JOBS:
  TASKS: 2 # is the correct one, this will add the $SBATCH directive.
  TASKS_PER_NODES: 2 # this will be accessible as %CURRENT_TASKS_PER_NODES%
```

Translated to 

2 == 2 

In the templates

The correct documentation site to look for this info would be https://autosubmit.readthedocs.io/en/master/userguide/configure/index.html#how-to-add-a-new-job
