### ISSUE TITLE
Wrappers in the accelerated partition of MN5

### ISSUE THREAD

**Issue by IsidreMas** [BSC-ES/autosubmit#2210]
Hello, I'm currently working on a configuration where I aim to implement an horizontal wrapper to optimize queue times in the accelerated partition of MN5 (using the acc_bsces or acc_debug queue). The relevant part of my current configuration (expid: a83d) is as follows:

```yaml

WRAPPERS:
  WRAPPER_0:
    MAX_WRAPPED: 8
    TYPE: horizontal
    JOBS_IN_WRAPPER: TUNE
    QUEUE: acc_bsces

JOBS:
  TUNE:
    CUSTOM_DIRECTIVES:
      - '#SBATCH --nodes 8'
      - '#SBATCH --gres=gpu:4'
      - '#SBATCH --exclusive'
    TASKS: 4
    CHECK: ON_SUBMISION
    DEPENDENCIES: SYNC_PROJ
    ENVIRONMENT: /gpfs/projects/bsc32/shared_conda_environments/automlenv
    FILE: templates/tune.sh
    NOTIFY_ON: FAILED COMPLETED
    PLATFORM: marenostrum5
    THREADS: 20
    PROCESSORS: 4
    QUEUE: acc_bsces
    RUNNING: once
    SPLITS: 9
    WALLCLOCK: 00:10
    NUM_TRIALS:
      - 1
      - 2
    NUM_FOLDS: 3
```

I have a couple of concerns regarding the conflicts between custom directives (e.g., explicitly setting #SBATCH --nodes 8 or #SBATCH --gres=gpu:4) and AS-managed variables when trying to accommodate a variable number of GPUs and nodes since this don't get updated with the wrapper. Should custom directives be avoided entirely in favor of AS variables, or is there a recommended method to integrate both?

What would be the best configuration practices when aiming to support wrappers that might require a variable number of GPUs and nodes—especially when using the accelerated partition?

Also, I'm setting the queue in several places and I'm not sure which one has priority (for instance in the platform configuration, the job configuration and the wrapper configuration). I'm setting it to `acc_bsces` but it is submitted to debug which is the default in the platform configuration.

I appreciate any insights or recommendations in the use of wrappers.

@dbeltrankyl @kinow

**Comment by IsidreMas** [comment]
I've reduced the number of custom directives and now the wrapper seems to agregate the resources properly

``` yaml
  TUNE:
    CUSTOM_DIRECTIVES:
    - '#SBATCH --gres=gpu:4'
    - '#SBATCH --exclusive'
    TASKS: 4
    CHECK: ON_SUBMISION
    DEPENDENCIES: SYNC_PROJ
    ENVIRONMENT: /gpfs/projects/bsc32/shared_conda_environments/automlenv
    FILE: templates/tune.sh
    NOTIFY_ON: FAILED COMPLETED
    PLATFORM: marenostrum5
    THREADS: 20
    PROCESSORS: 4
    QUEUE: acc_bsces
    RUNNING: once
    SPLITS: 9
    WALLCLOCK: 00:10
    NUM_TRIALS:
    - 1
    - 2
    NUM_FOLDS: 3
```
