### ISSUE TITLE
Document special dynamic variables ( %^VARIABLE%)

### ISSUE THREAD

**Issue by dbeltrankyl** [BSC-ES/autosubmit#2269]
This feature has been in the autosubmit config parser for a while (+1 year), but it is not documented anywhere. 

What that char does is to make the %placeholder% substitution once all the configuration is loaded. 

Fyi @ainagaya

**Comment by ainagaya** [comment]
Hi @dbeltrankyl , 

I was not sure if it was better to open a separate issue, but since its very much related, I'm posting here what we discussed. 

I tried to use this nice feature,

First attempt: https://earth.bsc.es/gitlab/digital-twins/de_340-2/workflow/-/commit/07106e790a3f44e83f46944454a48c3382ff05df

Is not getting substituted:

![Image](https://github.com/user-attachments/assets/fa6b088e-18ee-450f-b4b3-272778da925c)

The second attempt, using `^%MODEL.VERSION%` substitutes the %MODEL.VERSION% but doesn't take out the ^ and I'm not sure if it's really loading it the "last".

**Comment by dbeltrankyl** [comment]
Hello @ainagaya 

I did a quick, simple test:  (4.1.13)


```
ca.yml
var: "first"

conf.yml
aaaaa_test: "%var%"

cz.yml
var: "last"
```

aaaa_test: 

<img width="202" alt="Image" src="https://github.com/user-attachments/assets/06e9a2bd-dbcf-4fea-a3b0-a6ffd7b56242" />

```
ca.yml
var: "first"

conf.yml
aaaaa_test: "%^var%"

cz.yml
var: "last"
```

<img width="166" alt="Image" src="https://github.com/user-attachments/assets/89784d98-0eee-4550-ba48-06c22146fb83" />

So, for this case it is working 🤔

**Comment by dbeltrankyl** [comment]
It also works if the var is called

```
ca.yml
model:
  version: "first"


conf.yml
other_variable: "something"
aaaaa_test: "%other_variable%/%^model.version%/something"

cz.yml
model:
  version: "last"
```

aaaa_test: 

<img width="330" alt="Image" src="https://github.com/user-attachments/assets/59440a33-6d29-4e3c-8d87-3e0da007ec9a" />

This also works, so I'm not sure why it doesn't in your case. 

Can you provide me your expid?

**Comment by ainagaya** [comment]
Oh that's nice! My attempt was in the pipeline of the workflow, which is using v4.1.11. We need to update it (https://earth.bsc.es/gitlab/digital-twins/de_340-2/workflow/-/issues/1002) maybe with just that it happens to work. I'll let you know, thanks Dani!

**Comment by ainagaya** [comment]
Hi Dani, I tried from the VM with a "real" experiment (t049) and is not shown in the experiment data file. Maybe because is in the same "category"?

```
MODEL:
  ROOT_PATH: '%CURRENT_HPC_PROJECT_ROOT%/%CURRENT_PROJECT%/models/ifs-nemo'
  PATH: '%CURRENT_HPC_PROJECT_ROOT%/%CURRENT_PROJECT%/models/ifs-nemo/%^MODEL.VERSION%/make/%CURRENT_HPCARCH_lowercase%-cray'
  INPUTS: '%HPCROOTDIR%/git_project/dvc-cache-de340'
  COMPILE: 'False'
  VERSION: DE_CY48R1.0_climateDT_20250317
```

Running an inspect, I got:

```
[agayayav@climatedt-wf tmp]$ cat t049_19900101_fc1_1_SIM.cmd | grep MODEL_PATH
MODEL_PATH=${52:-/projappl/project_465000454/models/ifs-nemo/%^MODEL.VERSION%/make/lumi-cray}
```

**Comment by dbeltrankyl** [comment]
Let me check it

**Comment by dbeltrankyl** [comment]
modified default_models.yml

```yaml
  ROOT_PATH: "%CONFIGURATION.HPC_PROJECT_DIR%/models/%MODEL.NAME%"
  PATH: "%MODEL.ROOT_PATH%/%^MODEL.VERSION%/make/%CURRENT_HPCARCH_lowercase%-%RUN.ENVIRONMENT%"
  INPUTS: "%MODEL.ROOT_PATH%/%^MODEL.VERSION%/inidata"
  FINAL_VERSION: "%^MODEL.VERSION%"
```

Result:
```yaml
  ROOT_PATH: '%CURRENT_HPC_PROJECT_ROOT%/%CURRENT_PROJECT%/models/ifs-nemo'
  PATH: '%CURRENT_HPC_PROJECT_ROOT%/%CURRENT_PROJECT%/models/ifs-nemo/%^MODEL.VERSION%/make/%CURRENT_HPCARCH_lowercase%-cray'
  INPUTS: '%CURRENT_HPC_PROJECT_ROOT%/%CURRENT_PROJECT%/models/ifs-nemo/%^MODEL.VERSION%/inidata'
  FINAL_VERSION: DE_CY48R1.0_climateDT_20250317
```

As you can see, the final version has been modified correctly; however, the inputs and paths have not been modified.

I had this bug before with the normal substitution... so maybe the special ones don't have that bug fixed updated. 

Perhaps you can modify your SIM script and perform substitutions to obtain the correct PATH?

```
SIM receives something in the lines
  INPUTS: '%CURRENT_HPC_PROJECT_ROOT%/%CURRENT_PROJECT%/models/ifs-nemo/<placeholder>/inidata'

  VERSION: %MODEL.VERSION%
  # code sub <placeholder from input to $VERSION>

```
Meanwhile, do I fix this?
