### ISSUE TITLE
[QOL, DestinE] Setstatus improvements

### ISSUE THREAD

**Issue by dbeltrankyl** [BSC-ES/autosubmit#2279]
Hello @BSC-ES/autosubmit 

This issue is to make the `autosubmit setstatus` more manageable for operators.

In DestinE, some jobs share a prefix section name, for example, APP_, followed by the app name. 

If we add wildcards like "*" to match multiple sections, job names, etc., at once, it will be easier for them to set it to wait, suspend, etc. jobs.

Example:
 
```yaml
JOBS:
  JOB:
    APP_earth:
       File: ...
       ...
     APP_air:
        FILE: ...
       ...
```
`autosubmit setstatus a000 -ft "APP_earth, APP_air" -t WAITING -s` # current way
`autosubmit setstatus a000 -ft "APP*" -t WAITING -s`  # new way
