### ISSUE TITLE
Using minimal configuration, certain blocks of configuration only applied when they are in the $expid/conf

### ISSUE THREAD

**Issue by ainagaya** [BSC-ES/autosubmit#2350]
### Description

* Autosubmit version: 4.1.14
* Machine/VM/environment name (if applicable): Autosubmit VM & Laptop
* Experiment ID (if applicable): a2ft
* Experiment tasks & log path if applicable):
  * e.g. `<EXPID>_19900101_fc0_1_<TASK_NAME>` 
  * e.g. `/appl/AS/AUTOSUBMIT_DATA/<EXPID>/tmp/ASLOGS`
  * (And any other information you may have, the more, the merrier.)

### Reproducible Example

```
autosubmit expid \
  --description "Test for FOR loops" \
  --HPC MareNostrum5 \
  --minimal_configuration \
  --git_as_conf conf/bootstrap/ \
  --git_repo https://earth.bsc.es/gitlab/digital-twins/de_340-2/workflow \
  --git_branch 537-for-in-additional-jobs
```

```
 autosubmit create a00e
```

When prompted, chose "model" and "ifs-nemo" (1, 1). Save the `main.yml` as it is. There are 3 additional jobs configured.

Resulting workflow:

![Image](https://github.com/user-attachments/assets/0bc54cce-38b1-417e-a3dd-11768b3cd5a2)

Copying this block:

```
JOB:
  FOR:
    # List of additional jobs to be run
    NAME: "%CONFIGURATION.ADDITIONAL_JOBS%"
  # This will create a variables %JOB_NAME.PATH%
  path: "%PROJDIR%/conf/additional_jobs/%NAME%.yml"
```

From proj/git_project/conf/general.yml to conf/main.yml or conf/minimal.yml

Results in the following workflow:

![Image](https://github.com/user-attachments/assets/fa9c307f-4038-4a6b-8784-7c378d0e9678)

Which is what is expected.

**Comment by ainagaya** [comment]
Hi Autosubmit team! 

I created a small repo to reproduce this issue, avoiding the "complexity" of the ClimateDT workflow (thought it might be useful). It is here: https://github.com/ainagaya/reproduce-autosubmit

I could reproduce the issue locally on my laptop with an experiment that uses the following configuration:

```
CONFIG:
  AUTOSUBMIT_VERSION: "4.1.14"
  TOTALJOBS: 20
  MAXWAITINGJOBS: 20
DEFAULT:
  EXPID: "a00i"
  HPCARCH: "local"
  #hint: use %PROJDIR% to point to the project folder (where the project is cloned)
  CUSTOM_CONFIG: "%PROJDIR%/conf/load_additional_jobs.yaml"
project:
  PROJECT_TYPE: local
  PROJECT_DESTINATION: local_project
local:
  PROJECT_PATH: "~/repos/reproduce-autosubmit/issue-2350"

CONFIGURATION:
  ADDITIONAL_JOBS:
    - add_job

      #JOB:
      #  FOR:
      #    # List of additional jobs to be run
      #    NAME: "%CONFIGURATION.ADDITIONAL_JOBS%"
      #  # This will create a variable %JOB_NAME.PATH%
      #  path: "%PROJDIR%/conf/additional_jobs/%NAME%.yaml"
```

Commenting/uncomenting the last block makes the additional job appear and disappear, even though the block is also present in the files inside the repository.

So basically to reproduce this:
- Clone the repository
- autosubmit expid -min -local -d "reproduce issue 2350"
- Use the config file above for `minimal.yml` (substitute the project path and the experiment id)
- Try enable/disable the last block and see the differences.

Thanks!!
