### ISSUE TITLE
Setstatus bug with Status filter

### ISSUE THREAD

**Issue by dbeltrankyl** [BSC-ES/autosubmit#2363]
### Description

`Setstatus -fc ` broken for jobs with "STATUS" set

> `[hidden@climate-dt a2gb]$ autosubmit setstatus -fc "[ 19900101 [ fc0 [8-16] ] ]" -t WAITING -s a2gb`

It raises: 

```
  File "/appl/AS/4.1.14/lib64/python3.9/site-packages/autosubmit/platforms/platform.py", line 673, in get_checkpoint_files
    if job.current_checkpoint_step < job.max_checkpoint_step:
```

* Autosubmit version: 4.1.14
* Machine/VM/environment name (if applicable): climate-dt
* Experiment ID (if applicable): a2gb

### Reproducible Example

Don't have one, as I didn't test it personally but this should trigger it

```yaml
# add experiment configuration (dates,chunk,members)

```
```yaml
jobs:
 joba: 
   file: whatever.sh
   running: chunk
   splits: auto
 jobb:
   file: whatever2.sh
   running: once
   dependencies: 
      joba:
        Status: "COMPLETED"
```

### Expected Behaviour

It works flawlessly. The status is changed. 

### workaround if any

Working on a workaround here 
 https://earth.bsc.es/gitlab/digital-twins/de_340-2/energy_onshore/-/issues/73#note_366557.

FYI: @franra9
