### ISSUE TITLE
Additional files won't work in one specific case

### ISSUE THREAD

**Issue by dbeltrankyl** [BSC-ES/autosubmit#2374]
### Description

Yesterday, I was debugging Autosubmit, and I found a bug that I had already tested a fix for 

https://github.com/BSC-ES/autosubmit/commit/57c48874a450a50b4598b872b31455ffb8c2b2a0

This ugly thing was not sending the `Additional file` if the platform is local ( because the delete call of the send function will overwrite it). This works well until you try to use the "PS" platform with a filesystem that shares the local filesystem

* Autosubmit version: 4.1.14
* Machine/VM/environment name (if applicable): Any machine with a shared filesystem (/esarchive per ex)
* Experiment ID (if applicable): any

### Reproducible Example

https://earth.bsc.es/gitlab/es/requests/-/issues/2906#note_367714

```yaml
JOBS:
  DOWNLOAD_hidden:
    FILE: 
      - hidden
      - hidden
    FILE_TO_DOWNLOAD: hidden
    RUNNING: chunk
    ORIGINAL_FILE_PATH: hidden
    NOTIFY_ON:
    - FAILED
    DOWNLOAD_DELAY: 2 month
    DOWNLOAD_FLAG: true
    DEPENDENCIES: {}
    PLATFORM: hub
    EXPORT: "source %ROOTDIR%/env.sh"
Platforms:
  HUB:
    TYPE: ps
    HOST: bschub03
    USER: hidden
    PROJECT: Earth
    SCRATCH_DIR: /home
    ADD_PROJECT_TO_HOST: false
    TEMP_DIR: ''
    EXCLUSIVE: 'True'
```

### Expected Behaviour

Autosubmit don't crashes
