### ISSUE TITLE
cpus-per-task automatically set to 1

### ISSUE THREAD

**Issue by dmcclainbsc** [BSC-ES/autosubmit#2380]
Hello!

### Description

We (@ainagaya and I) are trying to enable NEMO standalone again for Marc Batlle and the PREDDYCT project using [this MR](https://earth.bsc.es/gitlab/digital-twins/de_340-2/workflow/-/merge_requests/807). We expected the number of threads/cpus-per-task to be set by sim_nemo.sh but instead we are seeing it set to 1 in the SLURM header. We think this is similar to [this issue](https://github.com/BSC-ES/autosubmit/issues/1407).

* Autosubmit version: 4.1.14
* Machine/VM/environment name (if applicable): MN5
* Experiment ID (if applicable): a2h2
* Experiment tasks & log path if applicable):
  * /appl/AS/AUTOSUBMIT_DATA/a2h2/tmp/a2h2_19930101_fc0_1_SIM.cmd

### Reproducible Example

Copy experiment a2h2 and try to run it.

### Expected Behaviour

We would expect `cpus-per-task` to not be defined in the SLURM header.

**Comment by kinow** [comment]
Tested with,

```bash
$ autosubmit expid \
  --description "AS issue 2380 damien" \
  --HPC marenostrum5 \
  --minimal_configuration \
  --git_as_conf conf/bootstrap/ \
  --git_repo /home/kinow/Development/python/workspace/workflow/ \
  --git_branch 1012-iterate-on-nemo-stand-alone
```

Chose model + nemo for the Git hook prompt, and copied the `main.yaml` from a2h2.

SIM produced in experiment_data.yml:

```yaml
  SIM:
    DEPENDENCIES:
      INI: {}
      SIM-1: {}
    FILE: templates/sim_nemo.sh
    PLATFORM: MARENOSTRUM5
    WALLCLOCK: 11:00
    RUNNING: chunk
    CHECK: on_submission
    QUEUE: gp_bsces
    NODES: 125
    CUSTOM_DIRECTIVES: "['#SBATCH --exclusive', '#SBATCH -A bsc32']"
    ADDITIONAL_FILES: []
```

@dmcclainbsc , I see your `main.yml` is defining the number of nodes for `SIM`, as well as dependencies, wallclock, queue, and some custom directives. But you are not specifying the number of tasks nor processors. So these will come from the platform instead.

The default value for threads and processors in the AS code is `'1'`.  `NUMTHREADS`, `THREADS`, and `CPUS_PER_TASK` are all initialized to the value of threads (I believe there's some historical reason for the overlapping/redundancy, but I fail to remember that now).

If you want to modify that, you can modify your `SIM job config in your `main.yml`,

```
JOBS:
  SIM:
    ......
    NODES: 125
    THREADS: 8
```

Or set `THREADS` for all jobs in the platform `MARENOSTRUM5` (I think you probably don't want to do that). Give it a try and run `autosubmit inspect a2h2` to confirm the `.cmd` has the right Slurm header for your job 👍
