### ISSUE TITLE
Fix Clean_attributes() for setstatus

### ISSUE THREAD

**Issue by dbeltrankyl** [BSC-ES/autosubmit#2381]
### Description

Jobs with STATUS: set, can't use setstatus once the job is in status "COMPLETED".

 

* Autosubmit version: 4.1.14
* Machine/VM/environment name (if applicable): climate-dt
* Experiment ID (if applicable): a2g2

### Reproducible Example

```yaml
JOBS:
  job:
    ...
  job2:
    DEPENDENCIES: 
      job1:
        STATUS: "RUNNING"
```

1 ) Finish the run once
2) Try to setstatus the job2

### Expected Behaviour

Status is changed. 

### Solution

https://earth.bsc.es/gitlab/digital-twins/de_340-2/energy_onshore/-/issues/73#note_369034

I created a temporal module (4.1.15-dev0) with a quick-fix (just force these variables to be 0 if they're none) so they can setstatus. 

We should do a proper fix for 4.1.15

@franra9 cc
