### ISSUE TITLE
Dependency not working correctly

### ISSUE THREAD

**Issue by agarci3** [BSC-ES/autosubmit#2397]
Hi @dbeltrankyl 

### Description

* Autosubmit version: 4.1.14
* Machine/VM/environment name (if applicable): HUB03
* Experiment ID (if applicable): t0el

We are having issues with dependency in some workflows (t0el). There are two wrong dependencies:

- **PREPROCVAR** does not detect **PREPROCFIX** as a dependency.

- **SIM** does not detect **SIM-1** as a dependency.

### Reproducible Example

When running the create command with the current workflow of experiment t0el, the dependencies for **PREPROCVAR** and **SIM** are not set correctly.

To reproduce the same dependencies as in AS3, I made the following changes:

- Explicitly defined the dependencies for **PREPROCVAR**: 

```yml
  PREPROCVAR:
    FILE: templates/preproc_var.sh
    DEPENDENCIES:
      LOCAL_SEND_INITIAL:
      LOCAL_SEND_CHEM:
      SIM-10:
      PREPROCFIX:
        chunks_from:
          all:
            chunks_to: 1
    RUNNING: chunk
    WALLCLOCK: 01:00
    NOTIFY_ON: FAILED COMPLETED
    CUSTOM_DIRECTIVES: '["#SBATCH --exclusive"]'
```

- The jobs **HERMES_GR** and **PREPROCVAR** depended on **SIM-10**. After changing these dependencies to **CLEAN-10**, the **SIM** job correctly set the dependency on **SIM-1** (note: **SIM** depends on **HERMES_GR** and **PREPROCVAR**).

### Expected Behaviour

The dependencies were fine using AS3. The expected behavior should be the same:

- **PREPROCVAR** should detect **PREPROCFIX** as a dependency.
- The **SIM** should detect the **SIM-1**.
