### ISSUE TITLE
EXPORT job variable

### ISSUE THREAD

**Issue by lauherrero** [BSC-ES/autosubmit#2415]
### Description

* Autosubmit version: 4.1.14-conda
* Machine/VM/environment name (if applicable): HUB03 and oper01
* Experiment ID (if applicable): a9bh

Hi 😸 

I am using the EXPORT job variable, but it seems not to be working properly.  The file `/esarchive/autosubmit/a9bh/tmp/ASLOGS/submit_****.sh ` does not exist and my jobs are failing because my conda env is not activated.

My job list is:
```yml
JOBS:
  DOWNLOAD_ENAGAS_distribution:
    FILE:
      - templates/download.sh
      - templates/configuration_files/ENAGAS_distribution.yml
    PLATFORM: local
    FILE_TO_DOWNLOAD: ENAGAS_distribution
    RUNNING: chunk
    # DOWNLOAD_FLAG: "True"
    ORIGINAL_FILE_PATH: "%INPUTS.ENAGAS_DISTRIBUTION.ORIGINAL_FILE_PATH%"
    # DOWNLOAD_DELAY: "%INPUTS.ENAGAS_DISTRIBUTION.DELAY%"
    NOTIFY_ON: FAILED
    EXPORT: "source %PROJDIR%/platforms/local/env.sh"
```

and my `env.sh` looks like:
```bash
module purge
# Load modules and activate conda environment
module load Miniconda3
# shellcheck source=/dev/null
source activate base
conda deactivate
conda activate /esarchive/scratch/cpinero/conda_envs/PHENOMENA_v0.2.3

```

I don't know if this is a bug or if I am doing something wrong 🙏
