### ISSUE TITLE
Misssynchronization between SPLITS and CHUNKS calendars?

### ISSUE THREAD

**Issue by ainagaya** [BSC-ES/autosubmit#2433]
### Description

Hi Autosubmit team! 

We have an experiment with the following configuration:

```
EXPERIMENT:
  SPLITSIZEUNIT: day
  SPLITSIZE: 2
  SPLITPOLICY: flexible
  DATELIST: 19900101
  MEMBERS: fc0 fc1 fc2 fc3
  CHUNKSIZEUNIT: month
  CHUNKSIZE: 1
  NUMCHUNKS: 12
  CALENDAR: standard
JOBS:
  TRANSFER:
      FILE: templates/transfer.sh
      PLATFORM: MARENOSTRUM5-transfer
      DEPENDENCIES:
        REMOTE_SETUP: {}
      RUNNING: chunk
      RETRIALS: 10
      SPLITS: auto
      WALLCLOCK: 06:00
      NODES: 1
      PROCESSORS: 1
      TASKS: 1
      THREADS: 1
      CHECK: on_submission
      SPLITSIZE: 3
      ADDITIONAL_FILES: []
```

The splitsize that is being applied is the one under JOBS (that's OK). The problem is that for the last chunk (number 12) the last split contains days from the following year:

```
CHUNK_SECOND_TO_LAST_DATE=${25:-19901231}
SPLIT_SECOND_TO_LAST_DATE=${5:-19910102}
```

Therefore, it is attempting to transfer (in this case) data that is not in the machine.

cc @mbatllem

* Autosubmit version: 4.1.14
* Machine/VM/environment name (if applicable): CSC Autosubmit VM
* Experiment ID (if applicable): a2i3
* Experiment tasks & log path if applicable):
  * /appl/AS/AUTOSUBMIT_DATA/a2i3/tmp/LOG_a2i3/a2i3_19900101_fc1_12_11_TRANSFER.20250625104121.err

### Reproducible Example

Creating an experiment with the same configuration I have should be enough!

### Expected Behaviour

The last split should end on the last day of the last chunk, even with `flexible`. I don't know if it's something that can be fixed by using `strict`, but then I think that the overall splitting of the jobs will change.

If you have any ideas to change this behaviour in an ongoing experiment, we are happy to hear them!
