### ISSUE TITLE
Possibility to set AS variables as lowercase/uppercase

### ISSUE THREAD

**Issue by LuiggiTenorioK** [BSC-ES/autosubmit#2504]
In GitLab by @ainagaya on Jul 19, 2024, 12:34

Hi!! 

I think that it would be useful to be able to change the variables to uppercase/lowercase. For example,

```
SECTION:
  VARIABLE: "Watermelon"
```

But then, when using the variable, if in the template/other config file when it is used:

```
BASH_VARIABLE1=%SECTION.VARIABLE^^%
BASH_VARIABLE2=%SECTION.VARIABLE,,%

```
That would translate in `BASH_VARIABLE1=WATERMELON`, `BASH_VARIABLE2=watermelon`. In the templates, we can do this in bash, its true. But my usecase is more in the configuration files, for example, the bootstrap. Here we are defining some paths:

```
DEFAULT:
  CUSTOM_CONFIG:
    PRE:
      # Basic configuration: platforms, jobs and defaults
      - "%PROJDIR%/conf/platforms.yml"
      - "%PROJDIR%/conf/jobs_%RUN.WORKFLOW%.yml" 
      - "%PROJDIR%/conf/defaults_%RUN.WORKFLOW%.yml"
```

.To avoid user errors, it would be amazing to have

```
DEFAULT:
  CUSTOM_CONFIG:
    PRE:
      # Basic configuration: platforms, jobs and defaults
      - "%PROJDIR%/conf/platforms.yml"
      - "%PROJDIR%/conf/jobs_%RUN.WORKFLOW,,%.yml" 
      - "%PROJDIR%/conf/defaults_%RUN.WORKFLOW,,%.yml"
```

In that way, this would work with RUN.WORKFLOW: MODEL, Model, MoDeL, or model. Right now, if the word is not capitalized correctly, the file is not found. It also happens a lot with "true", "True" values, and others.
