### ISSUE TITLE
Autosubmit4 - Error when creating experiment

### ISSUE THREAD

**Issue by kinow** [BSC-ES/autosubmit#861]
In GitLab by @charlio86 on Aug 23, 2022, 18:26

Hi @dbeltrankyl I give you a post-vacation gift :smile: 

Here my execution commands, responses and final error:

FYI: @mcastril 

# Auto-SNES test

```shell
ssh -XY USER@ bscesautosubmit01
```

```shell
module load autosubmit/4.0.0b-foss-2015a-Python-3.7.3

autosubmit expid -H mn4 -d "auto-SNES development"
```

```
Locale C.utf8 is not found, using 'C' as fallback
Autosubmit is running with 4.0.0b0
The new experiment "a542" has been registered.
Copying config files...
Experiment registered successfully
```

```shell
cd /esarchive/autosubmit/EXPID
vi conf/expdef_EXPID.conf 
```

```yml
DeFault:
  EXPID: a542
  HPCARCH: mn4
experiment:
  DATELIST: 2017121700
  MEMBERS: 000
  CHUNKSIZEUNIT: day
  CHUNKSIZE: 1
  NUMCHUNKS: 2
  CHUNKINI: ''
  CALENDAR: standard
project:
  PROJECT_TYPE: git
  PROJECT_DESTINATION: ''
git:
  PROJECT_ORIGIN: 'https://earth.bsc.es/gitlab/es/auto-SNES.git'
  PROJECT_BRANCH: 'develop-tests'
  PROJECT_COMMIT: ''
  PROJECT_SUBMODULES: ''
  FETCH_SINGLE_BRANCH: True
...
project_files:
  FILE_PROJECT_CONF: 'conf/autosubmit/proj_nord3v2.yml'
  FILE_JOBS_CONF: 'conf/autosubmit/jobs_nord3v2.yml'
  JOB_SCRIPTS_TYPE: ''
``` 

```shell
autosubmit create EXPID -np

```

```
Locale C.utf8 is not found, using 'C' as fallback
Autosubmit is running with 4.0.0b0
Preparing .lock file to avoid multiple instances with same expid.

Checking configuration files...
platforms_a542.yml OK
jobs_a542.yml OK
wrappers OK
autosubmit_a542.yml OK
Cloning develop-tests https://earth.bsc.es/gitlab/es/auto-SNES.git into /esarchive/autosubmit/a542/proj
Cloning into 'auto-SNES'...
Username for 'https://earth.bsc.es': ctena
Password for 'https://ctena@ earth.bsc.es':
remote: Enumerating objects: 32, done.
remote: Counting objects: 100% (32/32), done.
remote: Compressing objects: 100% (21/21), done.
remote: Total 32 (delta 4), reused 0 (delta 0), pack-reused 0
Unpacking objects: 100% (32/32), done.
Checking connectivity... done.
Cloning into 'sources/SNES'...
Username for 'https://earth.bsc.es': ctena
Password for 'https://ctena@ earth.bsc.es':
remote: Enumerating objects: 265, done.
remote: Counting objects: 100% (240/240), done.
remote: Compressing objects: 100% (119/119), done.
remote: Total 265 (delta 148), reused 206 (delta 120), pack-reused 25
Receiving objects: 100% (265/265), 60.52 KiB | 28.00 KiB/s, done.
Resolving deltas: 100% (148/148), done.
Checking connectivity... done.
 [CRITICAL] unsupported operand type(s) for +: 'PosixPath' and 'str' [eCode=7070]
More info at https://autosubmit.readthedocs.io/en/latest/faq.html
```
