### ISSUE TITLE
Autosubmit generating workflow configurations for different backends

### ISSUE THREAD

**Issue by kinow** [BSC-ES/autosubmit#897]
In GitLab by @mcastril on Nov 11, 2022, 14:06

This is a follow-up to yesterday's conversation with ECMWF.

The idea is to be able to export and Autosubmit experiment configurations to other workflow systems, including higher-level representations such as PyFlow.

I have been thinking about this, and two options come to my mind:

* Direct "source to source" (or config to config) translation
  * Pros: We do not risk losing information by passing through an intermediate representation
  * Cons: Probably less re-usable
* Two-step conversion, passing through an intermediate representation such as CWL ?
  * Pros: More modular. Both steps can be developed in parallel. We could also ask for support from the target workflow experts for the second part of the conversion.
  * Cons: Complexity, may lose information if not all features are represented in the intermediate language

Any thoughts @dbeltrankyl @kinow ?

**Comment by kinow** [comment]
Thanks for creating the issue to continue the discussion from that meeting @mcastril !

It's tough to choose the best option to start with. Maybe @dbeltrankyl could start a technical evaluation of both (a few days?) to assess if both are viable, or if one is easier to achieve. I can help with the ecFlow part if needed.

I was thinking of using Autosubmit to just parse the configuration, receiving some template and preprocessing it to output the final workflow configuration, but maybe that's not doable because of re-run and other configuration that would require better integration with the target workflow backend to generate valid configuration.

Sounds like some challenge (but also extremely nerdy-fun! :nerd: !).

**Comment by kinow** [comment]
In GitLab by @mcastril on Nov 12, 2022, 17:47

> I was thinking of using Autosubmit to just parse the configuration, receiving some template and preprocessing it to output the final workflow configuration, but maybe that's not doable because of re-run and other configuration that would require better integration with the target workflow backend to generate valid configuration.

Not sure if we can translate and integrate templates too, although maybe that's the easier step. Do you think that CWL provides the necessary grammar and syntax to express any Autosubmit configuration? (given that it's the source language).

**Comment by kinow** [comment]
I think so. I didn't have time to sit down and try to replicate an Autosubmit workflow in CWL, but I believe that would be possible. I reckon it is work of 1-4 days to assess it (depending how far we want to go with a PoC/test).

**Comment by kinow** [comment]
Yesterday I spent 1-2 hours reading PyFlow docs, and installing the Python dependencies locally. It is a syntactic sugar around ecFlow. The classes of PyFlow extend/wrap ecFlow Python API classes, but adds more things like OO inheritance and composition, Python context managers, common attributes like `suite`, `parent`, etc., and overloads some operators for adding tasks to families, appending tasks to families, etc.

I found it really simple and practical, one of the best API's for designing workflows directly in Python.

Some time ago there was a similar discussion in Cylc. A language that was mentioned (Regent) was handy, but not as good as PyFlow. The examples of a possible future Cylc Python API though, are very similar to PyFlow.

- https://github.com/cylc/cylc-flow/issues/1962
- http://regent-lang.org/
- https://github.com/cylc/cylc-flow/wiki/Possible-Cylc-Futures#config-api-and-python-config-api

The Jupyter notebooks in the PyFlow docs include examples of `Host` objects. These objects generate the command for the job to run remotely (i.e. that `ECF_JOB_CMD` variable). They also have a `TroikaHost` object: https://github.com/ecmwf/pyflow/blob/51f57b3335c7c5c79c60e99483dae09f82e76037/pyflow/host.py#L945-L949

**Comment by kinow** [comment]
Finished a skeleton CWL workflow, based on the following `jobs.yml` created with AS4:

```yaml
JOBS:
  LOCAL_SETUP:
    FILE: LOCAL_SETUP.sh
    PLATFORM: LOCAL
    RUNNING: once
  REMOTE_SETUP:
    FILE: REMOTE_SETUP.sh
    DEPENDENCIES: LOCAL_SETUP
    WALLCLOCK: '00:05'
    RUNNING: once
  INI:
    FILE: INI.sh
    DEPENDENCIES: REMOTE_SETUP
    RUNNING: member
    WALLCLOCK: '00:05'
  SIM:
    FILE: SIM.sh
    DEPENDENCIES: INI
    RUNNING: chunk
    WALLCLOCK: '00:05'
  POST:
    FILE: POST.sh
    DEPENDENCIES: SIM
    RUNNING: once
    WALLCLOCK: '00:05'
  CLEAN:
    FILE: CLEAN.sh
    DEPENDENCIES: POST
    RUNNING: once
    WALLCLOCK: '00:05'
  TRANSFER:
    FILE: TRANSFER.sh
    PLATFORM: LOCAL
    DEPENDENCIES: CLEAN
    RUNNING: member
```

Here's a version in CWL (I could have used [scattering steps](https://common-workflow-languageuser-guide.readthedocs.io/en/latest/topics/workflows.html#scattering-steps) in CWL, but I suspect it won't work with SKIPPABLE and having each entry instead in the configuration would be simpler):

```yaml
cwlVersion: v1.2
class: Workflow

doc: |
  An example workflow created using Autosubmit's basic a000 workflow as
  reference. The `platform.yml` is ignored as it contains only information
  about platforms (e.g. it could be given to a tool like Troika as-is).

  `expdef.yml` and `autosubmit.yml` basically provide CWL inputs.

  `jobs.yml` contains the steps of the CWL workflow, with their dependencies.

  In CWL dependencies are specified via inputs and outputs. When task A outputs
  a value X, and task B has an input of type A/X, then the dependency A -> B
  is created in CWl.

  This is different than Autosubmit, and needs some care to guarantee the correct
  order in the workflow graph of start dates, members, chunks, etc.

requirements:
  InlineJavascriptRequirement: {}
  SchemaDefRequirement:
    types:
      - type: enum
        name: autosubmit_statuses
        label: The possible statuses of an Autosubmit task
        symbols:
          - UNKNOWN
          - COMPLETE
          - QUEUED
          - SUSPENDED
          - ABORTED
          - SUBMITTED
          - ACTIVE
  EnvVarRequirement:
    envDef:
      # N.B.: Either we flat it like this, or we have to use a convention like
      #       default_EXPID, experiment_DATELIST, git_PROJECT_ORIGIN, etc.
      EXPID: a000
      HPCARCH: local
      DATELIST: 20220401 20220402
      MEMBERS: "fc0 fc1"
      CHUNKSIZEUNIT: month
      # In CWL envVar values are strings, not ints. Could it be a problem later?
      CHUNKSIZE: '4'
      NUMCHUNKS: '2'
      CHUNKINI: ''
      CALENDAR: standard
      PROJECT_TYPE: none
      PROJECT_DESTINATION: ''
      PROJECT_ORIGIN: ''
      PROJECT_BRANCH: ''
      PROJECT_COMMIT: ''
      PROJECT_SUBMODULES: ''
      # In CWL envVar values are strings, not booleans. Could it be a problem later?
      FETCH_SINGLE_BRANCH: 'True'
      PROJECT_URL: ''
      PROJECT_REVISION: ''
      PROJECT_PATH: ''
      FILE_PROJECT_CONF: ''
      FILE_JOBS_CONF: ''
      JOB_SCRIPTS_TYPE: ''
      RERUN: 'FALSE'
      RERUN_JOBLIST: ''
inputs: []
outputs: []

steps:
  # LOCAL_SETUP
  a000_LOCAL_SETUP:
    in: []
    out: [status]
    run:
      class: Operation
      # baseCommand: echo
      # arguments: ["Hello World!"]
      inputs:
        TASK:
          type: string
          default: LOCAL_SETUP
      outputs:
        status:
          type: autosubmit_statuses
          # outputBinding:
          #   outputEval: $("COMPLETE")
  # REMOTE_SETUP
  a000_REMOTE_SETUP:
    in:
      previous_statuses:
        source: a000_LOCAL_SETUP/status
        valueFrom: |
          ${
            return [inputs['a000_LOCAL_SETUP/status']]
          }
    out: [status]
    run:
      class: Operation
      inputs:
        previous_statuses:
          type: autosubmit_statuses[]
        TASK:
          type: string
          default: REMOTE_SETUP
      outputs:
        status:
          type: autosubmit_statuses
  # INI
  a000_20220401_fc0_INI:
    in:
      previous_statuses:
        source: a000_REMOTE_SETUP/status
        valueFrom: |
          ${
            return [inputs['a000_REMOTE_SETUP/status']]
          }
    out: [status]
    run:
      class: Operation
      inputs:
        previous_statuses:
          type: autosubmit_statuses[]
        START_DATE:
          type: string
          default: 20220401
        MEMBER:
          type: string
          default: fc0
        TASK:
          type: string
          default: INI
      outputs:
        status:
          type: autosubmit_statuses
  a000_20220401_fc1_INI:
    in:
      previous_statuses:
        source: a000_REMOTE_SETUP/status
        valueFrom: |
          ${
            return [inputs['a000_REMOTE_SETUP/status']]
          }
    out: [status]
    run:
      class: Operation
      inputs:
        previous_statuses:
          type: autosubmit_statuses[]
        START_DATE:
          type: string
          default: 20220401
        MEMBER:
          type: string
          default: fc1
        TASK:
          type: string
          default: INI
      outputs:
        status:
          type: autosubmit_statuses
  a000_20220402_fc0_INI:
    in:
      previous_statuses:
        source: a000_REMOTE_SETUP/status
        valueFrom: |
          ${
            return [inputs['a000_REMOTE_SETUP/status']]
          }
    out: [status]
    run:
      class: Operation
      inputs:
        previous_statuses:
          type: autosubmit_statuses[]
        START_DATE:
          type: string
          default: 20220402
        MEMBER:
          type: string
          default: fc0
        TASK:
          type: string
          default: INI
      outputs:
        status:
          type: autosubmit_statuses
  a000_20220402_fc1_INI:
    in:
      previous_statuses:
        source: a000_REMOTE_SETUP/status
        valueFrom: |
          ${
            return [inputs['a000_REMOTE_SETUP/status']]
          }
    out: [status]
    run:
      class: Operation
      inputs:
        previous_statuses:
          type: autosubmit_statuses[]
        START_DATE:
          type: string
          default: 20220402
        MEMBER:
          type: string
          default: fc1
        TASK:
          type: string
          default: INI
      outputs:
        status:
          type: autosubmit_statuses
  # SIM
  a000_20220401_fc0_1_SIM:
    in:
      previous_statuses:
        source: a000_20220401_fc0_INI/status
        valueFrom: |
          ${
            return [inputs['a000_20220401_fc0_INI/status']]
          }
    out: [status]
    run:
      class: Operation
      inputs:
        previous_statuses:
          type: autosubmit_statuses[]
        START_DATE:
          type: string
          default: 20220401
        MEMBER:
          type: string
          default: fc0
        CHUNK:
          type: int
          default: 1
        TASK:
          type: string
          default: SIM
      outputs:
        status:
          type: autosubmit_statuses
  a000_20220401_fc1_1_SIM:
    in:
      previous_statuses:
        source: a000_20220401_fc1_INI/status
        valueFrom: |
          ${
            return [inputs['a000_20220401_fc1_INI/status']]
          }
    out: [status]
    run:
      class: Operation
      inputs:
        previous_statuses:
          type: autosubmit_statuses[]
        START_DATE:
          type: string
          default: 20220401
        MEMBER:
          type: string
          default: fc1
        CHUNK:
          type: int
          default: 1
        TASK:
          type: string
          default: SIM
      outputs:
        status:
          type: autosubmit_statuses
  a000_20220402_fc0_1_SIM:
    in:
      previous_statuses:
        source: a000_20220402_fc0_INI/status
        valueFrom: |
          ${
            return [inputs['a000_20220402_fc0_INI/status']]
          }
    out: [status]
    run:
      class: Operation
      inputs:
        previous_statuses:
          type: autosubmit_statuses[]
        START_DATE:
          type: string
          default: 20220402
        MEMBER:
          type: string
          default: fc0
        CHUNK:
          type: int
          default: 1
        TASK:
          type: string
          default: SIM
      outputs:
        status:
          type: autosubmit_statuses
  a000_20220402_fc1_1_SIM:
    in:
      previous_statuses:
        source: a000_20220402_fc1_INI/status
        valueFrom: |
          ${
            return [inputs['a000_20220402_fc1_INI/status']]
          }
    out: [status]
    run:
      class: Operation
      inputs:
        previous_statuses:
          type: autosubmit_statuses[]
        START_DATE:
          type: string
          default: 20220402
        MEMBER:
          type: string
          default: fc1
        CHUNK:
          type: int
          default: 1
        TASK:
          type: string
          default: SIM
      outputs:
        status:
          type: autosubmit_statuses
  # POST
  a000_POST:
    in:
      previous_statuses:
        source:
          - a000_20220401_fc0_1_SIM/status
          - a000_20220401_fc1_1_SIM/status
          - a000_20220402_fc0_1_SIM/status
          - a000_20220402_fc1_1_SIM/status
        valueFrom: |
          ${
            return [inputs['a000_20220401_fc0_1_SIM/status', inputs['a000_20220401_fc1_1_SIM/status', inputs['a000_20220402_fc0_1_SIM/status', inputs['a000_20220402_fc1_1_SIM/status']]
          }
    out: [status]
    run:
      class: Operation
      inputs:
        previous_statuses:
          type: autosubmit_statuses[]
        TASK:
          type: string
          default: POST
      outputs:
        status:
          type: autosubmit_statuses
  # CLEAN
  a000_CLEAN:
    in:
      previous_statuses:
        source: a000_POST/status
        valueFrom: |
          ${
            return [inputs['a000_POST/status']]
          }
    out: [status]
    run:
      class: Operation
      inputs:
        previous_statuses:
          type: autosubmit_statuses[]
        TASK:
          type: string
          default: CLEAN
      outputs:
        status:
          type: autosubmit_statuses
  # TRANSFER
  a000_20220401_fc0_TRANSFER:
    in:
      previous_statuses:
        source: a000_CLEAN/status
        valueFrom: |
          ${
            return [inputs['a000_CLEAN/status']]
          }
    out: [status]
    run:
      class: Operation
      inputs:
        previous_statuses:
          type: autosubmit_statuses[]
        START_DATE:
          type: string
          default: 20220401
        MEMBER:
          type: string
          default: fc0
        TASK:
          type: string
          default: TRANSFER
      outputs:
        status:
          type: autosubmit_statuses
  a000_20220401_fc1_TRANSFER:
    in:
      previous_statuses:
        source: a000_CLEAN/status
        valueFrom: |
          ${
            return [inputs['a000_CLEAN/status']]
          }
    out: [status]
    run:
      class: Operation
      inputs:
        previous_statuses:
          type: autosubmit_statuses[]
        START_DATE:
          type: string
          default: 20220401
        MEMBER:
          type: string
          default: fc1
        TASK:
          type: string
          default: TRANSFER
      outputs:
        status:
          type: autosubmit_statuses
  a000_20220402_fc0_TRANSFER:
    in:
      previous_statuses:
        source: a000_CLEAN/status
        valueFrom: |
          ${
            return [inputs['a000_CLEAN/status']]
          }
    out: [status]
    run:
      class: Operation
      inputs:
        previous_statuses:
          type: autosubmit_statuses[]
        START_DATE:
          type: string
          default: 20220402
        MEMBER:
          type: string
          default: fc0
        TASK:
          type: string
          default: TRANSFER
      outputs:
        status:
          type: autosubmit_statuses
  a000_20220402_fc1_TRANSFER:
    in:
      previous_statuses:
        source: a000_CLEAN/status
        valueFrom: |
          ${
            return [inputs['a000_CLEAN/status']]
          }
    out: [status]
    run:
      class: Operation
      inputs:
        previous_statuses:
          type: autosubmit_statuses[]
        START_DATE:
          type: string
          default: 20220402
        MEMBER:
          type: string
          default: fc1
        TASK:
          type: string
          default: TRANSFER
      outputs:
        status:
          type: autosubmit_statuses
```

Using `cwltool` to plot it, with `cwltool --print-dot autosubmit.cwl | dot -Tpng > /tmp/graph.png`:

![image](https://earth.bsc.es/gitlab/es/autosubmit/uploads/9692574fb2e5f7ca441f34a279075315/image.png)
