### ISSUE TITLE
Prepare Custom config experiments by adding a flag in expid

### ISSUE THREAD

**Issue by kinow** [BSC-ES/autosubmit#910]
In GitLab by @dbeltrankyl on Dec 5, 2022, 12:35

I think it would be useful to have a parameter in expid command that edits/adds the custom_conf parameter.

**Comment by kinow** [comment]
In GitLab by @mcastril on Dec 15, 2022, 14:12

Wouldn't you set it as a different command? If not, I understand that users could only change parameters when creating a new experiment.

**Comment by kinow** [comment]
In GitLab by @dbeltrankyl on Dec 15, 2022, 14:50

The users can/add change the parameter directly by adding the parameter DEFAULT.CUSTOM_CONFIG to their current configuration.

The point of adding the flag to the expid command is for generating a new/copy experiment directly with the correct parameters so the users could have their platforms linked directly without mod anything else

I can add another command that does that, but it would be useful to have what @kinow mentioned on another issue

https://earth.bsc.es/gitlab/es/autosubmit/-/issues/903#note_188912 #905 

that would work for all parameters not only this one

edit: it is already opened, forgot about it

**Comment by kinow** [comment]
In GitLab by @dbeltrankyl on Dec 16, 2022, 15:34

Hello,

While working on the new doc page, I though about a way of implementing this. 

So what I thought this would do is: 

* Add `autosubmit expid --use-project-conf <folder>  --use-user-conf <folder>` 
  * <folder> path would be optional, and by default, it would point to project/as_conf/ ( or something like that) 

* [optional] Add `autosubmit expid --git_repo <repo_path> -b <branch>` and `autosubmit expid --local_repo <repo_path>`
  * Only usable if --use-project-conf is also specified 
  * Will populate project_type and git or local parameters

The `$expid/conf` when using these parameters would be a single file containing only the strictly necessary.

I still would need to do changes to autosubmit in order to implement this.

Concretely in what Autosubmit expects before doing an `autosubmit create`. Also, I would need to change the order (if proj is empty and `PROJECT_TYPE.PROJECT` is not none) of the `autosubmit create` -> `autosubmit refresh` to `autosubmit refresh` -> `autosubmit create` otherwise, the jobs won't be generated. 

Possible contents of `$expid/conf/use_external_conf.yml `

```
CONFIG:
 AUTOSUBMIT_VERSION: 4.0.0
DEFAULT:
 EXPID : a000 
 CUSTOM_CONF: %ROOTDIR%/--use-project-conf outcome, --use-user-conf ( if specified)
PROJECT:
  PROJECT_TYPE: git or local ( default git) 
  PROJECT_DESTINATION: git_project or "TO_FILL"
git:
  PROJECT_ORIGIN: --git_repo or "TO_FILL"
  PROJECT_BRANCH: --git_repo -b  or "TO_FILL" 
  PROJECT_COMMIT: "TO_FILL"
  PROJECT_SUBMODULES: "TO_FILL"
  FETCH_SINGLE_BRANCH: True
local:
  PROJECT_PATH: "TO_FILL"
```

These parameters are necessary because before performing an `autosubmit refresh`, autosubmit won't be able to find the custom_dir I think there are no more mandatory parameters before doing an `autosubmit refresh`.

* The rest of the parameters would be in the custom_dir path
* --copy and --use_project_conf are not allowed to be used together. 

If autosubmit sees that any of the parameters have as value "TO_FILL" it will raise an critical error.

If autosubmit can't load the custom_conf dir parameters (when using this mechanism) after the refresh it will raise an critical error.

Not sure if I missed anything else to do

**Comment by kinow** [comment]
In GitLab by @dbeltrankyl on Dec 21, 2022, 14:03

mentioned in commit 1b06c786bb8aba37ba2e263215441dd1995fd835

**Comment by kinow** [comment]
In GitLab by @dbeltrankyl on Dec 21, 2022, 14:08

Hello, 

I've worked on the autosubmitconfigparser ( need to update the pip ) with the aim of presenting better documentation before I go on holiday. There is still work to do for do in this issue. 

The minimum configuration required on the `$expid/conf` before performing a `refresh` is now:

```
dbeltran@ bsces107894:~/autosubmit/a04b/conf$ ls
expdef_a04b.yml
```

Example: 

```
(base) dbeltran@ bsces107894:~/autosubmit/a04b/conf$ cat expdef_a04b.yml 
DeFault:
  EXPID: a04b
  HPCARCH: local
  CUSTOM_CONFIG: "%ROOTDIR%/proj/git_project/as_conf,/home/dbeltran/as_user_conf/platforms.yml"
project:
  PROJECT_TYPE: git
  PROJECT_DESTINATION: 'git_project'
git:
  PROJECT_ORIGIN: 'https://earth.bsc.es/gitlab/ces/auto-advanced_config_example'
  PROJECT_BRANCH: 'main'
  PROJECT_COMMIT: ''
  PROJECT_SUBMODULES: ''
  FETCH_SINGLE_BRANCH: True
```

Then the user has to do autosubmit refresh ( before performing a create, this is not yet done) 


On another topic, 

Using autosubmit migrate with distributed configuration won't work unless there is a platform_a04b.yml file in the $expid/conf I have to fix it since it has a few hardcode configurations ( per example, the user_to and project_to it expects to modify the file $expid/conf/platform_$expid.yml.

**Comment by kinow** [comment]
In GitLab by @mcastril on Jan 18, 2023, 13:33

So you can copy but still overload parameters with your user conf (platform file for example) right?

Great

**Comment by kinow** [comment]
In GitLab by @mcastril on Jan 18, 2023, 13:33

> `autosubmit create` -> `autosubmit refresh` to `autosubmit refresh` -> `autosubmit create` otherwise, the jobs won't be generated.

How did you approach this?

**Comment by kinow** [comment]
In GitLab by @dbeltrankyl on Feb 7, 2023, 15:25

> https://earth.bsc.es/gitlab/es/autosubmit/-/issues/910#note_191828

I still need to implement a flag in expdef to provide the skeleton for a distributed configuration. 

> Using autosubmit migrate with distributed configuration won't work unless there is a platform_a04b.yml file in the $expid/conf I have to fix it since it has a few hardcode configurations ( per example, the user_to and project_to it expects to modify the file $expid/conf/platform\_$expid.yml.

new issue to address this

**Comment by kinow** [comment]
In GitLab by @dbeltrankyl on Mar 2, 2023, 09:55

Hello, @franra9 , @Lerriola , @sebastianbeyer , @mandresm 

This has been added in the **devel4 module , pip v4.0.72 and tag v4.0.0b8**. 

Docs will be available later today, but in summary:

* Added -min, --minimal_config
  * Added -repo, --git_repo
  * Added -branch, --git_branch, default main
  * Added -config, --git_as_conf, relative to project root

Usage: 

`autosubmit expid -min -repo https://earth.bsc.es/gitlab/ces/auto-advanced_config_example -b main -conf as_conf -d "Test minimal conf"`

* -min: generates a minimal.yml file. 
* -repo: fills the %GIT.PROJECT_ORIGIN% parameter
* -b: fills the %GIT.PROJECT_BRANCH%
* -conf: fills the %DEFAULT.CUSTOM_CONFIG%

This will generate a new experiment that has only a file called "minimal.yml":

```
(python39) (base) dbeltran@ bsces107894:~/autosubmit/a068/conf$ cat minimal.yml 
CONFIG:
  AUTOSUBMIT_VERSION: "4.0.0b"
DEFAULT:
    EXPID: "a068"
    HPCARCH: "local"
    CUSTOM_CONFIG: "%ROOTDIR%/proj/git_project/as_conf"
PROJECT:
    PROJECT_TYPE: "git"
    PROJECT_DESTINATION: "git_project"
GIT:
    PROJECT_ORIGIN: "https://earth.bsc.es/gitlab/ces/auto-advanced_config_example"
    PROJECT_BRANCH: "main"
    PROJECT_COMMIT: ""
    PROJECT_SUBMODULES: ""
    FETCH_SINGLE_BRANCH: True
```

Then when autosubmit create is prompted, AS will read this file first. 

A new parameter called %PROJDIR% points to $EXPID/conf/proj/PROJECT_DESTINATION, so now the "PROJECT_DESTINATION" value doesn't matter. 

CUSTOM_CONFIG:

The %DEFAULT.CUSTOM_CONFIG% parameter is used to define the location of the model/project or user files. The paths can be absolute or relative to the ``%PROJDIR%``.

It has two different syntaxes:

* *Simple* a list of paths to the model or project yaml files. This can be a file or a folder. If it is a folder, all the files inside will be loaded in a non-recursive way.
* *Advanced* a dictionary with two keys: ``PRE`` and ``POST``. The ``PRE`` key defines the files that will be loaded before the ``$EXPID/CONF`` ones. The ``POST`` key is used to define user configuration.

With the simple syntax, the outcome is the same as the advanced one, but with the ``POST`` key empty.

If a list of paths is provided, the paths will be loaded in the order they are provided and in a recursive way. This means that if there are additional ``DEFAULT.CUSTOM_CONFIG``parameters inside the files, they will also be loaded.

* Now, the advanced configuration must be done in a file that ends with "minimal.yml" inside $EXPID/conf 
* The overwrite permission has **CHANGED**, new priority is: 
  * PRE: <files or folders>
  * $EXPID/conf
  * POST: <files or folders> 

So, the PRE or simple syntax is meant to be used to load $EXPID/PROJ/ configuration files and the POST is meant to be used to load user files like platforms.yml.

So before updating the version, keep in mind these changes.

For bsc users, @franra9 , @Lerriola . You have to load the autosubmit/devel4-foss-2015a-Python-3.7.3. I didn't update the 4.0.0b one to avoid issues with your current workflow configuration, tell me when you're ready.

The main change is the override order

**Comment by kinow** [comment]
In GitLab by @dbeltrankyl on Mar 2, 2023, 09:59

Other changes, 

* $expid/conf/custom_dir is deleted
* CUSTOM_CONFIG is now available to use inside $PROJ/CONF files. The syntax is the same PRE will load files before the current one and POST after. 
* CUSTOM_CONFIG folder/files are being loaded in order following a depth -first pattern, so if one of them has a custom_config parameter, that file will be loaded before continuing with the rest of files

**Comment by kinow** [comment]
In GitLab by @sebastianbeyer on Mar 2, 2023, 14:41

Hey, good news @dbeltrankyl ! I just wanted to test this with the `-min` option, but I wanted to use a local project instead of a git one and that left me without any file in the expid directory. 

`autosubmit expid -min -H LUMI -d "testing the new CUSTOMCONF"`

`tree`

```
.
├── conf
├── pkl
├── plot
├── status
└── tmp
    ├── ASLOGS
    └── LOG_A00U

8 directories, 0 files
```

Is that intended? Seems a bit too minimal for my taste.

**Comment by kinow** [comment]
In GitLab by @dbeltrankyl on Mar 2, 2023, 14:45

Hello, did you update the autosubmitconfigparser4? it should use 1.0.1 now

**Comment by kinow** [comment]
In GitLab by @sebastianbeyer on Mar 2, 2023, 14:48

Yes: 
```
pip freeze |grep autosubmit
autosubmitconfigparser==1.0.1
```

**Comment by kinow** [comment]
In GitLab by @dbeltrankyl on Mar 2, 2023, 14:56

Oh, I see the issue, 

The pip files weren't updated, so the code can't find the new "minimal.yml" file. I need to upload a new version to solve it.

It should have this file:

/home/dbeltran/autosubmit4-config-parser/autosubmitconfigparser/config/files/expdef-minimal.yml

as $expid/conf/minimal.yml

Meanwhile, you can create it by yourself, 

```
CONFIG:
  AUTOSUBMIT_VERSION: 4.0.0b
DEFAULT:
    EXPID: ""
    HPCARCH: ""
    #ADD, note that %ROOTDIR% is an special AS_PLACEHOLDER that points to the expid folder.
    #Syntax: <model-specific_configuration_folder_path>,<user-file>,<user-file2_path>
    #hint: use %PROJDIR% to point to the project folder (where the project is cloned)
    CUSTOM_CONFIG: ""
PROJECT:
    PROJECT_TYPE: "git"
    PROJECT_DESTINATION: "git_project"
GIT:
    PROJECT_ORIGIN: ""
    PROJECT_BRANCH: ""
    PROJECT_COMMIT: ""
    PROJECT_SUBMODULES: ""
    FETCH_SINGLE_BRANCH: True
```

Btw, I only thought about the GIT option. In local, it should also work, but the minimal file doesn't have set the Local section. 

So the minimal local should be 

```
CONFIG:
  AUTOSUBMIT_VERSION: 4.0.0b
DEFAULT:
    EXPID: "YOUR_EXPID"
    HPCARCH: "local" # or other defined
    #ADD, note that %ROOTDIR% is an special AS_PLACEHOLDER that points to the expid folder.
    #Syntax: <model-specific_configuration_folder_path>,<user-file>,<user-file2_path>
    #hint: use %PROJDIR% to point to the project folder (where the project is cloned)
    CUSTOM_CONFIG: "%PROJDIR%/<path_to_files_inside_project_path"
project:
  PROJECT_TYPE: local
  PROJECT_DESTINATION: local_project

local:
  PROJECT_PATH: 'TO_FILL'

```

**Comment by kinow** [comment]
In GitLab by @sebastianbeyer on Mar 2, 2023, 15:00

I did not install via PyPI, but cloned the gitlab and then did a `pip install -e .`. not sure if that makes any difference.

**Comment by kinow** [comment]
In GitLab by @dbeltrankyl on Mar 2, 2023, 15:00

No, no difference. The issue the file is not included in the tarball uploaded to pip, not sure why it didn't upload all but I'll fix it

**Comment by kinow** [comment]
In GitLab by @sebastianbeyer on Mar 2, 2023, 15:47

It kind of works now, but I don't understand the syntax of it yet:

```
RUN:
  CONFIGURATION: test
  SIMULATION: test
  

CONFIG:
  AUTOSUBMIT_VERSION: 4.0.0b
DeFault:
  EXPID: a00u
  HPCARCH: LUMI
    #CUSTOM_CONFIG: "%ROOTDIR%/proj/proj_ifs-fesom/conf"
  CUSTOM_CONFIG:
    - "%ROOTDIR%/proj/proj_ifs-fesom/conf/simulation/%RUN.SIMULATION%.yml"
    - "%ROOTDIR%/proj/proj_ifs-fesom/conf/configuration/%RUN.CONFIGURATION%.yml"
```

This gives me `[ERROR] Trace: unhashable type: 'list'`

So, do we have to use a single comma separated string there instead, as before?

**Comment by kinow** [comment]
In GitLab by @sebastianbeyer on Mar 2, 2023, 15:53

But this one does not work either:

```
RUN:
  CONFIGURATION: test
  SIMULATION: test
  

CONFIG:
  AUTOSUBMIT_VERSION: 4.0.0b
DeFault:
  EXPID: a00u
  HPCARCH: LUMI
    #CUSTOM_CONFIG: "%ROOTDIR%/proj/proj_ifs-fesom/conf"
  CUSTOM_CONFIG: "%ROOTDOR%/proj/proj_ifs-fesom/conf,%ROOTDIR%/proj/proj_ifs-fesom/conf/simulation/%RUN.SIMULATION%.yml,%ROOTDIR%/proj/proj_ifs-fesom/conf/configuration/%RUN.CONFIGURATION%.yml"
```

I get a `KeyError: 'JOBS'` from that one.
