### ISSUE TITLE
Platform-specific variables

### ISSUE THREAD

**Issue by kinow** [BSC-ES/autosubmit#922]
In GitLab by @mandresm on Dec 19, 2022, 11:30

With ClimateDT having to be operational in multiple computers I think it's important that template scripts are as general as possible and that the platform-dependent configurations are already provided via Autosubmit, not via `if`s in the scripts.

I had an example for that need, for compiling `ifs-fesom` in RAPS I need the command `source initbm ${COMPILING_SCRIPT} SINGLE=yes FESOM=yes RAPS_SUPPORT=yes RAPSHARED=no ODB=no OOPS=no NCPUS=24` where the compiling script takes different values depending on the platform. My first approach to that was to define in the `conf/platforms.yml` the following:

```yaml
  [ ... ]
  juwels:
    [ ... ]
    RAPS_COMPILING_SCRIPT: config.intel.juwels
  lumi:
    [ ... ]
    RAPS_COMPILING_SCRIPT: config.cce.lumi
```

and then add the following in the template:
```
COMPILING_SCRIPT=%PLATFORM.RAPS_COMPILING_SCRIPT%
```

@dbeltrankyl told me that unfortunately that functionality is not yet available, and only hard-coded variables can be accessed from the different platform sections. I think it would be a very nice feature to have, what do you think?
