### ISSUE TITLE
Custom executable relative to project folder

### ISSUE THREAD

**Issue by kinow** [BSC-ES/autosubmit#967]
In GitLab by @orioltinto on Mar 7, 2023, 11:26

Hello @dbeltrankyl and @kinow,

I'm trying to use a custom executable for the jobs that is relative to the project.
The idea would be:

```yaml
JOBS:
  CREATE_ENVIRONMENT:
    FILE: create_environment.sh
    RUNNING: once
  USE_ENVIRONMENT:
    FILE: use_environment.py
    RUNNING: once
    DEPENDENCIES: VENV_CREATE
    TYPE: python
    EXECUTABLE: {HPCROOTDIR}/virtual_environment/bin/python3

```

Is there a way of using autosubmit variables in the configuration files or do you know another another way of achieving the same?

Cheers,
Oriol

**Comment by kinow** [comment]
In GitLab by @dbeltrankyl on Mar 7, 2023, 11:29

Hello @orioltinto ,

```yaml
JOBS:
  CREATE_ENVIRONMENT:
    FILE: create_environment.sh
    RUNNING: once
  USE_ENVIRONMENT:
    FILE: use_environment.py
    RUNNING: once
    DEPENDENCIES: VENV_CREATE
    TYPE: python
    EXECUTABLE: "%HPCROOTDIR%/virtual_environment/bin/python3"
```

This should work with the lastest tag

or:



```yaml
JOBS:
  CREATE_ENVIRONMENT:
    FILE: create_environment.sh
    RUNNING: once
  USE_ENVIRONMENT:
    FILE: use_environment.py
    RUNNING: once
    DEPENDENCIES: VENV_CREATE
    TYPE: python
    EXECUTABLE: "%CURRENT_ROOTDIR%/virtual_environment/bin/python3"
```
