### ISSUE TITLE
Expanding custom variable sections in templates.

### ISSUE THREAD

**Issue by kinow** [BSC-ES/autosubmit#980]
In GitLab by @orioltinto on Mar 17, 2023, 13:45

Hello @dbeltrankyl and @kinow,

I'm trying something and maybe you can help me figure out if there's an easy way of doing it.

In my **proj.yml** I define something like:
```yaml
namelist:
        path: "%PROJDIR%/namelists/icon.namelist"

```

However if I do a template like

``` bash
namelist = "%namelist%"
namelist_path = "%namelist.path%"
```

The first part ends up not being replaced:
```bash
namelist_path = ""
namelist_path = "/home/o/Oriol.Tinto/autosubmit/a00a/proj/a00a_proj/namelists/icon.namelist"
```

Is there a way of getting the full definition of the **namelist** dictionary in the template?

**Comment by kinow** [comment]
In GitLab by @dbeltrankyl on Mar 17, 2023, 15:01

Hello @orioltinto ,

I'm afraid that it is not possible, you can not get the full section compacted in one single string

```yaml
namelist:
        path: "%PROJDIR%/namelists/icon.namelist"
        X: "value"
```

To access values in the templates would be:

```
%namelist.path%
%namelist.X%
```

If you want to obtain the name of the section, you would need to do it manually, something like

```yaml
namelist:
        name: "namelist"
        path: "%PROJDIR%/namelists/icon.namelist"
        X: "value"
```

What is your usage case? I can't think of a scenario in which this would be useful,  maybe we can implement something that can help you to archive your goal if you give us more details

**Comment by kinow** [comment]
In GitLab by @orioltinto on Mar 17, 2023, 15:12

Hi @dbeltrankyl ,

thank you for your response.

The use case that I had in mind is that I would like to enable users to modify model's namelist parameters through the **jobs.yml** file.

So for example if I have:
```yaml
namelist:
        input_nml:
            name: "a"
            format: ".nc"
            
        output_nml:
            name: "b"
            file: ".grb"
```

Then I would modify the corresponding parameters in the default namelist.

If I can get the full definition of **namelist** I can do that.

Is there a way to get something like the output of **autosubmit report xxxx -all** from the actual script?

**Comment by kinow** [comment]
In GitLab by @dbeltrankyl on Mar 17, 2023, 15:46

By default, autosubmit can already overload parameters.

The correct way of using it is with the key %DEFAULT.CUSTOM_CONFIG%.
```
DEFAULT:
    #ADD, note that %PROJDIR% is an special AS_PLACEHOLDER that points to the expid folder.
    #hint: use %PROJDIR% to point to the project folder (where the project is cloned)
    CUSTOM_CONFIG: 
     PRE: 
       - "%PROJDIR%/as_conf/common"
       - "%PROJDIR%/as_conf/mn4/namelist1.yml"
     POST: 
      - "/home/dbeltran/platforms.yml"
```

Some issues in the doc are pending to be merged, but you can also look at #958 for detailed info. 

 https://autosubmit.readthedocs.io/en/master/userguide/set_and_share_the_configuration/index.html

![Copy_of_advanced_conf__3_](https://earth.bsc.es/gitlab/es/autosubmit/uploads/b6c470e173a4ce598791c777aeb76719/Copy_of_advanced_conf__3_.jpg)


In summary:

Now Autosubmit uses a configuration based on priorities as follow:

* Can have a file named "minimal.yml" that has the lowest priority, mainly used to load project data and basic parameters
* Alters the loading order of the parameters so what is loaded last can overwrite all the other parameters. This is allowed by using CUSTOM_CONFIG.PRE and CUSTOM_CONFIG.POST. 
* The $expid/conf **always** overwrites all folders or files specifies on custom_config.pre
* Custom_config.post is what is loaded the last. 

You can also have Custom_config defined inside folders/files loaded by the minimal.yml or $expid/conf custom_config 


For your case,  it can be more straightforward, add to the expid.yml

expid.yml
```yaml
    CUSTOM_CONFIG: 
     PRE: 
       - "%PROJDIR%/as_conf/namelist.yml"
```

%PROJDIR%/as_conf/namelist.yml:
```YAML
namelist:
        input_nml:
            name: "a"
            format: ".nc"
            
        output_nml:
            name: "b"
            file: ".grb"
```


And then the user could have another namelist or jobs.yml or whatever its name is ( autosubmit no longer look for names aside from "minimal.yml" with (for example)

$expid/conf/run.yml
```YAML
namelist:
        input_nml:
            name: "c"
```

This would leave all values intact except namelist.input_nml.name which would have the value "c"

**Comment by kinow** [comment]
In GitLab by @dbeltrankyl on Mar 17, 2023, 15:53

Also, the order inside the PRE or POST key matters as well, as it always will depth-first load the  file/folder specified and others files/folders that it contains ( if specified in another custom_config in any of these files loaded)

**Comment by kinow** [comment]
In GitLab by @orioltinto on Mar 17, 2023, 15:56

Hi @dbeltrankyl,
I have to confess that I'm a bit confused.

So I can put other configuration files inside "custom_conf" and autosubmit will read them, is that right?

However, how does it help me later knowing which variables have been set?

**Comment by kinow** [comment]
In GitLab by @dbeltrankyl on Mar 17, 2023, 16:05

> So I can put other configuration files inside "custom_conf" and autosubmit will read them, is that right?

Yes, per example, in DestinE we will have all configurations stored in our git/branch and then the user in their experiment would only have to set a "minimal.yml" to git clone the correct branch and define only the parameters that they want to change in a file located inside $expid/conf

> However, how does it help me later knowing which variables have been set?

The users would load the namelist that you defined without touching it and instead, overwrite the parameters that they want to change in a file inside their current experiment/conf, $expid/conf/run.yml per example. 

So you have two ways:

* Check their $expid/conf files, because your original configuration will be located in the $expid/proj/<path_to_conf>

*  Use `autosubmit report <expid> ` you would see the final values ( the merged configuration of all AS files loaded ). That is what the templates will see. 

There is a pending issue that we're discussing yesterday to store the previous run variables and logs as well as to add a command to check what was changed between runs of the same experiment.

**Comment by kinow** [comment]
In GitLab by @orioltinto on Mar 29, 2023, 11:34

Hi again,

we managed to achieve our target with ~~a dirty workaround~~ **yaml multiline strings**.

To summarize again, what we wanted to do is to recover a whole section of a configuration file later inside a template.

For example:

```yaml
namelist:
   input:
      type: nc
      path: "/whatever/"
   output:
      type: grb
      path: "/whatever/else/"
```

What we did is to assign the variables under namelist to the variable namelist by using the **|** operator:

```yaml
namelist: |
   input:
      type: nc
      path: "/whatever/"
   output:
      type: grb
      path: "/whatever/else/"
```

Then, if we do a template like this (I used python in this case):

```python
import yaml

namelist_string="""
%namelist%
"""

namelist = yaml.safe_load(namelist_string)

print(namelist)
```

we get something fully functional like:

```python
import yaml

namelist_string="""
input:
  type: nc
  path: "/whatever/"
output:
  type: grb
  path: "/whatever/else/"
"""

namelist = yaml.safe_load(namelist_string)

print(namelist)

```
