### ISSUE TITLE
Configuration parameter gets duplicated ( several times)

### ISSUE THREAD

**Issue by kinow** [BSC-ES/autosubmit#988]
In GitLab by @orioltinto on Mar 23, 2023, 10:49

Hello again @dbeltrankyl and @kinow,

### Autosubmit Version

4.0.75

### Summary

I have defined some parameters in a configuration file like:

```yaml
python_environment:
  # Name of the virtual environment in the remote platform experiment folder
  folder_name: python_environment
  requirements:
    # Because there's an issue with numba, for now we need to keep a specific version of numpy
    - numpy==1.23
    - enstools-compression
    # Just to try a library from a git repository.
    - git+https://gitlab.physik.uni-muenchen.de/Oriol.Tinto/otils.git
    - f90nml

```

When I do autosubmit report I get:

```

PYTHON_ENVIRONMENT.REQUIREMENTS=['numpy==1.23', 'enstools-compression', 'git+https://gitlab.physik.uni-muenchen.de/Oriol.Tinto/otils.git', 'f90nml', 'numpy==1.23', 'enstools-compression', 'git+https://gitlab.physik.uni-muenchen.de/Oriol.Tinto/otils.git', 'f90nml', 'numpy==1.23', 'enstools-compression', 'git+https://gitlab.physik.uni-muenchen.de/Oriol.Tinto/otils.git', 'f90nml', 'numpy==1.23', 'enstools-compression', 'git+https://gitlab.physik.uni-muenchen.de/Oriol.Tinto/otils.git', 'f90nml', 'numpy==1.23', 'enstools-compression', 'git+https://gitlab.physik.uni-muenchen.de/Oriol.Tinto/otils.git', 'f90nml', 'numpy==1.23', 'enstools-compression', ...
```

The same things repeated up to 195 times.

### Steps to reproduce

I guess you can reproduce the problem creating an experiment with a similar configuration and doing autosubmit report.

()
