### ISSUE TITLE
Variable replacement and case sensitivity.

### ISSUE THREAD

**Issue by kinow** [BSC-ES/autosubmit#990]
In GitLab by @orioltinto on Mar 23, 2023, 12:16

Hello @dbeltrankyl and @kinow,

### Autosubmit Version

4.0.75

### Summary

I have a configuration file that used to work with something similar to:

```
spack:
  compiler: gcc@12.2.0 # desired compiler for spack
  build_cmd: "icon-nwp@%icon.version ^%spack.compiler%"

icon:
  version: 2.6.5-nwp0

```

It stopped working until I replaced the placeholders with the upper case versions
```
spack:
  compiler: gcc@12.2.0 # desired compiler for spack
  build_cmd: "icon-nwp@%ICON.VERSION% ^%SPACK.COMPILER%"

icon:
  version: 2.6.5-nwp0


```

Was it on purpose?

()
