### ISSUE TITLE
[docs] Write docs for submodules and autosubmit refresh

### ISSUE THREAD

**Issue by kinow** [BSC-ES/autosubmit#991]
From workflows internal meeting where Aina asked about this feature.

**Comment by kinow** [comment]
In GitLab by @dbeltrankyl on Mar 23, 2023, 15:38

@ainagaya 

To specify submodules, add a parameter in any yml file ( minimal.yml when using distributed configuration)

and annotates the name of the submodule separated by a space

```
GIT:
  PROJECT_ORIGIN: ""
  PROJECT_BRANCH: ""
  PROJECT_COMMIT: ""
  PROJECT_SUBMODULES: "one two"
  FETCH_SINGLE_BRANCH: True
```

TODO: yaml list syntax
