### ISSUE TITLE
Variable replacement with multiple configuration files.

### ISSUE THREAD

**Issue by kinow** [BSC-ES/autosubmit#993]
In GitLab by @orioltinto on Mar 23, 2023, 17:31

Hello @dbeltrankyl and @kinow,

### Autosubmit Version

4.0.75

### Summary

We had an issue with placeholder replacement that can be tricky.

If we have a default configuration:

```yaml
spack:
    compiler: "gcc"
    build_cmd: "icon-nwp^%SPACK.COMPILER%"
```

and then in the configuration folder we set something like:
```yaml
spack:
    compiler: "intel"
```

If we look at the variables afterwards we get:

```yaml
SPACK.COMPILER=intel
SPACK.BUILD_CMD=icon-nwp^gcc
```

I don't know if this is intended or not but in case you don't know at least it is good to be aware of this.

()Varia

**Comment by kinow** [comment]
In GitLab by @orioltinto on Jun 29, 2023, 14:26

Hello again!

We were facing a problem that I believe is related with this one and I was wondering that maybe you know a way of doing what we are trying to do. 

Let me try to illustrate what we would like to do. Let's say that we have a jobs file in our repository configuration which is using a variable defined in a different file.

```yaml
settings:
    excluded_members: "10 11"
```

```yaml
jobs:
   job1:
      exccluded_members: "%settings.excuded_members%"
   job2:
      exccluded_members: "%settings.excuded_members%"
```

We would like to be able to modify the settings.excluded_members variable in the conf folder.
How can we do that?

**Comment by kinow** [comment]
In GitLab by @dbeltrankyl on Jun 30, 2023, 10:42

Hello @orioltinto ,

This should work already.. maybe is the same bug that in the other issue, 

Two day ago, I found a bug with placeholders but didn't uploaded it to pip because I was in a hurry and forgot, the pip has been updated

I've tested a dummy example in which I have

jobs.yml

```
  DATA_NOTIFY:
    FILE: DATA_NOTIFY.sh
    DEPENDENCIES: NOT INI
    splits : "%settings.splits%"
    RUNNING: once
    WALLCLOCK: 00:05
    DELETE_WHEN_EDGELESS: False
```

expdef.yml

```
settings:
  splits: "9"
```

This is a new file that you can encounter in your experiment folder; it is the final unified configuration, currently, it is only used to help with the debugging, and is generated with the create command It will have some more usage cases in 4.1

$expid/conf/metadata/experiment_data.yml

```
JOBS:
  DATA_NOTIFY:
    ADDITIONAL_FILES: []
    DELETE_WHEN_EDGELESS: false
    DEPENDENCIES:
      INI: {}
      NOT: {}
    FILE: DATA_NOTIFY.sh
    RUNNING: once
    SPLITS: '9'
    WALLCLOCK: 00:05
```
As you can see, the values have been unified using the pip version 4.0.80

**Comment by kinow** [comment]
In GitLab by @dbeltrankyl on Jun 30, 2023, 10:48

Also, about excluded_members, are you trying to use the Autosubmit variable? or is it not related to Autosubmit?

Because in AS 4 it doesn't exists, instead to exclude something, you should do it using the new dependencies.. example:

```yaml

JOBS:
  DATA_NOTIFY:
    DELETE_WHEN_EDGELESS: false # This will delete the task if it has no edges ( default is false ) 
    DEPENDENCIES:
      INI: 
        MEMBERS_FROM:
          10,11,12:
             DATES_TO: "none"
             MEMBERS_TO: "none"
             SPLITS_TO: "none"
             CHUNKS_TO: "none"
      NOT: {}
```

The main difference is that you can now specify it dependency per dependency and  task-to-task instead of the whole section for all dependencies ( the same goes for select_member, select_chunk, include_chunk..)

**Comment by kinow** [comment]
In GitLab by @orioltinto on Jun 30, 2023, 11:23

Hi @dbeltrankyl,

yes we were porting an old experiment that work with AS3. Thanks I'll check.

Anyway, I tried if the substitution was working for me and it is not.

Are you able to run containers? I will prepare scripts to fully reproduce both issues in a container so we know that we are running exactly the same thing.

**Comment by kinow** [comment]
In GitLab by @dbeltrankyl on Jun 30, 2023, 11:28

I didn't play with the containers, but @kinow yes.

Are you busy @kinow?  Could you take a look when Oriol provides the container?

**Comment by kinow** [comment]
In GitLab by @dbeltrankyl on Jun 30, 2023, 11:31

Btw, @orioltinto , 

Which version of autosubmitconfigparser does your venv have? 

It should be v1.0.39, maybe the issue is that it has not be updated

**Comment by kinow** [comment]
In GitLab by @orioltinto on Jun 30, 2023, 11:36

I think I have the proper one.
```
Package                Version
---------------------- --------
autosubmit             4.0.80
autosubmitconfigparser 1.0.39
```

**Comment by kinow** [comment]
Happy to give the container a try and see if I can reproduce the issue :thumbsup:

**Comment by kinow** [comment]
In GitLab by @orioltinto on Jun 30, 2023, 12:44

Well, trying to do the container script already found a couple of other issues:

First: installation fails with container python3.11 as well as ubuntu:rolling because of the dependency to an older version of numpy.

Second:
It looks like creating the experiment using `-min` and `-repo` the minimal configuration file does not set the project type to git and sets the path provided to the local path.
```
FROM python:3.9
RUN pip install autosubmit
RUN mkdir autosubmit
RUN autosubmit configure  -db /autosubmit -dbf autosubmit.db -lr /autosubmit
RUN autosubmit install
RUN autosubmit expid -min -d "debug" --git_repo "https://gitlab.physik.uni-muenchen.de/Oriol.Tinto/debug-autosubmit" 
```

```
...
project:
  # Type of the project.
  PROJECT_TYPE: local
  # Folder to hold the project sources.
  PROJECT_DESTINATION: local_project
local:
  PROJECT_PATH: "https://gitlab.physik.uni-muenchen.de/Oriol.Tinto/debug-autosubmit"
```

Any clue on what is happening here?

**Comment by kinow** [comment]
In GitLab by @dbeltrankyl on Jun 30, 2023, 12:49

> First: installation fails with container python3.11 as well as ubuntu:rolling because of the dependency to an older version of numpy.

Currently, we support Python* 3.7 and 3.9

> Second: It looks like creating the experiment using `-min` and `-repo` the minimal configuration file does not set the project type to git and sets the path provided to the local path.

Known issue, Bruno applied a fix, but I have to review the merge it will be patched next week ( https://earth.bsc.es/gitlab/es/autosubmit/-/merge_requests/347 ) 

For now, you can just fill these parameters manually after doing the expid

**Comment by kinow** [comment]
In GitLab by @orioltinto on Jun 30, 2023, 13:32

Ok, I made a temporary workaround.

So again, what I'm doing is that I have some variables defined in the repository configuraition:

```
settings:
  independent: "NOT replaced"
  dependent: "the independent variable was %settings.independent%"
```

Then I add another configuration file in the conf folder in which I replace **settings.independent**.

The result is:
```
echo "INDEPENDENT: REPLACED"
echo "DEPENDENT: the independent variable was NOT replaced"
```


The expected result is:

```
echo "INDEPENDENT: REPLACED"
echo "DEPENDENT: the independent variable was REPLACED"
```

Using the following Dockerfile and [this dummy repository](https://gitlab.physik.uni-muenchen.de/Oriol.Tinto/debug-autosubmit/-/tree/Issue993) I created I can reproduce the problem:

```
FROM python:3.9 

# Install and setup autosubmit
RUN pip install autosubmit
RUN mkdir autosubmit
RUN autosubmit configure  -db /autosubmit -dbf autosubmit.db -lr /autosubmit
RUN autosubmit install

# Proper version to create a new experiment from a repo:
# RUN autosubmit expid -min -d "debug" -repo "https://gitlab.physik.uni-muenchen.de/Oriol.Tinto/debug-autosubmit" -b master

###########################################
# Workaround until the bug is fix
RUN autosubmit expid -min -d "debug" 

RUN echo ' \n\
git:\n\
   PROJECT_ORIGIN: https://gitlab.physik.uni-muenchen.de/Oriol.Tinto/debug-autosubmit \n\
   PROJECT_BRANCH: Issue993 ' >> /autosubmit/a000/conf/minimal.yml

RUN sed 's/PROJECT_TYPE: local/PROJECT_TYPE: git/g' -i /autosubmit/a000/conf/minimal.yml
###########################################

# Adding some extra configuration
RUN echo ' \n\
settings:\n\
   independent: "REPLACED"\n\
   ' >> /autosubmit/a000/conf/extra_conf.yml


RUN autosubmit create a000 -np
RUN autosubmit inspect a000
CMD cat /autosubmit/a000/tmp/a000_DUMMY.cmd
```

**Comment by kinow** [comment]
In GitLab by @dbeltrankyl on Jun 30, 2023, 14:12

Ah, okay, I think now I understand what is the issue. I was not replicating it well. 

So what is happening is that:

* Autosubmit loads minimal 
* Autosubmit loads ( from 0 ) proj/conf.yaml
 at this step, the value is:
```yaml
settings:
  independent: "NOT replaced"
  dependent: "the independent variable was %settings.independent%"
```

* Autosubmit substitutes the %_% variables
```yaml
settings:
  independent: "NOT replaced"
  dependent: "the independent variable was NOT REPLACED"
```

* Autosubmit loads $expid/conf/extra-conf.yml

```yaml
settings:
  independent: "replaced"
  dependent: "the independent variable was NOT REPLACED"
```
*Autosubmit substitutes the %_% variables, but dependent no longer has a placeholder

```yaml
settings:
  independent: "replaced"
  dependent: "the independent variable was NOT REPLACED"
```

* Autosubmit appends the minimal.yml keys if they don't exist. 

This is the currently expected behavior of autosubmit.

To solve this concrete issue from Autosubmit maybe we could add a flag to not perform the substitution until all data is loaded...(and that flag is set) not sure what you think about it @kinow , @mcastril

**Comment by kinow** [comment]
In GitLab by @orioltinto on Jun 30, 2023, 14:16

Yes that's what I believe that happens, you explained it more clearly than me.

It would really make our life easier if the substitutions are made afterwards, not sure about how tricky it can be.

**Comment by kinow** [comment]
In GitLab by @dbeltrankyl on Jun 30, 2023, 14:27

I think it can be tricky because, in our current workflow, we have placeholders to load a preset of files. If we don't perform the substitution while loading the files, we won't load anything at all.

To be generic for all the workflows, from Autosubmit, the best I can think about is to have a flag to disable that behavior or enable it... and by default ( or the flag is disabled), it should be as it is now. 

edit: This flag would be a parameter set in the minimal CUSTOM_CONFIG I think, but let's wait for Miguel or/and Bruno answer

Another mixed solution, that would be complex to understand and implement ( I think ) is to provide a memory of where the placeholders where and replace them even if they are already replaced

**Comment by kinow** [comment]
In GitLab by @dbeltrankyl on Jul 6, 2023, 14:21

We had an AS meeting today and agreed to have a middle-ground approach.

We will keep the behavior as it is but, 

We will add the possibility of adding a special char to any placeholder that will indicate to AS that it will be only substituted after all the configuration is loaded. 

Going back to the previous example, the syntax I want to add is similar to:


* Autosubmit loads minimal 
* Autosubmit loads ( from 0 ) proj/conf.yaml
 at this step, the value is:
```yaml
settings:
  independent: "NOT replaced"
  dependent: "the independent variable was %^settings.independent%"
```

* Autosubmit substitutes the %_% variables
```yaml
settings:
  independent: "NOT replaced"
  dependent: "the independent variable was %^settings.independent%"
```

* Autosubmit loads $expid/conf/extra-conf.yml

```yaml
settings:
  independent: "replaced"
  dependent: "the independent variable was %^settings.independent%"
```
*Autosubmit substitutes the %_% variables

```yaml
settings:
  independent: "replaced"
  dependent: "the independent variable was %^settings.independent%"
```

* Autosubmit appends the minimal.yml keys if they don't exist. 

*Autosubmit substitutes the %^_% variables

```yaml
settings:
  independent: "replaced"
  dependent: "the independent variable was replaced"
```
