### ISSUE TITLE
Conditional selection of platform

### ISSUE THREAD

**Issue by kinow** [BSC-ES/autosubmit#996]
In GitLab by @orioltinto on Mar 24, 2023, 15:02

Hello @dbeltrankyl and @kinow,

### Summary
I would like to select the platform conditionally, is there a way of doing that?

Let me show an example:

To prepare **I**nitial **C**onditions we might have two possibilities:
- 1) the **IC** files are already in the remote platform.
- 2) the **IC** files are in the local platform.

Then we have a configuration like:
```yaml
initial_conditions:
  # Is the data in the local system?
  local: True
  # Where are we getting our initial data from?
  parent_folder: /path/to/initial/conditions
```

Depending on **INITIAL_CONDITIONS.LOCAL** we would need to run a job locally or in the HPC.

I could do that by adding two jobs (for example: PREPARE_FROM_LOCAL, PREPARE_FROM_REMOTE) and inside the template check the value of **INITIAL_CONDITIONS.LOCAL**. However I feel like there must be a cleaner way of doing that.

Thanks in advance.

()

**Comment by kinow** [comment]
In GitLab by @dbeltrankyl on Mar 24, 2023, 16:39

Hello @orioltinto , 

Maybe, something like this? 

```yaml
DEFAULT:
  CUSTOM_CONFIG: 
    PRE:
     - # Load all files or at least the ones that are loading the INITIAL_CONDITION value and common values between platforms
     - "%PROJDIR%/conf/%INITIAL_CONDITIONS%/jobs.yml"

INITIAL_CONDITIONS: LOCAL
 
```
file: "%PROJDIR%/conf/LOCAL/jobs.yml

```yaml
JOBS: 
 PREPARE_INITIAL_CONDITIONS:
   PLATFORM: LOCAL

```

Additional info, just if it helps you...

The only conditional that we have inside the workflow ( at the moment ) 

are optional dependencies, dependencies that can fail ( marked with ? ) in any %JOBS.$JOBSECTION%


`DEPENDENCIES: PREP? SIM`
